# Generated by Django 5.2 on 2026-03-10 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("payments", "0032_consumable_standalone_invoice"),
        ("provisioning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisioningVPS",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROVISIONING", "Provisioning"),
                            ("ACTIVE", "Active"),
                            ("ERROR", "Error"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, default=None, null=True)),
                ("ssh_user", models.CharField(blank=True, default="", max_length=100)),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("root_password_encrypted", models.TextField(blank=True, default="")),
                ("external_id", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("plan_slug", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("provisioned_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                (
                    "consumed_consumable",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Consumable used at request time; used to reimburse on provisioning failure.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.consumable",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "vendor",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="provisioning.provisioningvendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provisioning VPS",
                "verbose_name_plural": "Provisioning VPS",
            },
        ),
    ]
