# Generated by Django 5.2 on 2026-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0002_add_provisioning_vps"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvps",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the VPS was deprovisioned; useful for vendor charge analysis (e.g. active duration).",
                null=True,
            ),
        ),
    ]
