# Generated by Django 3.2.19 on 2023-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0004_auto_20230611_0534"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningbill",
            name="stripe_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
