# Generated by Django 5.2 on 2026-03-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0005_alter_provisioningacademy_vendor_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningacademy",
            name="connection_status",
            field=models.CharField(
                choices=[("UNTESTED", "Untested"), ("OK", "OK"), ("DEGRADED", "Degraded"), ("ERROR", "Error")],
                db_index=True,
                default="UNTESTED",
                help_text="Last known vendor API connection health (updated by connection checks).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="provisioningacademy",
            name="connection_status_text",
            field=models.CharField(
                blank=True, help_text="Vendor or error detail for the last connection test.", max_length=512
            ),
        ),
        migrations.AddField(
            model_name="provisioningacademy",
            name="connection_test_at",
            field=models.DateTimeField(blank=True, help_text="When the last connection test was run.", null=True),
        ),
    ]
