# Generated by Django 3.2.19 on 2023-07-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0006_provisioningbill_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningbill',
            name='vendor',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='provisioning.provisioningvendor'),
        ),
        migrations.AlterField(
            model_name='provisioningactivity',
            name='multiplier',
            field=models.FloatField(blank=True,
                                    default=1,
                                    help_text='To increase price in a certain percentage'),
        ),
    ]
