# Generated by Django 5.2 on 2026-03-27 01:25

from django.db import migrations, models


def backfill_vendor_type(apps, schema_editor):
    ProvisioningVendor = apps.get_model("provisioning", "ProvisioningVendor")

    vps_names = {"hostinger"}
    coding_editor_names = {"codespaces", "gitpod"}
    llm_names = {"litellm"}

    for vendor in ProvisioningVendor.objects.all().only("id", "name", "vendor_type"):
        slug = (vendor.name or "").strip().lower()
        if slug in vps_names:
            vendor.vendor_type = "VPS_SERVER"
        elif slug in llm_names:
            vendor.vendor_type = "LLM"
        elif slug in coding_editor_names:
            vendor.vendor_type = "CODING_EDITOR"
        else:
            vendor.vendor_type = "CODING_EDITOR"
        vendor.save(update_fields=["vendor_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0006_provisioningacademy_connection_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvendor",
            name="vendor_type",
            field=models.CharField(
                choices=[("CODING_EDITOR", "Coding Editor"), ("VPS_SERVER", "VPS Server"), ("LLM", "LLM")],
                db_index=True,
                default="CODING_EDITOR",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_vendor_type, migrations.RunPython.noop),
    ]
