# Generated by Django 5.2 on 2026-03-30 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("provisioning", "0007_provisioningvendor_vendor_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisioningLLM",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Identifier of the user in the external LLM provider.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("DEPROVISIONED", "Deprovisioned"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message encountered while provisioning/deprovisioning with the LLM provider.",
                    ),
                ),
                (
                    "deprovisioned_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the user was deprovisioned in the LLM provider (if applicable).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "vendor",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="provisioning.provisioningvendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provisioning LLM",
                "verbose_name_plural": "Provisioning LLM",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "academy", "vendor"), name="uniq_provisioning_llm_per_user_academy_vendor"
                    )
                ],
            },
        ),
    ]
