# Generated by Django 3.2.19 on 2023-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0007_auto_20230703_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningbill',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
