# Generated by Django 5.2 on 2026-07-08 19:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0008_provisioningllm"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningllm",
            name="last_budget_sync_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When team member budget was last aligned with BreatheCode consumables (member_update).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provisioningllm",
            name="last_budget_sync_error",
            field=models.TextField(
                blank=True, default="", help_text="Last team member budget alignment error message, if any."
            ),
        ),
        migrations.AddField(
            model_name="provisioningllm",
            name="last_known_spend",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="Last LiteLLM team-member spend synced into BreatheCode (USD) for delta FEFO.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="provisioningllm",
            name="litellm_team_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LiteLLM team_id used on last sync; mismatch with academy vendor_settings resets last_known_spend.",
                max_length=64,
            ),
        ),
    ]
