# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0008_provisioningllm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisioningvps",
            name="consumed_consumable",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Current consumable for this VPS (set at request or last renewal); used to reimburse on failure or mid-cycle delete.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.consumable",
            ),
        ),
    ]
