# Generated by Django 3.2.19 on 2023-07-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0012_provisioningbill_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisioningbill",
            name="title",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="This title should describe what the Bill is about. I.e.: April's bill. (MAX 64 chars)",
                max_length=64,
                null=True,
            ),
        ),
    ]
