# Generated by Django 5.2 on 2025-04-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0017_alter_provisioninguserconsumption_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisioningbill",
            name="fee",
            field=models.DecimalField(decimal_places=9, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="provisioningbill",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="provisioningconsumptionevent",
            name="quantity",
            field=models.DecimalField(decimal_places=9, help_text="Quantity of the product consumed", max_digits=18),
        ),
        migrations.AlterField(
            model_name="provisioningprice",
            name="multiplier",
            field=models.DecimalField(
                decimal_places=2, default=1, help_text="To increase price in a certain percentage", max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="provisioningprice",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=9, help_text="Price paid to the provisioning vendor, E.g: Github", max_digits=13
            ),
        ),
        migrations.AlterField(
            model_name="provisioninguserconsumption",
            name="amount",
            field=models.DecimalField(
                decimal_places=9, default=0, help_text="Amount of the product consumed", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="provisioninguserconsumption",
            name="hash",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="provisioninguserconsumption",
            name="quantity",
            field=models.DecimalField(
                decimal_places=9, default=0, help_text="Quantity of the product consumed", max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="provisioninguserconsumption",
            name="status_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
