# Generated by Django 3.2.21 on 2023-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_auto_20230811_0645"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmanager",
            name="attemps",
            field=models.IntegerField(default=1),
        ),
    ]
