# Generated by Django 3.1 on 2020-08-06 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("score", models.CharField(blank=True, max_length=250)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "enity_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event"),
                            ("CERTIFICATE", "Certificate"),
                            ("WORKSHOP", "Workshop"),
                            ("MENTOR", "Mentor"),
                            ("ACADEMY", "Academy"),
                            ("COHORT", "Cohort"),
                        ],
                        max_length=12,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                ("entity_slug", models.SlugField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
