# Generated by Django 3.1.2 on 2020-10-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_auto_20201009_2018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("ANSWERED", "Answered"), ("EXPIRED", "Expired")],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
