# Generated by Django 3.2.7 on 2021-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0020_alter_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="nps_previous_rating",
            field=models.FloatField(
                blank=True, default=None, help_text="Automatically calculated based on NPS survay responses", null=True
            ),
        ),
    ]
