# Generated by Django 3.2.7 on 2021-11-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "__first__"),
        ("feedback", "0021_review_nps_previous_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="mentorship_session",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentorship.mentorshipsession",
            ),
        ),
    ]
