# Generated by Django 3.2.7 on 2021-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0022_answer_mentorship_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
