# Generated by Django 3.2.15 on 2022-08-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0025_alter_review_nps_previous_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="avg_score",
        ),
        migrations.AddField(
            model_name="survey",
            name="scores",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
