# Generated by Django 3.2.18 on 2023-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0026_auto_20220830_0808"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
