# Generated by Django 3.2.18 on 2023-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0027_review_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="lang",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
