# Generated by Django 5.0.7 on 2024-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0028_review_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question_by_slug",
            field=models.CharField(
                blank=True, choices=[("PLATFORM", "Platform")], default=None, max_length=30, null=True
            ),
        ),
    ]
