# Generated by Django 5.1.6 on 2025-02-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0062_event_recording_url"),
        ("feedback", "0029_answer_question_by_slug"),
        ("registry", "0054_merge_20241216_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="asset",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="registry.asset"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="live_class",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="events.liveclass"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="is_customized",
            field=models.BooleanField(
                default=False, help_text="Customized surveys are not based on the default questions for a cohort"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question_by_slug",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Ideal to create new standarized questions",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="max_assistants_to_ask",
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="max_teachers_to_ask",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
