# Generated by Django 3.1 on 2020-09-07 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspecialty",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userspecialty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
