# Generated by Django 3.1 on 2020-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0002_auto_20200907_2333"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspecialty",
            name="signed_by",
            field=models.CharField(default="Bob Dylan", max_length=100),
            preserve_default=False,
        ),
    ]
