# Generated by Django 3.2.6 on 2021-08-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0012_auto_20210805_0329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userspecialty",
            name="issued_at",
        ),
    ]
