# Generated by Django 5.1.7 on 2025-03-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("certificate", "0017_layoutdesign_foot_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="syllabuses",
            field=models.ManyToManyField(
                blank=True,
                help_text="This specialty can have multiple syllabi",
                related_name="specialties_with_many_syllabus",
                to="admissions.syllabus",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="syllabus",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="This specialty represents only one certificate",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialty_with_one_syllabus",
                to="admissions.syllabus",
            ),
        ),
    ]
