strings = {
    "es": {
        "event": {
            "title": "¿Qué tan probable es que recomiendes eventos como este a tus familiares y amigos?",
            "highest": "muy probable",
            "lowest": "poco probable",
            "survey_subject": "Una pregunta sobre el evento al que atendiste hoy",
        },
        "mentor": {
            "title": "¿Cómo ha sido tu experiencia con el mentor {} hasta este momento?",
            "highest": "muy buena",
            "lowest": "mala",
            "survey_subject": "Una pregunta sobre tu mentor",
        },
        "cohort": {
            "title": "¿Cómo ha sido tu experiencia estudiando {} hasta este momento?",
            "highest": "muy buena",
            "lowest": "mala",
            "survey_subject": "Una pregunta sobre tu cohort",
        },
        "academy": {
            "title": "Según tu experiencia hasta ahora, ¿qué tan probable es que recomiendes {} a otras personas?",
            "highest": "muy probable",
            "lowest": "poco probable",
            "survey_subject": "Una pregunta sobre la academia",
        },
        "mentorship_session": {
            "title": "¿Cómo fue tu experiencia en tu mentoría con {}?",
            "highest": "muy útil",
            "lowest": "poco útil",
            "survey_subject": "Una pregunta sobre tu ultima sesion de mentoría",
        },
        "platform": {
            "title": "¿Cómo ha sido tu experiencia con la plataforma y el contenido hasta este momento?",
            "highest": "muy buena",
            "lowest": "mala",
            "survey_subject": "Una pregunta sobre la plataforma de enseñanza",
        },
        "live_class": {
            "title": "¿Cómo fue la clase de hoy?",
            "highest": "muy buena",
            "lowest": "mala",
            "survey_subject": "¿Cómo fue la clase de hoy?",
        },
        "liveclass_mentor": {
            "title": "¿Valora el desempeño de tu profe el día de hoy?",
            "highest": "muy bien",
            "lowest": "mal",
            "survey_subject": "Una pregunta sobre tu profe durante la clase",
        },
        "mentor_communication": {
            "title": "¿Qué tan claro fue @l profe al explicar los conceptos?",
            "highest": "muy bueno",
            "lowest": "malo",
            "survey_subject": "Una pregunta sobre tu profe durante la clase",
        },
        "mentor_participation": {
            "title": "¿@l profe fomentó la participación y resolvió tus dudas de manera efectiva?",
            "highest": "muy bien",
            "lowest": "mal",
            "survey_subject": "Una pregunta sobre tu profe durante la clase",
        },
        "button_label": "Responder",
        "survey_subject": "Necesitamos tu feedback",
        "survey_message": "Por favor toma 5 minutos para enviarnos un feedback",
    },
    "en": {
        "event": {
            "title": "How likely are you to recommend events like this to your friends and family?",
            "highest": "very likely",
            "lowest": "not likely",
            "survey_subject": "One question about the event you attended today",
        },
        "mentor": {
            "title": "How has your experience been with your mentor {} so far?",
            "highest": "very good",
            "lowest": "not good",
            "survey_subject": "One question about your mentor",
        },
        "cohort": {
            "title": "How has your experience been studying {} so far?",
            "highest": "very good",
            "lowest": "not good",
            "survey_subject": "One question about your cohort",
        },
        "academy": {
            "title": "Based on your experience so far, how likely are you to recommend {} to others?",
            "highest": "very likely",
            "lowest": "not likely",
            "survey_subject": "One question about the academy",
        },
        "mentorship_session": {
            "title": "How was your experience in your mentoring session with {}?",
            "highest": "very useful",
            "lowest": "not useful",
            "survey_subject": "One question about your last mentoring session",
        },
        "platform": {
            "title": "How has your experience been with the platform and content so far?",
            "highest": "very good",
            "lowest": "not good",
            "survey_subject": "One question about the learning platform",
        },
        "live_class": {
            "survey_subject": "How was today's class?",
            "title": "How was today's class?",
            "highest": "very good",
            "lowest": "not good",
        },
        "liveclass_mentor": {
            "title": "How would you rate your teacher's performance today?",
            "highest": "very good",
            "lowest": "not good",
            "survey_subject": "One question about the live class mentor",
        },
        "mentor_communication": {
            "title": "How clear was the teacher in explaining the concepts?",
            "highest": "very clear",
            "lowest": "not clear",
            "survey_subject": "One question about the live class mentor communication",
        },
        "mentor_participation": {
            "title": "Did the teacher encourage participation and effectively resolve your doubts?",
            "highest": "very good",
            "lowest": "not good",
            "survey_subject": "One question about the live class mentor practice",
        },
        "button_label": "Answer",
        "survey_subject": "We need your feedback",
        "survey_message": "Please take 5 minutes to give us feedback",
    },
}
