image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: redis-server
  - init: |
      python -m scripts.install &&
      gp sync-done deps
    command: pipenv run celery
  - init: gp sync-await deps
    command: >
      ./scripts/utils/wait-port.sh localhost 5432 &&
      (psql -U gitpod -c 'CREATE DATABASE breathecode;' || true) &&
      (psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d breathecode || true) &&
      export CACHE=0 &&
      pipenv run migrate &&
      pipenv run python manage.py loaddata breathecode/*/fixtures/dev_*.json &&
      pipenv run python manage.py create_academy_roles &&
      export CACHE=1 &&
      pipenv run start;
  - init: gp sync-await deps

vscode:
  extensions:
    - ms-python.python
    - streetsidesoftware.code-spell-checker
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - gruntfuggly.todo-tree
    - redhat.vscode-yaml
    - ms-python.black-formatter
    - ms-python.isort
    - janisdd.vscode-edit-csv
    - tamasfe.even-better-toml
    - ms-python.flake8
    - donjayamanne.githistory
    - ms-python.debugpy
