image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: redis-server
  - init: python -m scripts.install
    command: pipenv run celery
  - init: python -m scripts.install
    command: >
      psql -U gitpod -c 'CREATE DATABASE breathecode;' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d breathecode &&
      pipenv run migrate &&
      pipenv run python manage.py loaddata breathecode/*/fixtures/dev_*.json &&
      pipenv run python manage.py create_roles &&
      pipenv run start;
