image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - command: redis-server
    - init: pipenv install --dev && cp -n .env.example .env
      command: >
        psql -U gitpod -c 'CREATE DATABASE breathecode;';
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d breathecode;
        pipenv run migrate;
        pipenv run python manage.py loaddata breathecode/*/fixtures/dev_*.json;
        pipenv run start;
    - init: pipenv install --dev && cp -n .env.example .env
      command: pipenv run celery


# Other commands
# python manage.py sync_admissions academies
# python manage.py sync_admissions certificates
# python manage.py sync_admissions cohorts
# python manage.py sync_admissions students --limit=5