# Generated by Django 5.2 on 2025-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="delivered_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of JWT-like tokens for flag validation in CTF challenges",
                null=True,
            ),
        ),
    ]
