# Generated by Django 3.0.7 on 2020-07-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_auto_20200703_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="associated_slug",
            field=models.SlugField(max_length=150),
        ),
    ]
