# Generated by Django 5.2 on 2026-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_learnpackwebhook_package_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnpackwebhook",
            name="event",
            field=models.CharField(max_length=60),
        ),
    ]
