# Generated by Django 5.2 on 2026-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_learnpackwebhook_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
