# Generated by Django 3.1.6 on 2021-02-05 04:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_auto_20210205_0426'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('assignments', '0005_task_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admissions.cohort',),
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
