# Generated by Django 3.2.20 on 2023-08-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0013_task_opened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rigobot_repository_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
