# Generated by Django 5.0.6 on 2024-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0017_assignmenttelemetry_task_telemetry_learnpackwebhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryDeletionOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("GITHUB", "GitHub")], default="GITHUB", max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ERROR", "Error"),
                            ("DELETED", "Deleted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("status_text", models.TextField(blank=True, default=None, null=True)),
                ("repository_user", models.CharField(max_length=100)),
                ("repository_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryWhiteList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("GITHUB", "GitHub")], default="GITHUB", max_length=15)),
                ("repository_user", models.CharField(max_length=100)),
                ("repository_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
