# Generated by Django 5.1.4 on 2024-12-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0021_alter_repositorydeletionorder_repository_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydeletionorder",
            name="notified_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
