# Generated by Django 5.1.6 on 2025-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0022_repositorydeletionorder_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnpackwebhook",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("DONE", "Done"), ("IGNORED", "Ignored"), ("ERROR", "Error")],
                default="PENDING",
                max_length=9,
            ),
        ),
    ]
