# Generated by Django 5.1.6 on 2025-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0023_alter_learnpackwebhook_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="completion_rate",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Completion rate from 0 to 100 of the exercise in percentage",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="engagement_score",
            field=models.FloatField(
                blank=True, default=None, help_text="Calculated score from 0 to 100 based on the telemetry", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="frustration_score",
            field=models.FloatField(
                blank=True, default=None, help_text="Calculated score 0 to 100 based on the telemetry", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="metrics",
            field=models.JSONField(
                blank=True, default=None, help_text="Calculated metrics based on the telemetry", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="metrics_algo_version",
            field=models.FloatField(
                blank=True, default=None, help_text="Version of the algorithm used to calculate the metrics", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmenttelemetry",
            name="total_time",
            field=models.DurationField(
                blank=True, default=None, help_text="Total time spent on the exercise", null=True
            ),
        ),
    ]
