# Generated by Django 5.1.6 on 2025-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0024_assignmenttelemetry_completion_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="The moment when the student checked the revision",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="The moment when the teacher marks the task as ACCEPTED or REJECTED",
                null=True,
            ),
        ),
    ]
