# Generated by Django 3.2.16 on 2022-11-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0047_merge_20220924_0611"),
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="score_threshold",
        ),
        migrations.AddField(
            model_name="assessment",
            name="next",
            field=models.URLField(default=False),
        ),
        migrations.CreateModel(
            name="AssessmentThreshold",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score_threshold",
                    models.IntegerField(
                        help_text="You can set a threshold to determine if the user score is successfull"
                    ),
                ),
                ("success_message", models.TextField(blank=True, default=None, null=True)),
                ("fail_message", models.TextField(blank=True, default=None, null=True)),
                ("success_next", models.URLField(blank=True, default=None, null=True)),
                ("fail_next", models.URLField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="If null it will be default, but if specified, the only this academy will have this threshold",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_thresholds",
                        to="assessment.assessment",
                    ),
                ),
            ],
        ),
    ]
