# Generated by Django 5.2 on 2025-11-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0010_alter_syllabusversion_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated string of technologies (e.g., 'Python, Django, PostgreSQL').",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academy that owns this career path.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_career_paths",
                        to="admissions.academy",
                    ),
                ),
            ],
            options={
                "ordering": ("job_role__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="CareerStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField(help_text="Position within the career path.")),
                ("title", models.CharField(max_length=150)),
                ("goal", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "career_path",
                    models.ForeignKey(
                        help_text="Career path that owns this stage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="talent_development.careerpath",
                    ),
                ),
            ],
            options={
                "ordering": ("career_path", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("leadership", "Leadership"),
                            ("functional", "Functional"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated string of technologies (e.g., 'Python, Django, PostgreSQL').",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [models.UniqueConstraint(fields=("slug",), name="uq_competency_slug")],
            },
        ),
        migrations.CreateModel(
            name="JobFamily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academy that owns this family, if None, it can be used across multiple academies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_job_families",
                        to="admissions.academy",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_model",
                    models.BooleanField(default=False, help_text="Model role can be used to create new roles."),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academy that owns this role. if None, it can be used across multiple academies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_job_roles",
                        to="admissions.academy",
                    ),
                ),
                (
                    "job_family",
                    models.ForeignKey(
                        help_text="Job family that owns this role.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_roles",
                        to="talent_development.jobfamily",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="careerpath",
            name="job_role",
            field=models.ForeignKey(
                help_text="Anchor role for this path.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_paths",
                to="talent_development.jobrole",
            ),
        ),
        migrations.CreateModel(
            name="CompetencySkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional relative weight (0-100) describing the skill impact.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        help_text="Parent competency.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competency_skills",
                        to="talent_development.competency",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill contributing to the competency.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_competencies",
                        to="talent_development.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillAttitudeTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.CharField(
                        help_text="Short mindset/attitude label (e.g., 'attention to detail').", max_length=150
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Optional elaboration of the attitude.")),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attitude_tags",
                        to="talent_development.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("skill", "tag"),
            },
        ),
        migrations.CreateModel(
            name="SkillBehaviorIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("foundation", "Foundation"), ("core", "Core"), ("applied", "Applied")], max_length=15
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Observable behavior that shows this skill at the given level."),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavioral_indicators",
                        to="talent_development.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("skill", "level"),
            },
        ),
        migrations.CreateModel(
            name="SkillDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
                "constraints": [models.UniqueConstraint(fields=("slug",), name="uq_skill_domain_slug")],
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="domain",
            field=models.ForeignKey(
                help_text="Domain that categorizes this skill.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="talent_development.skilldomain",
            ),
        ),
        migrations.CreateModel(
            name="SkillKnowledgeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Concept, fact, or principle a learner must understand to perform the skill."
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="talent_development.skill",
                    ),
                ),
            ],
            options={
                "ordering": ("skill", "id"),
            },
        ),
        migrations.CreateModel(
            name="StageCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_level",
                    models.CharField(
                        choices=[("foundation", "Foundation"), ("core", "Core"), ("applied", "Applied")],
                        default="core",
                        max_length=15,
                    ),
                ),
                ("is_core", models.BooleanField(default=True, help_text="Mark as False for optional competencies.")),
                (
                    "competency",
                    models.ForeignKey(
                        help_text="Competency required at this stage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_assignments",
                        to="talent_development.competency",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Stage that requires this competency.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_competencies",
                        to="talent_development.careerstage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="careerstage",
            index=models.Index(fields=["career_path", "sequence"], name="talent_deve_career__bbde5e_idx"),
        ),
        migrations.AddConstraint(
            model_name="careerstage",
            constraint=models.UniqueConstraint(fields=("career_path", "sequence"), name="uq_stage_path_sequence"),
        ),
        migrations.AddIndex(
            model_name="jobfamily",
            index=models.Index(fields=["is_active"], name="talent_deve_is_acti_3a0cb9_idx"),
        ),
        migrations.AddConstraint(
            model_name="jobfamily",
            constraint=models.UniqueConstraint(fields=("slug",), name="uq_job_family_slug"),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(fields=["is_active"], name="talent_deve_is_acti_a97bbb_idx"),
        ),
        migrations.AddConstraint(
            model_name="jobrole",
            constraint=models.UniqueConstraint(fields=("slug",), name="uq_job_role_slug"),
        ),
        migrations.AddConstraint(
            model_name="careerpath",
            constraint=models.UniqueConstraint(fields=("job_role", "name"), name="uq_career_path_role_name"),
        ),
        migrations.AddIndex(
            model_name="competencyskill",
            index=models.Index(fields=["competency", "skill"], name="talent_deve_compete_88f32c_idx"),
        ),
        migrations.AddConstraint(
            model_name="competencyskill",
            constraint=models.UniqueConstraint(fields=("competency", "skill"), name="uq_competency_skill"),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(fields=("slug",), name="uq_skill_slug"),
        ),
        migrations.AddIndex(
            model_name="stagecompetency",
            index=models.Index(fields=["stage", "competency"], name="talent_deve_stage_i_3d393e_idx"),
        ),
        migrations.AddConstraint(
            model_name="stagecompetency",
            constraint=models.UniqueConstraint(fields=("stage", "competency"), name="uq_stage_competency"),
        ),
    ]
