# Generated by Django 5.2 on 2026-03-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_development", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_level",
                    models.CharField(
                        choices=[("foundation", "Foundation"), ("core", "Core"), ("applied", "Applied")],
                        default="core",
                        help_text="Required proficiency level at this stage.",
                        max_length=15,
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(default=True, help_text="Mark as False for optional stage-anchored skills."),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill anchored to the stage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_skills",
                        to="talent_development.skill",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Stage that anchors this skill.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_skills",
                        to="talent_development.careerstage",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["stage", "skill"], name="talent_deve_stage_i_4b3da8_idx")],
                "constraints": [models.UniqueConstraint(fields=("stage", "skill"), name="uq_stage_skill")],
            },
        ),
    ]
