# Generated by Django 3.1.4 on 2021-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0018_credentialsgithub_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capability",
            name="slug",
            field=models.SlugField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
