# Generated by Django 3.2.9 on 2022-01-24 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authenticate", "0023_academyproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvite",
            name="author",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("WAITING_LIST", "Waiting list")],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
