# Generated by Django 3.2.9 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0024_auto_20220124_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                    ("WAITING_LIST", "Waiting list"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
