# Generated by Django 3.2.20 on 2023-08-05 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authenticate", "0041_auto_20230725_0322"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Descriptive and unique name of the app", max_length=25, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug for the app, it must be url friendly and please avoid to change it",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the app, it will appear on the authorize UI", max_length=255
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("HMAC_SHA256", "HMAC-SHA256"),
                            ("HMAC_SHA512", "HMAC_SHA512"),
                            ("ED25519", "ED25519"),
                        ],
                        default="HMAC_SHA512",
                        max_length=11,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[("JWT", "Json Web Token"), ("SIGNATURE", "Signature")], default="JWT", max_length=9
                    ),
                ),
                (
                    "schema",
                    models.CharField(
                        choices=[("LINK", "Link")],
                        default="LINK",
                        help_text="Schema to use for the auth process to r2epresent how the apps will communicate",
                        max_length=4,
                    ),
                ),
                (
                    "agreement_version",
                    models.IntegerField(default=1, help_text="Version of the agreement, based in the scopes"),
                ),
                ("private_key", models.CharField(blank=True, max_length=255)),
                ("public_key", models.CharField(blank=True, default=None, max_length=255, null=True)),
                (
                    "require_an_agreement",
                    models.BooleanField(
                        default=True, help_text="If true, the user will be required to accept an agreement"
                    ),
                ),
                ("webhook_url", models.URLField()),
                ("redirect_url", models.URLField()),
                ("app_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive and unique name that appears on the authorize UI",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.CharField(help_text="{action}:{data} for example read:repo", max_length=15, unique=True),
                ),
                ("description", models.CharField(help_text="Description of the scope", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OptionalScopeSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("optional_scopes", models.ManyToManyField(blank=True, to="authenticate.Scope")),
            ],
        ),
        migrations.CreateModel(
            name="LegacyKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("HMAC_SHA256", "HMAC-SHA256"),
                            ("HMAC_SHA512", "HMAC_SHA512"),
                            ("ED25519", "ED25519"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(choices=[("JWT", "Json Web Token"), ("SIGNATURE", "Signature")], max_length=9),
                ),
                ("schema", models.CharField(choices=[("LINK", "Link")], max_length=4)),
                ("private_key", models.CharField(blank=True, max_length=255)),
                ("public_key", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("webhook_url", models.URLField()),
                ("redirect_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="legacy_key", to="authenticate.app"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppUserAgreement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "agreement_version",
                    models.IntegerField(default=1, help_text="Version of the agreement that was accepted"),
                ),
                ("agreed_at", models.DateTimeField()),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="authenticate.app")),
                (
                    "optional_scope_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_user_agreement",
                        to="authenticate.optionalscopeset",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AppRequiredScope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agreed_at", models.DateTimeField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="m2m_required_scopes",
                        to="authenticate.app",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="m2m_required_scopes",
                        to="authenticate.scope",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppOptionalScope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agreed_at", models.DateTimeField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="m2m_optional_scopes",
                        to="authenticate.app",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="m2m_optional_scopes",
                        to="authenticate.scope",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="app",
            name="optional_scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="app_optional_scopes",
                through="authenticate.AppOptionalScope",
                to="authenticate.Scope",
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="required_scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="app_required_scopes",
                through="authenticate.AppRequiredScope",
                to="authenticate.Scope",
            ),
        ),
    ]
