# Generated by Django 3.2.22 on 2023-10-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0044_auto_20230908_1941"),
        ("authenticate", "0044_auto_20231017_0605"),
    ]

    operations = []
