# Generated by Django 5.1.1 on 2024-09-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0055_alter_profile_github_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academyauthsettings",
            name="google_cloud_owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Google auth token for this user will be used for any admin call to the google cloud api, for example: creating classroom video calls",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="google_cloud_academy_auth_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="academyauthsettings",
            name="github_owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Github auth token for this user will be used for any admin call to the google cloud api, for example: inviting users to the academy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
