# Generated by Django 5.1.1 on 2024-09-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0056_academyauthsettings_google_cloud_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialsgoogle",
            name="id_token",
            field=models.CharField(default="", max_length=1152),
        ),
    ]
