# Generated by Django 5.1.2 on 2024-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0058_credentialsgoogle_google_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleWebhook",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.SlugField(blank=True, help_text="base64 message provided by google", max_length=124),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done"), ("ERROR", "Error")],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                ("status_text", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
