# Generated by Django 5.1.2 on 2024-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0059_googlewebhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlewebhook",
            name="message",
            field=models.SlugField(blank=True, help_text="base64 message provided by google", max_length=512),
        ),
    ]
