# Generated by Django 5.1.6 on 2025-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0066_credentialsgithub_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialsgithub",
            name="granted",
            field=models.BooleanField(default=False, help_text="If true, the user has granted the scopes to the app"),
        ),
    ]
