# Generated by Django 5.1.6 on 2025-02-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0067_credentialsgithub_granted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notfoundanongoogleuser",
            name="id_token",
            field=models.CharField(default="", max_length=1400),
        ),
    ]
