# Generated by Django 5.2 on 2025-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0069_academyauthsettings_github_whitelist_exemption_users"),
        ("authenticate", "0069_userinvite_expires_at"),
    ]

    operations = []
