# Generated by Django 3.2.19 on 2023-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_page", models.IntegerField(blank=True, default=0, null=True)),
                ("total_pages", models.IntegerField(blank=True, default=0, null=True)),
                ("task_module", models.CharField(max_length=200)),
                ("task_name", models.CharField(max_length=200)),
                ("reverse_module", models.CharField(blank=True, max_length=200, null=True)),
                ("reverse_name", models.CharField(blank=True, max_length=200, null=True)),
                ("arguments", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed"),
                            ("PAUSED", "Paused"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("killed", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
