# Generated by Django 3.2.23 on 2023-11-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0004_taskwatcher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskmanager",
            old_name="attemps",
            new_name="attempts",
        ),
    ]
