# Generated by Django 5.0.1 on 2024-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0006_auto_20231209_0707"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmanager",
            name="started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="taskmanager",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
    ]
