# Generated by Django 5.2 on 2025-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="telemetry_stats",
            field=models.JSONField(
                blank=True, default=None, help_text="Daily stats about the telemetry of the asset", null=True
            ),
        ),
    ]
