# Generated by Django 3.1.6 on 2021-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='language',
        ),
        migrations.AddField(
            model_name='asset',
            name='gitpod',
            field=models.BooleanField(default=False),
        ),
    ]
