# Generated by Django 5.2 on 2025-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_asset_telemetry_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="flag_seed",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated seed for CTF and other delivery flags, this is used by the assignment app to validate the flags automatically",
                max_length=16,
                null=True,
            ),
        ),
    ]
