# Generated by Django 3.2.12 on 2022-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_asset_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="readme_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="This will be used to synch only lessons from github. Projects, quizzes and exercises it will try README.md for english and README.lang.md for other langs",
                null=True,
            ),
        ),
    ]
