# Generated by Django 3.1.6 on 2021-04-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20210409_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTechnology',
            fields=[
                ('slug',
                 models.SlugField(max_length=200,
                                  primary_key=True,
                                  serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTranslation',
            fields=[
                ('slug',
                 models.SlugField(max_length=2,
                                  primary_key=True,
                                  serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='solution_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lang',
            field=models.CharField(blank=True,
                                   default=None,
                                   max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OK', 'Ok'),
                                            ('WARNING', 'Warning'),
                                            ('ERROR', 'Error')],
                                   default='DRAFT',
                                   max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='technologies',
            field=models.ManyToManyField(to='registry.AssetTechnology'),
        ),
        migrations.AddField(
            model_name='asset',
            name='translations',
            field=models.ManyToManyField(to='registry.AssetTranslation'),
        ),
    ]
