# Generated by Django 5.2 on 2025-06-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_initial"),
        ("registry", "0003_asset_flag_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetFlag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flag_value",
                    models.CharField(
                        help_text="The flag string (e.g., FLAG{header.payload.signature})", max_length=500
                    ),
                ),
                (
                    "flag_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the flag, extracted from JWT payload or generated for legacy flags",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked"), ("EXPIRED", "Expired")],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Status of the flag",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When the flag expires (null means no expiration)",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the flag was revoked (null means not revoked)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Additional metadata about the flag (e.g., generation parameters, usage context)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The academy this flag is generated for (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="The asset this flag belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="registry.asset",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="User who generated this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="User who revoked this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The user this flag is generated for (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["asset", "status"], name="registry_as_asset_i_68cdb0_idx"),
                    models.Index(fields=["user", "asset"], name="registry_as_user_id_aaed06_idx"),
                    models.Index(fields=["academy", "asset"], name="registry_as_academy_923180_idx"),
                    models.Index(fields=["expires_at"], name="registry_as_expires_e30ac4_idx"),
                ],
                "unique_together": {("asset", "flag_id")},
            },
        ),
    ]
