# Generated by Django 5.2 on 2025-06-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_assetflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="registry.assetcategory"
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="lang",
            field=models.CharField(help_text="E.g: us, es, it", max_length=2),
        ),
    ]
