# Generated by Django 3.1.6 on 2021-04-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20210409_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAlias',
            fields=[
                ('slug',
                 models.SlugField(max_length=200,
                                  primary_key=True,
                                  serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='registry.asset')),
            ],
        ),
    ]
