# Generated by Django 3.2 on 2021-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_assetalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='config',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
