# Generated by Django 5.2 on 2025-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0005_alter_asset_category_alter_assetcategory_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="solution_readme",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
