# Generated by Django 5.2 on 2025-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0006_asset_solution_readme"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="allow_contributions",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indicates if the repo of the asset is public or private. if its public, it will be set as True, otherwise it will be set as False",
            ),
        ),
    ]
