# Generated by Django 3.2 on 2021-05-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_asset_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external',
            field=models.BooleanField(default=False, help_text='External assets will open in a new window, they are not built using breathecode or learnpack tecnology'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('EXERCISE', 'Exercise'), ('QUIZ', 'Quiz'), ('LESSON', 'Lesson'), ('LESSON', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='preview',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
