# Generated by Django 5.2 on 2025-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0007_asset_allow_contributions"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="learnpack_id",
            field=models.IntegerField(
                blank=True, default=None, help_text="LearnPack ID of the asset, used for better integration", null=True
            ),
        ),
    ]
