# Generated by Django 3.2.9 on 2021-12-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20210517_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='authors_username',
            field=models.CharField(blank=True,
                                   default=None,
                                   help_text='Github usernames separated by comma',
                                   max_length=80,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('UNNASIGNED', 'Unnasigned'), ('DRAFT', 'Draft'), ('OK', 'Ok'),
                                            ('WARNING', 'Warning'), ('ERROR', 'Error')],
                                   default='DRAFT',
                                   max_length=20),
        ),
    ]
