# Generated by Django 5.2 on 2026-01-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("registry", "0008_asset_learnpack_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSite",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "domain_url",
                    models.URLField(
                        help_text="Base domain URL for the content site (e.g., https://content.4geeks.com)"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "auto_generate_previews",
                    models.BooleanField(default=False, help_text="Whether to automatically generate preview images"),
                ),
                (
                    "preview_generation_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="URL endpoint for generating preview images (will be POSTed to)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="The academy this content site belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="content_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The content site this category is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="registry.contentsite",
            ),
        ),
    ]
