# Generated by Django 3.2.9 on 2022-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20211221_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
