# Generated by Django 5.2 on 2026-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0009_contentsite_assetcategory_content_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="github_activity_log",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="JSON array (max 10 objects, newest first) logging GitHub-related activity: pulls, pushes, webhooks, scheduled jobs, and academy API actions. Each object includes ``kind`` and ``kind_help_text`` (English). Written by Celery tasks, academy views, and the GitHub webhook handler. Update via registry.utils.record_github_activity. API exposes this as ``github_activity_logs`` (array) on asset payloads.",
                null=True,
            ),
        ),
    ]
