# Generated by Django 3.2.9 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_alter_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='readme_url',
            field=models.URLField(blank=True,
                                  default=None,
                                  help_text='This will be used to synch from github',
                                  null=True),
        ),
    ]
