# Generated by Django 3.2.12 on 2022-03-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20220315_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='translations',
        ),
        migrations.AddField(
            model_name='asset',
            name='other_translations',
            field=models.ManyToManyField(blank=True,
                                         null=True,
                                         related_name='_registry_asset_other_translations_+',
                                         to='registry.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lang',
            field=models.CharField(blank=True,
                                   default=None,
                                   help_text='E.g: en, es, it',
                                   max_length=2,
                                   null=True),
        ),
        migrations.DeleteModel(name='AssetTranslation', ),
    ]
