# Generated by Django 5.2 on 2026-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0012_asseterrorlog_dedup_and_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="manifest",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="LearnPack Cloud published manifest snapshot (lessons, titles, etc.)",
                null=True,
            ),
        ),
    ]
