# Generated by Django 3.2.12 on 2022-03-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20220323_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='other_translations',
            field=models.ManyToManyField(related_name='_registry_asset_other_translations_+',
                                         to='registry.Asset'),
        ),
    ]
