# Generated by Django 5.2 on 2026-07-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0013_alter_asset_is_seo_tracked_default"),
        ("registry", "0013_asset_manifest"),
    ]

    operations = []
