# Generated by Django 3.2.12 on 2022-03-23 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessment_original'),
        ('registry', '0014_alter_asset_other_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assessment',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='Connection with the assessment breathecode app',
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='assessment.assessment'),
        ),
    ]
