# Generated by Django 5.2 on 2026-10-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_asset_graded_help_text'),
        ('talent_development', '0003_skillalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='skills_source',
            field=models.CharField(blank=True, choices=[('FILE', 'File'), ('INHERITED', 'Inherited')], default=None, help_text='FILE if the source file declares skills, INHERITED if they were copied from a translation, empty if the source file never declared skills', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AssetSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('core', 'Core'), ('applied', 'Applied')], default=None, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_skills', to='registry.asset')),
                ('skill', models.ForeignKey(help_text='Remove the skill from every asset source file before deleting it', on_delete=django.db.models.deletion.PROTECT, related_name='asset_skills', to='talent_development.skill')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Synced from the asset source file (learn.json, frontmatter or quiz json), read only', related_name='assets', through='registry.AssetSkill', to='talent_development.skill'),
        ),
        migrations.AddConstraint(
            model_name='assetskill',
            constraint=models.UniqueConstraint(fields=('asset', 'skill'), name='uq_asset_skill'),
        ),
    ]
