# Generated by Django 3.2.12 on 2022-03-24 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0015_asset_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetErrorLog',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('status',
                 models.CharField(choices=[('ERROR', 'Error'), ('FIXED', 'Fixed'), ('IGNORED', 'Ignored')],
                                  default='ERROR',
                                  max_length=20)),
                ('status_code', models.IntegerField()),
                ('status_text',
                 models.TextField(
                     blank=True,
                     default=None,
                     help_text='Status details, it may be set automatically if enough error information',
                     null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset',
                 models.ForeignKey(
                     default=None,
                     help_text=
                     'Assign an asset to this error and you will be able to create an alias for it from the django admin bulk actions "create alias"',
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='registry.asset')),
                ('user',
                 models.ForeignKey(default=None,
                                   help_text='The user how asked for the asset and got the error',
                                   null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
