# Generated by Django 3.2.16 on 2022-10-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0016_assettechnology_sort_priority"),
        ("registry", "0016_auto_20221029_0531"),
    ]

    operations = []
