# Generated by Django 3.2.16 on 2023-02-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0052_alter_cohort_kickoff_date"),
        ("registry", "0023_merge_20230105_0103"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalityScan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("success", models.BooleanField(blank=True, default=None, null=True)),
                ("score_original", models.FloatField(blank=True, default=None, null=True)),
                ("score_ai", models.FloatField(blank=True, default=None, null=True)),
                ("credits_used", models.IntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ERROR", "Error"),
                            ("COMPLETED", "Completed"),
                            ("WARNING", "Warning"),
                        ],
                        default="PENDING",
                        help_text="Scan for originality",
                        max_length=20,
                    ),
                ),
                ("status_text", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registry.asset")),
            ],
        ),
        migrations.CreateModel(
            name="CredentialsOriginality",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255)),
                ("balance", models.FloatField(default=0)),
                ("usage", models.JSONField(default=[])),
                ("last_call_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
    ]
