# Generated by Django 3.2.16 on 2023-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0025_alter_credentialsoriginality_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcategory",
            name="all_translations",
            field=models.ManyToManyField(
                blank=True, related_name="_registry_assetcategory_all_translations_+", to="registry.AssetCategory"
            ),
        ),
    ]
