# Generated by Django 3.2.16 on 2023-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0026_assetcategory_all_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="github_commit_hash",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
