# Generated by Django 3.2.20 on 2023-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0032_contentvariable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvariable",
            name="default_value",
            field=models.TextField(
                help_text="If the variable type is fetch or code and the processing fails, the default value will be used"
            ),
        ),
    ]
