# Generated by Django 3.2.22 on 2023-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_auto_20231017_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettechnology',
            name='is_deprecated',
            field=models.BooleanField(
                default=True,
                help_text='If False, the frontend will generate a landing for this technology.'),
        ),
    ]
