# Generated by Django 3.2.22 on 2023-11-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_auto_20231017_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='related_assets',
            field=models.ManyToManyField(
                blank=True,
                help_text='Related assets used to get prepared before going through this asset.',
                null=True,
                related_name='_registry_asset_related_assets_+',
                to='registry.Asset'),
        ),
    ]
