# Generated by Django 5.1.1 on 2024-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0043_asset_superseded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="learnpack_deploy_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Only applies to LearnPack tutorials that have been published in the LearnPack cloud",
                null=True,
            ),
        ),
    ]
