# Generated by Django 5.1.1 on 2024-09-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0043_asset_superseded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="agent",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="If value is vscode, then we recommend to open this exercise/project in vscode and instructions will be different. If it is standalone, then you can open it directly from the terminal",
                max_length=20,
                null=True,
            ),
        ),
    ]
