# Generated by Django 5.1.1 on 2024-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0047_asset_preview_in_tutorial_alter_asset_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="dependencies",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Automatically calculated based on the package.json, pipfile or alternatives. String like: python=3.10,node=16.0",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_template",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Automatically set by the system, if true, it means that this asset is set as template by another asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="template_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="This template will be used to open the asset (only applied for projects)",
                null=True,
            ),
        ),
    ]
