# Generated by Django 5.1.2 on 2024-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0047_asset_preview_in_tutorial_alter_asset_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettechnology",
            name="marketing_information",
            field=models.JSONField(
                blank=True, default=None, help_text="JSON structure for marketing information", null=True
            ),
        ),
    ]
