# Generated by Django 5.1.2 on 2024-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0049_remove_asset_is_template_alter_asset_asset_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontext",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PROCESSING", "Processing"), ("DONE", "Done"), ("ERROR", "Error")],
                db_index=True,
                default="PENDING",
                help_text="If pending, it means it hasn't been generated yet, processing means that is being generated at this moment, done means it has been generated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetcontext",
            name="status_text",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Status details, it may be set automatically if enough error information",
                null=True,
            ),
        ),
    ]
