# Generated by Django 5.1.2 on 2024-12-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0091_course_cohorts_order"),
        ("registry", "0052_assettechnology_marketing_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettechnology",
            name="featured_course",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The featured course for this technology",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketing.course",
            ),
        ),
    ]
