# Generated by Django 5.1.1 on 2024-12-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0052_assettechnology_marketing_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="template_url",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="This template will be used to open the asset (only applied for projects). If project has no template it should state 'self' as template url",
                max_length=500,
                null=True,
            ),
        ),
    ]
