# Generated by Django 5.1.3 on 2024-12-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0053_alter_asset_template_url"),
        ("registry", "0053_assettechnology_featured_course"),
    ]

    operations = []
