# Generated by Django 5.1.6 on 2025-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0055_asset_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="feature",
            field=models.BooleanField(
                default=False,
                help_text="If true, it will be shown in the landing pages of the website for marketing purposes",
            ),
        ),
    ]
