# Generated by Django 3.0.7 on 2020-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0010_automation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[("2", "Active"), ("1", "Innactive"), ("0", "Uknown")],
                default="0",
                help_text="2 = inactive, 1=active",
            ),
        ),
    ]
