# Generated by Django 3.0.7 on 2020-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0013_auto_20200619_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[("STRONG", "Strong"), ("SOFT", "Soft"), ("DISCOVERY", "Discovery"), ("OTHER", "Other")],
                default=None,
                help_text="The STRONG tags in a lead will determine to witch automation it does unless there is an 'automation' property on the lead JSON",
                max_length=15,
                null=True,
            ),
        ),
    ]
