# Generated by Django 3.1.1 on 2020-09-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0019_auto_20200921_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="gclid",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
