# Generated by Django 3.1.3 on 2020-11-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0025_auto_20201110_0001"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="utm_source",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
