# Generated by Django 3.2.4 on 2021-07-03 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0037_auto_20210608_0627"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="won_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
