# Generated by Django 3.2.8 on 2021-10-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0039_formentry_ac_expected_cohort"),
        ("marketing", "0040_formentry_current_download"),
    ]

    operations = []
