# Generated by Django 3.2.9 on 2022-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0052_utmfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, default=None, help_text="How is this tag being used? Why is it needed?", null=True
            ),
        ),
    ]
