# Generated by Django 3.2.15 on 2022-10-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0047_merge_20220924_0611"),
        ("marketing", "0058_alter_formentry_storage_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admissions.academy",),
        ),
        migrations.AlterField(
            model_name="leadgenerationapp",
            name="app_id",
            field=models.CharField(
                help_text="Unique token generated only for this app, can be reset to revoke access",
                max_length=255,
                unique=True,
            ),
        ),
    ]
