# Generated by Django 3.2.16 on 2023-02-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0062_alter_formentry_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="ac_deal_owner_full_name",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="formentry",
            name="ac_deal_owner_id",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="formentry",
            name="ac_expected_cohort_date",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Which date is this student expecting to join",
                max_length=100,
                null=True,
            ),
        ),
    ]
