# Generated by Django 3.2.18 on 2023-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0072_alter_formentry_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="attribution_id",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="Keep a consistent attribution from al the previous applications from the same email (it will reset to a new one for each WON)",
                null=True,
            ),
        ),
    ]
