# Generated by Django 5.0.3 on 2024-04-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0084_merge_20240322_1818"),
        ("marketing", "0084_merge_20240329_1501"),
    ]

    operations = []
