# Generated by Django 5.1.1 on 2024-09-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0088_alter_formentry_storage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activecampaignacademy",
            name="crm_vendor",
            field=models.CharField(
                choices=[("ACTIVE_CAMPAIGN", "Active Campaign"), ("BREVO", "Brevo")],
                default="ACTIVE_CAMPAIGN",
                help_text="Only one vendor allowed per academy, defaults to active campaign",
                max_length=20,
            ),
        ),
    ]
