# Generated by Django 5.1.2 on 2024-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0092_coursetranslation_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetranslation",
            name="heading",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Heading that will be used in the landing page",
                max_length=400,
                null=True,
            ),
        ),
    ]
