# Generated by Django 5.1.5 on 2025-02-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0093_alter_coursetranslation_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="course",
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="lead_generation_app",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Other apps can send leads to breathecode but they need to be registered here",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketing.leadgenerationapp",
            ),
        ),
    ]
