# Generated by Django 5.1.6 on 2025-03-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0095_remove_course_cohorts_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_listed",
            field=models.BooleanField(default=True, help_text="controls inclusion in browser listings and sitemaps"),
        ),
    ]
