# Generated by Django 5.1.6 on 2025-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0096_course_is_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetranslation",
            name="featured_assets",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Comma separated list of asset slugs featured in this course translation.",
                max_length=500,
                null=True,
            ),
        ),
    ]
