# Generated by Django 5.2 on 2025-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0098_alter_course_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetranslation",
            name="preview_url",
            field=models.URLField(
                blank=True, default=None, help_text="Preview URL used for marketing purposes.", null=True
            ),
        ),
    ]
