# Generated by Django 5.2 on 2025-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_add_monitoring_error"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="monitoringerror",
            new_name="monitoring__created_54bc3f_idx",
            old_name="monitoring_m_created_idx",
        ),
        migrations.RenameIndex(
            model_name="monitoringerror",
            new_name="monitoring__academy_4a6bd7_idx",
            old_name="monitoring_m_academy__idx",
        ),
        migrations.RenameIndex(
            model_name="monitoringerror",
            new_name="monitoring__monitor_fc3390_idx",
            old_name="monitoring_m_monitor_idx",
        ),
        migrations.RenameIndex(
            model_name="monitoringerror",
            new_name="monitoring__severit_af59bf_idx",
            old_name="monitoring_m_severit_idx",
        ),
    ]
