# Generated by Django 3.1.2 on 2020-10-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_auto_20201021_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status_text",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="status_text",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
