# Generated by Django 5.2 on 2025-12-20 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("monitoring", "0003_rename_monitoring_m_created_idx_monitoring__created_54bc3f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurnAlert",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("INACTIVITY", "Inactive for 7+ days"),
                            ("ENGAGEMENT_DROP", "Engagement dropped significantly"),
                            ("HIGH_FRUSTRATION", "High frustration detected"),
                            ("PAYMENT_RISK", "Payment issues"),
                            ("TRIAL_EXPIRING", "Trial expiring without conversion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        max_length=10,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True, help_text="What intervention was done", null=True)),
                ("metrics_snapshot", models.JSONField(default=dict)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_alerts",
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["academy", "severity", "-triggered_at"], name="monitoring__academy_8e594f_idx"
                    ),
                    models.Index(fields=["user", "-triggered_at"], name="monitoring__user_id_312f1f_idx"),
                    models.Index(fields=["alert_type", "-triggered_at"], name="monitoring__alert_t_5b8ad9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChurnRiskReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField(db_index=True)),
                ("churn_risk_score", models.FloatField(help_text="0-100, higher = more likely to churn")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("days_since_last_activity", models.IntegerField(default=0)),
                ("login_count_7d", models.IntegerField(default=0)),
                ("login_trend", models.FloatField(default=0, help_text="Percentage change vs previous 7 days")),
                ("assignments_completed_7d", models.IntegerField(default=0)),
                ("assignment_trend", models.FloatField(default=0, help_text="Percentage change vs previous 7 days")),
                ("avg_frustration_score", models.FloatField(blank=True, null=True)),
                ("avg_engagement_score", models.FloatField(blank=True, null=True)),
                ("subscription_status", models.CharField(blank=True, max_length=20, null=True)),
                ("days_until_renewal", models.IntegerField(blank=True, null=True)),
                ("has_payment_issues", models.BooleanField(default=False)),
                ("details", models.JSONField(default=dict, help_text="Detailed metrics breakdown")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_reports",
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["academy", "report_date", "risk_level"], name="monitoring__academy_bdb48a_idx"
                    ),
                    models.Index(fields=["risk_level", "report_date"], name="monitoring__risk_le_7f5fd9_idx"),
                    models.Index(fields=["-churn_risk_score"], name="monitoring__churn_r_62b355_idx"),
                    models.Index(fields=["report_date", "-churn_risk_score"], name="monitoring__report__125df1_idx"),
                ],
                "unique_together": {("user", "report_date")},
            },
        ),
    ]
