# Generated by Django 5.2 on 2026-04-28 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("authenticate", "0016_remove_githubacademyuser_copilot_granted"),
        ("marketing", "0012_make_activecampaign_optional_for_tags"),
        ("monitoring", "0004_add_churn_risk_reports"),
        ("payments", "0036_planfinancing_next_charge_pull_applied_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcquisitionReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("FORM_ENTRY", "Form entry"), ("USER_INVITE", "User invite")], max_length=20
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("report_date", models.DateField(db_index=True)),
                ("email", models.CharField(blank=True, default="", max_length=150)),
                (
                    "funnel_tier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "won_or_sale"), (2, "strong_lead"), (3, "soft_lead"), (4, "nurture_invite")],
                        db_index=True,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=70, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=70, null=True)),
                ("utm_campaign", models.CharField(blank=True, max_length=70, null=True)),
                ("utm_term", models.CharField(blank=True, max_length=50, null=True)),
                ("utm_content", models.CharField(blank=True, max_length=70, null=True)),
                ("utm_placement", models.CharField(blank=True, max_length=50, null=True)),
                ("landing_url", models.CharField(blank=True, max_length=2000, null=True)),
                ("conversion_url", models.CharField(blank=True, max_length=2000, null=True)),
                ("lead_type", models.CharField(blank=True, max_length=15, null=True)),
                ("deal_status", models.CharField(blank=True, max_length=15, null=True)),
                ("attribution_id", models.CharField(blank=True, max_length=30, null=True)),
                ("event_slug", models.SlugField(blank=True, max_length=120, null=True)),
                ("asset_slug", models.SlugField(blank=True, max_length=60, null=True)),
                ("team_seat_invite", models.BooleanField(default=False)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisition_reports",
                        to="admissions.academy",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_acquisition_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="admissions.cohort",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="marketing.course",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "plan_financing_seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="payments.planfinancingseat",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="authenticate.role",
                    ),
                ),
                (
                    "subscription_seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="payments.subscriptionseat",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to="admissions.syllabus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acquisition_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["academy", "report_date", "source_type"], name="monitoring__academy_307109_idx"
                    ),
                    models.Index(fields=["report_date", "-created_at"], name="monitoring__report__61da2d_idx"),
                    models.Index(fields=["utm_source", "report_date"], name="monitoring__utm_sou_9fbd01_idx"),
                    models.Index(fields=["asset_slug", "report_date"], name="monitoring__asset_s_6f1473_idx"),
                    models.Index(fields=["event_slug", "report_date"], name="monitoring__event_s_660864_idx"),
                    models.Index(fields=["conversion_url", "report_date"], name="monitoring__convers_1b6686_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_id"), name="monitoring_acquisition_report_source_uniq"
                    )
                ],
            },
        ),
    ]
