# Generated by Django 5.2 on 2026-04-28 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("monitoring", "0005_acquisitionreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGenerationJob",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[("acquisition", "Acquisition"), ("churn", "Churn")], db_index=True, max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("PARTIAL", "Partial"),
                            ("ERROR", "Error"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("status_message", models.TextField(blank=True, default=None, null=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("params", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("progress_current", models.PositiveIntegerField(default=0)),
                ("progress_total", models.PositiveIntegerField(default=0)),
                ("generated_rows", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_log", models.TextField(blank=True, default=None, null=True)),
                ("celery_task_id", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_generation_jobs",
                        to="admissions.academy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_report_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["academy", "report_type", "-created_at"], name="monitoring__academy_e8af23_idx"
                    ),
                    models.Index(fields=["status", "-created_at"], name="monitoring__status_fdec1b_idx"),
                    models.Index(fields=["fingerprint", "status"], name="monitoring__fingerp_a34f2b_idx"),
                ],
            },
        ),
    ]
