# Generated by Django 5.2 — index names from 0007 exceeded 30 chars; align with auto names.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0009_acquisitionreport_form_entry_won"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportgenerationjob",
            new_name="monitoring__parent__832e87_idx",
            old_name="monitoring__parent_i_7c8a1e_idx",
        ),
        migrations.RenameIndex(
            model_name="reportgenerationjob",
            new_name="monitoring__batch_i_dceefc_idx",
            old_name="monitoring__batch_i_d4e2b1_idx",
        ),
    ]
