# Generated by Django 3.1.6 on 2021-03-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0009_auto_20210225_0142"),
        ("monitoring", "0009_auto_20210220_1651"),
    ]

    operations = []
