# Generated by Django 3.2.7 on 2021-09-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0012_auto_20210312_0618"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorscript",
            name="notify_email",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Only specify if need to override the application.notify_email, you can add many comma separated.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="notify_email",
            field=models.CharField(
                blank=True, default=None, help_text="Comma separated list of emails", max_length=255, null=True
            ),
        ),
    ]
