# Generated by Django 3.2.12 on 2022-03-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0031_academy_icon_url"),
        ("monitoring", "0013_auto_20210923_0305"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVDownload",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[("LOADING", "Loading"), ("ERROR", "Error"), ("DONE", "Done")],
                        default="LOADING",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
    ]
