# Generated by Django 5.0.3 on 2024-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0019_repositorysubscription_hook_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorysubscription",
            name="status",
            field=models.CharField(
                choices=[("OPERATIONAL", "Operational"), ("CRITICAL", "Critical"), ("DISABLED", "Disabled")],
                default="CRITICAL",
                max_length=20,
            ),
        ),
    ]
