# Generated by Django 3.0.7 on 2020-07-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_auto_20200708_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='github_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
