# Generated by Django 3.1 on 2020-08-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_auto_20200807_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='github_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
