# Generated by Django 3.1.4 on 2020-12-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_auto_20201209_0216'),
        ('coursework', '0006_auto_20201218_1137'),
    ]

    operations = [
    ]
