# Generated by Django 5.2 on 2025-08-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_initial"),
        ("marketing", "0004_alter_coursetranslation_prerequisite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="course",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="marketing.course"
            ),
        ),
    ]
