# Generated by Django 5.2 on 2025-09-08 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0003_userinvite_course"),
        ("payments", "0010_subscriptionseatinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="team_member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Related team membership for team invitations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.billingteammembership",
            ),
        ),
    ]
