# Generated by Django 5.2 on 2025-08-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0003_userinvite_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialsgoogle",
            name="google_id",
            field=models.CharField(default="", max_length=34),
        ),
        migrations.AlterField(
            model_name="credentialsgoogle",
            name="refresh_token",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="credentialsgoogle",
            name="token",
            field=models.CharField(max_length=500),
        ),
    ]
