# Generated by Django 5.2 on 2025-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0004_credentialsdiscord"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialsdiscord",
            name="joined_servers_id",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
