# Generated by Django 5.2 on 2025-09-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0004_userinvite_team_member"),
        ("payments", "0018_delete_subscriptionseatinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvite",
            name="team_member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Related team membership for team invitations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionseat",
            ),
        ),
    ]
