# Generated by Django 5.2 on 2025-09-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0004_alter_credentialsgoogle_google_id_and_more"),
        ("payments", "0009_bag_seat_service_item_plan_consumption_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="subscription_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Related subscription seat for team invitations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionseat",
            ),
        ),
    ]
