# Generated by Django 5.2 on 2025-08-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0005_credentialsdiscord_joined_servers_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credentialsdiscord",
            old_name="joined_servers_id",
            new_name="joined_servers",
        ),
    ]
