# Generated by Django 5.2 on 2025-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0006_rename_joined_servers_id_credentialsdiscord_joined_servers"),
    ]

    operations = [
        migrations.AddField(
            model_name="academyauthsettings",
            name="discord_settings",
            field=models.JSONField(blank=True, default=None, help_text="Discord variables for this academy", null=True),
        ),
    ]
