# Generated by Django 5.2 on 2025-11-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0006_academyauthsettings_discord_settings_and_more"),
        ("payments", "0020_rename_pos_api_key_academypaymentsettings_stripe_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="plan_financing_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Related plan financing seat for team invitations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.planfinancingseat",
            ),
        ),
    ]
