# Generated by Django 5.2 on 2025-12-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0007_userinvite_plan_financing_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="clicked_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userinvite",
            name="opened_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
