# Generated by Django 5.2 on 2025-12-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0008_add_opened_at_clicked_at_to_user_invite"),
        ("payments", "0028_alter_invoice_status_creditnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Payment method to use when creating the invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
            ),
        ),
    ]
