# Generated by Django 3.1.1 on 2020-10-06 00:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authenticate", "0008_auto_20201005_2253"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("user", "key")},
        ),
    ]
