# Generated by Django 5.2 on 2025-12-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0009_userinvite_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="welcome_video",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Video de bienvenida con preview_image y url. Formato: {'preview_image': 'url', 'url': 'url'}",
                null=True,
            ),
        ),
    ]
