# Generated by Django 3.1.2 on 2020-10-29 06:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authenticate', '0010_credentialsslack_slackteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAutentication',
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='credentialsslack',
            name='authed_user',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
