# Generated by Django 5.2 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0010_userinvite_welcome_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academyauthsettings",
            name="learnpack_owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who owns the LearnPack integration for this academy. Must have FirstPartyCredentials with rigobot id.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learnpack_academy_auth_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academyauthsettings",
            name="learnpack_features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON configuration for LearnPack features. Structure to be defined later.",
            ),
        ),
        migrations.AddField(
            model_name="academyauthsettings",
            name="learnpack_org_id",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="LearnPack organization ID for this academy.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academyauthsettings",
            name="learnpack_org_slug",
            field=models.SlugField(
                blank=True,
                help_text="LearnPack organization slug for this academy.",
                max_length=200,
            ),
        ),
    ]

