# Generated by Django 5.2 on 2025-12-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0011_add_learnpack_fields_to_academy_auth_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academyauthsettings",
            name="learnpack_org_slug",
        ),
    ]
