# Generated by Django 5.2 on 2026-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0012_remove_academyauthsettings_learnpack_org_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileacademy",
            name="status",
            field=models.CharField(
                choices=[("INVITED", "Invited"), ("ACTIVE", "Active"), ("DELETED", "Deleted")],
                db_index=True,
                default="INVITED",
                max_length=15,
            ),
        ),
    ]
