# Generated by Django 5.2 on 2026-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0012_remove_academyauthsettings_learnpack_org_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="how_many_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many times we've attempted to deliver the invite email for this UserInvite. This counter is used by the invite-resend cronjob to decide when to retry. 0 means 'unknown/legacy' (created before tracking) or 'not sent yet'.",
            ),
        ),
    ]
