# Generated by Django 5.2 on 2026-03-06 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("authenticate", "0013_alter_profileacademy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for native (platform) roles; set for academy-owned custom roles.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_roles",
                to="admissions.academy",
            ),
        ),
    ]
