# Generated by Django 3.1.4 on 2021-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0017_auto_20210113_0644"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialsgithub",
            name="username",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
