# Generated by Django 3.1.6 on 2021-02-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0019_auto_20210121_2142"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
