# Generated by Django 3.2.7 on 2021-09-20 14:39
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0023_auto_20210812_2153"),
        ("authenticate", "0022_credentialsgoogle"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admissions.academy",),
        ),
    ]
