# Generated by Django 3.2.19 on 2023-05-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0037_auto_20230509_0801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="User biography in user's language. Will be used if there are no ProfileTranslations.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profiletranslation",
            name="bio",
            field=models.CharField(max_length=255),
        ),
    ]
