# Generated by Django 3.2.19 on 2023-07-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0041_auto_20230725_0322'),
        ('authenticate', '0041_auto_20230725_0619'),
    ]

    operations = []
