# Generated by Django 3.2.19 on 2023-07-28 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0041_auto_20230725_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=25, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('algorithm',
                 models.CharField(choices=[('HMAC_SHA256', 'HMAC-SHA256'), ('HMAC_SHA512', 'HMAC_SHA512'),
                                           ('ED25519', 'ED25519')],
                                  max_length=11)),
                ('strategy',
                 models.CharField(choices=[('JWT', 'Json Web Token'), ('SIGNATURE', 'Signature')],
                                  max_length=9)),
                ('schema', models.CharField(choices=[('LINK', 'Link')], max_length=4)),
                ('agreement_version',
                 models.IntegerField(default=1, help_text='Version of the agreement, based in the scopes')),
                ('private_key', models.CharField(blank=True, max_length=255)),
                ('public_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('require_an_agreement',
                 models.BooleanField(default=True,
                                     help_text='If true, the user will be required to accept an agreement')),
                ('webhook_url', models.URLField()),
                ('redirect_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=25, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalScopeSet',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_scopes', models.ManyToManyField(blank=True, to='authenticate.Scope')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyKey',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm',
                 models.CharField(choices=[('HMAC_SHA256', 'HMAC-SHA256'), ('HMAC_SHA512', 'HMAC_SHA512'),
                                           ('ED25519', 'ED25519')],
                                  max_length=11)),
                ('strategy',
                 models.CharField(choices=[('JWT', 'Json Web Token'), ('SIGNATURE', 'Signature')],
                                  max_length=9)),
                ('schema', models.CharField(choices=[('LINK', 'Link')], max_length=4)),
                ('private_key', models.CharField(blank=True, max_length=255)),
                ('public_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('webhook_url', models.URLField()),
                ('redirect_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                      related_name='legacy_key',
                                      to='authenticate.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppUserAgreement',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_version',
                 models.IntegerField(default=1, help_text='Version of the agreement that was accepted')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                          to='authenticate.app')),
                ('optional_scope_set',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='app_user_agreement',
                                   to='authenticate.optionalscopeset')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='optional_scopes',
            field=models.ManyToManyField(blank=True,
                                         related_name='app_optional_scopes',
                                         to='authenticate.Scope'),
        ),
        migrations.AddField(
            model_name='app',
            name='required_scopes',
            field=models.ManyToManyField(blank=True,
                                         related_name='app_required_scopes',
                                         to='authenticate.Scope'),
        ),
    ]
