# Generated by Django 3.2.20 on 2023-08-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0042_auto_20230801_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
