# Generated by Django 3.2.20 on 2023-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0042_auto_20230805_0323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appoptionalscope",
            name="agreed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="apprequiredscope",
            name="agreed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
