# Generated by Django 3.2.20 on 2023-08-15 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_event_slug'),
        ('registry', '0031_alter_asset_status'),
        ('authenticate', '0042_auto_20230805_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='asset',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='If set, the user signed up because of an Asset',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='registry.asset'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='conversion_info',
            field=models.JSONField(blank=True,
                                   default=None,
                                   help_text='UTMs and other conversion information.',
                                   null=True),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='event',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='If set, the user signed up because of an Event',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='events.event'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='has_marketing_consent',
            field=models.BooleanField(default=False),
        ),
    ]
