# Generated by Django 3.2.20 on 2023-08-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0043_alter_scope_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
