# Generated by Django 3.2.20 on 2023-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0044_alter_scope_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalscopeset',
            name='agreement_version',
            field=models.IntegerField(default=1),
        ),
    ]
