# Generated by Django 3.2.20 on 2023-08-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0045_optionalscopeset_agreement_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalscopeset',
            name='agreement_version',
        ),
    ]
