# Generated by Django 5.0.1 on 2024-02-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0048_auto_20231128_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPartyCredentials',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigobot_id', models.IntegerField(blank=True, default=None, null=True)),
                ('health_status',
                 models.JSONField(blank=True, default={}, help_text='Health status of each credentials')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                      related_name='credentials',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstPartyWebhookLog',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.CharField(blank=True,
                                  default='unknown',
                                  help_text='Type of the webhook',
                                  max_length=50)),
                ('user_id',
                 models.IntegerField(blank=True,
                                     default=None,
                                     help_text='User ID who triggered the webhook',
                                     null=True)),
                ('external_id',
                 models.IntegerField(blank=True,
                                     default=None,
                                     help_text='External ID where the webhook was triggered',
                                     null=True)),
                ('url',
                 models.URLField(blank=True, default=None, help_text='URL to consult the content',
                                 null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Data received', null=True)),
                ('processed',
                 models.BooleanField(blank=True,
                                     default=False,
                                     help_text='If true, the webhook has been processed')),
                ('attempts',
                 models.IntegerField(blank=True,
                                     default=0,
                                     help_text='Number of attempts to process the webhook')),
                ('status',
                 models.CharField(blank=True,
                                  choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('ERROR', 'Error')],
                                  default='PENDING',
                                  max_length=9)),
                ('status_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app',
                 models.ForeignKey(help_text='App that triggered or will receive the webhook',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='authenticate.app')),
            ],
        ),
    ]
