# Generated by Django 5.0.3 on 2024-03-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0049_firstpartycredentials_firstpartywebhooklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='optional_scopes',
        ),
        migrations.RemoveField(
            model_name='app',
            name='required_scopes',
        ),
        migrations.RemoveField(
            model_name='appuseragreement',
            name='app',
        ),
        migrations.RemoveField(
            model_name='apprequiredscope',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appoptionalscope',
            name='app',
        ),
        migrations.RemoveField(
            model_name='firstpartywebhooklog',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appoptionalscope',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='apprequiredscope',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='appuseragreement',
            name='optional_scope_set',
        ),
        migrations.RemoveField(
            model_name='appuseragreement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='firstpartycredentials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='optionalscopeset',
            name='optional_scopes',
        ),
        migrations.DeleteModel(name='LegacyKey', ),
        migrations.DeleteModel(name='App', ),
        migrations.DeleteModel(name='FirstPartyWebhookLog', ),
        migrations.DeleteModel(name='AppOptionalScope', ),
        migrations.DeleteModel(name='AppRequiredScope', ),
        migrations.DeleteModel(name='AppUserAgreement', ),
        migrations.DeleteModel(name='FirstPartyCredentials', ),
        migrations.DeleteModel(name='OptionalScopeSet', ),
        migrations.DeleteModel(name='Scope', ),
    ]
