# Generated by Django 5.0.3 on 2024-03-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0050_remove_app_optional_scopes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyKey",
        ),
    ]
