# Generated by Django 5.0.7 on 2024-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0054_academyauthsettings_auto_sync_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio_url",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
