# Generated by Django 5.1.2 on 2024-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0060_alter_googlewebhook_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlewebhook",
            name="type",
            field=models.CharField(default="noSet", max_length=40),
        ),
    ]
