# Generated by Django 5.1.4 on 2024-12-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0061_googlewebhook_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="App",
        ),
    ]
