# Generated by Django 5.1.6 on 2025-02-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0063_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotFoundAnonGoogleUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("id_token", models.CharField(default="", max_length=1152)),
                ("google_id", models.CharField(default="", max_length=24)),
                ("expires_at", models.DateTimeField()),
                ("email", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
