# Generated by Django 5.1.6 on 2025-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0064_notfoundanongoogleuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialsgoogle",
            name="id_token",
            field=models.CharField(default="", max_length=1400),
        ),
    ]
