# Generated by Django 5.1.6 on 2025-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0065_alter_credentialsgoogle_id_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialsgithub",
            name="scopes",
            field=models.CharField(default="", max_length=64),
        ),
    ]
