# Generated by Django 3.0.7 on 2020-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_auto_20200703_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="logo",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
