# Generated by Django 3.0.7 on 2020-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_auto_20200703_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="week_hours",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
