# Generated by Django 3.1.3 on 2020-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0011_auto_20201006_0058"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="timezone",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cohort",
            name="timezone",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
