# Generated by Django 3.1.7 on 2021-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_cohort_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="never_ends",
            field=models.BooleanField(default=False),
        ),
    ]
