# Generated by Django 3.2.7 on 2021-10-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0023_auto_20210812_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="feedback_email",
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
