# Generated by Django 3.2.8 on 2021-10-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0024_academy_feedback_email"),
        ("admissions", "0024_auto_20211016_0015"),
    ]

    operations = []
