# Generated by Django 3.2.12 on 2022-03-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0031_academy_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialtymodetimeslot",
            name="academy",
        ),
        migrations.AddField(
            model_name="specialtymode",
            name="academy",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"
            ),
        ),
        migrations.DeleteModel(
            name="AcademySpecialtyMode",
        ),
    ]
