# Generated by Django 3.2.15 on 2022-09-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0046_academy_available_as_saas"),
        ("admissions", "0046_auto_20220920_1117"),
    ]

    operations = []
