# Generated by Django 3.2.16 on 2023-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0051_auto_20230117_2219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="kickoff_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
