# Generated by Django 3.2.16 on 2023-01-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0052_alter_cohort_kickoff_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="kickoff_date",
            field=models.DateTimeField(),
        ),
    ]
