# Generated by Django 5.1.2 on 2024-11-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0064_academy_legal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="cohorts_order",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="An IDs comma separated list to indicate the order in which the micro cohorts will be displayed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="micro_cohorts",
            field=models.ManyToManyField(
                blank=True,
                help_text="This cohorts will represent small courses inside a main course",
                related_name="cohorts",
                to="admissions.cohort",
            ),
        ),
    ]
