# Generated by Django 3.2.19 on 2023-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0008_auto_20230715_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioninguserconsumption",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
