# Generated by Django 3.2.19 on 2023-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0011_auto_20230718_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningbill",
            name="title",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="This title should describe what the Bill is about. I.e.: April's bill.",
                max_length=40,
                null=True,
            ),
        ),
    ]
