# Generated by Django 5.2 on 2025-05-16 04:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admissions.cohort",),
        ),
        migrations.CreateModel(
            name="UserProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LayoutDesign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=40)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Will be used as default for all future certificates. Only one default layout per academy.",
                    ),
                ),
                ("html_content", models.TextField(blank=True, default=None, null=True)),
                ("css_content", models.TextField(blank=True, default=None, null=True)),
                ("preview_url", models.CharField(default=None, max_length=250, null=True)),
                ("background_url", models.CharField(max_length=250)),
                ("foot_note", models.CharField(default=None, max_length=250, null=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("logo_url", models.CharField(blank=True, default=None, max_length=250, null=True)),
                ("duration_in_hours", models.IntegerField(blank=True, default=None, null=True)),
                ("description", models.TextField(blank=True, default=None, max_length=500, null=True)),
                ("expiration_day_delta", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "syllabus",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="This specialty represents only one certificate",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialty_with_one_syllabus",
                        to="admissions.syllabus",
                    ),
                ),
                (
                    "syllabuses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="This specialty can have multiple syllabi",
                        related_name="specialties_with_many_syllabus",
                        to="admissions.syllabus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("logo_url", models.CharField(blank=True, default=None, max_length=250, null=True)),
                ("duration_in_hours", models.IntegerField()),
                ("expiration_day_delta", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("specialties", models.ManyToManyField(to="certificate.specialty")),
            ],
        ),
        migrations.CreateModel(
            name="UserSpecialty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status_text", models.CharField(blank=True, default=None, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PERSISTED", "Persisted"), ("ERROR", "Error")],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=40, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("signed_by", models.CharField(max_length=100)),
                ("signed_by_role", models.CharField(default="Director", max_length=100)),
                ("issued_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("update_hash", models.CharField(blank=True, max_length=40, null=True)),
                ("preview_url", models.CharField(blank=True, default=None, max_length=250, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificate.layoutdesign",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="certificate.specialty"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
