# Generated by Django 5.2 on 2025-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="metrics",
            field=models.JSONField(blank=True, default=dict, help_text="Key performance metrics for this specialty"),
        ),
    ]
