# Generated by Django 5.2 on 2025-10-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0002_specialty_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive"), ("DELETED", "Deleted")],
                default="ACTIVE",
                help_text="Current status of the specialty",
                max_length=15,
            ),
        ),
    ]
