# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0003_specialty_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialties",
                to="admissions.academy",
            ),
        ),
    ]
