# Generated by Django 3.1 on 2020-09-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0008_auto_20200708_0049"),
        ("certificate", "0003_userspecialty_signed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspecialty",
            name="cohort",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"
            ),
        ),
    ]
