# Generated by Django 3.1.1 on 2020-10-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0005_auto_20200929_1916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userspecialty",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="certificate.layoutdesign",
            ),
        ),
    ]
