# Generated by Django 3.2.12 on 2022-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0015_userspecialty_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspecialty",
            name="update_hash",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
