# Generated by Django 5.1.6 on 2025-03-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("certificate", "0017_layoutdesign_foot_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="syllabus_many",
            field=models.ManyToManyField(blank=True, related_name="specialties", to="admissions.syllabus"),
        ),
    ]
