# Generated by Django 5.1.7 on 2025-03-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("certificate", "0017_layoutdesign_foot_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="syllabus",
        ),
        migrations.AddField(
            model_name="specialty",
            name="syllabus",
            field=models.ManyToManyField(
                blank=True, help_text="This specialty can have multiple certificates", to="admissions.syllabus"
            ),
        ),
    ]
