# Generated by Django 5.1.7 on 2025-03-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("certificate", "0018_remove_specialty_syllabus_specialty_syllabus"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialties",
                to="admissions.academy",
            ),
        ),
    ]
