# Generated by Django 5.1.7 on 2025-03-24 23:42
from django.db import migrations


def migrate_syllabus_data(apps, schema_editor):
    Specialty = apps.get_model("certificate", "Specialty")
    ThroughModel = Specialty._meta.get_field("syllabus").remote_field.through

    to_create = []
    for specialty in Specialty.objects.all():
        for syllabus in specialty.syllabus.all():
            to_create.append(ThroughModel(specialty_id=specialty.id, syllabus_id=syllabus.id))

    if to_create:
        ThroughModel.objects.bulk_create(to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0018_remove_specialty_syllabus_specialty_syllabus"),
    ]

    operations = [
        migrations.RunPython(migrate_syllabus_data),
    ]
