# Generated by Django 5.1.7 on 2025-03-25 20:12

from django.db import migrations


def migrate_syllabus_to_syllabuses(apps, schema_editor):
    Specialty = apps.get_model("certificate", "Specialty")

    for specialty in Specialty.objects.all():
        if specialty.syllabus:
            specialty.syllabuses.add(specialty.syllabus)


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0018_specialty_syllabuses_alter_specialty_syllabus"),
    ]

    operations = [
        migrations.RunPython(migrate_syllabus_to_syllabuses),
    ]
