# Generated by Django 5.1.7 on 2025-03-24 21:58

from django.db import migrations


def migrate_syllabus_data(apps, schema_editor):
    Specialty = apps.get_model("certificate", "Specialty")
    Syllabus = apps.get_model("admissions", "Syllabus")

    for specialty in Specialty.objects.all():
        if hasattr(specialty, "syllabus_old") and specialty.syllabus_old:
            syllabus_instance = Syllabus.objects.filter(id=specialty.syllabus_old.id).first()
            if syllabus_instance:
                specialty.syllabus.add(syllabus_instance)
                specialty.save()


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0018_remove_specialty_syllabus_specialty_syllabus"),
    ]

    operations = [
        migrations.RunPython(migrate_syllabus_data),
    ]
