# Generated by Django 5.1.6 on 2025-03-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0019_auto_20250313_2042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="syllabus",
        ),
    ]
