# Generated by Django 5.1.6 on 2025-03-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0020_remove_specialty_syllabus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialty",
            old_name="syllabus_many",
            new_name="syllabus_list",
        ),
    ]
