# Generated by Django 5.2 on 2025-05-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        ("mentorship", "0001_initial"),
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportchannel",
            name="slack_channel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notify.slackchannel",
            ),
        ),
        migrations.AddField(
            model_name="supportchannel",
            name="syllabis",
            field=models.ManyToManyField(related_name="support_channels", to="admissions.syllabus"),
        ),
        migrations.AddField(
            model_name="supportagent",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="mentorship.supportchannel",
            ),
        ),
    ]
