# Generated by Django 3.2.7 on 2021-11-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_merge_20211018_2259'),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='syllabus',
            field=models.ManyToManyField(blank=True,
                                         default=None,
                                         help_text='What syllabis is this mentor going to be menting to?',
                                         null=True,
                                         to='admissions.Syllabus'),
        ),
    ]
