# Generated by Django 3.2.7 on 2021-11-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentorprofile_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='email',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Only use this if the user does not exist on breathecode already',
                max_length=150,
                null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
