# Generated by Django 3.2.12 on 2022-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0011_auto_20220402_0003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorshipsession",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
