# Generated by Django 3.2.13 on 2022-07-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0013_auto_20220408_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='service',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='services',
            field=models.ManyToManyField(to='mentorship.MentorshipService'),
        ),
    ]
