# Generated by Django 3.2.14 on 2022-07-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0041_cohortuser_watching'),
        ('mentorship', '0014_auto_20220707_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='academy',
            field=models.ForeignKey(default=None,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='admissions.academy'),
        ),
    ]
