# Generated by Django 3.2.14 on 2022-07-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0015_mentorprofile_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='service',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='mentorship.mentorshipservice'),
        ),
    ]
