# Generated by Django 3.2.18 on 2023-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0021_calendlyorganization_calendlywebhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="calendly_uuid",
            field=models.CharField(
                blank=True, default=None, help_text="To be used by the calendly API", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="calendly_uuid",
            field=models.CharField(
                blank=True, default=None, help_text="To be used by the calendly API", max_length=150, null=True
            ),
        ),
    ]
