# Generated by Django 5.0.6 on 2024-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0029_mentorshipservice_video_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorshipservice",
            name="video_provider",
            field=models.CharField(
                blank=True, choices=[("DAILY", "Daily"), ("GOOGLE_MEET", "Google Meet")], default=None, max_length=15
            ),
        ),
    ]
