# Generated by Django 3.1.3 on 2020-11-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0012_auto_20201110_0727"),
        ("notify", "0006_auto_20201111_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackteam",
            name="credentials",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authenticate.credentialsslack",
            ),
        ),
    ]
