# Generated by Django 5.1.1 on 2024-09-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0064_academy_legal_name"),
        ("notify", "0012_hookerror"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_code", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True, default=None, null=True)),
                ("meta", models.JSONField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done"), ("SENT", "Sent"), ("SEEN", "Seen")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("sent_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("seen_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
