# Generated by Django 5.2 on 2025-05-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0002_initial"),
        ("authenticate", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyFreelanceProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("repository", models.URLField(help_text="Github repo where the event occured", max_length=255)),
                (
                    "total_client_hourly_price",
                    models.FloatField(help_text="How much will the client be billed for each our on this project"),
                ),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_per_hour", models.FloatField()),
                (
                    "github_user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="authenticate.credentialsgithub",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="FreelanceProjectMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "total_cost_hourly_price",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Paid to the freelancer, leave blank to use the default freelancer price",
                        null=True,
                    ),
                ),
                (
                    "total_client_hourly_price",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Billed to the client on this project/freelancer, leave blank to use default from the project",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="freelance.academyfreelanceproject"
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="freelance.freelancer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("DUE", "Due"), ("APPROVED", "Approved"), ("IGNORED", "Ignored"), ("PAID", "Paid")],
                        default="DUE",
                        max_length=20,
                    ),
                ),
                ("total_duration_in_minutes", models.FloatField(default=0)),
                ("total_duration_in_hours", models.FloatField(default=0)),
                ("total_price", models.FloatField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Will help catalog billing grouped by academy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="freelance.freelancer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInvoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("DUE", "Due"), ("APPROVED", "Approved"), ("IGNORED", "Ignored"), ("PAID", "Paid")],
                        default="DUE",
                        max_length=20,
                    ),
                ),
                ("total_duration_in_minutes", models.FloatField(default=0)),
                ("total_duration_in_hours", models.FloatField(default=0)),
                ("total_price", models.FloatField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="freelance.academyfreelanceproject"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "node_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="This is the only unique identifier we get from github, the issue number is not unique among repos",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IGNORED", "Ignored"),
                            ("DRAFT", "Draft"),
                            ("TODO", "Todo"),
                            ("DOING", "Doing"),
                            ("DONE", "Done"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Important message like reason why not included on bill, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("github_state", models.CharField(blank=True, default=None, max_length=30, null=True)),
                ("github_number", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("body", models.TextField(max_length=500)),
                ("duration_in_minutes", models.FloatField(default=0)),
                ("duration_in_hours", models.FloatField(default=0)),
                ("url", models.URLField()),
                ("repository_url", models.URLField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Will help catalog billing grouped by academy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="freelance.bill",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="freelance.freelancer"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Attach this issue to a project invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="freelance.projectinvoice",
                    ),
                ),
            ],
        ),
    ]
