# Generated by Django 3.0.8 on 2020-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0003_auto_20200717_2009"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="duration_in_hours",
            field=models.FloatField(default=0),
        ),
    ]
