# Generated by Django 3.2.9 on 2022-02-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0010_repositoryissuewebhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="node_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="This is the only unique identifier we get from github, the issue number its not unique among repos",
                max_length=50,
                null=True,
            ),
        ),
    ]
