# Generated by Django 3.2.15 on 2022-09-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0016_academyfreelanceproject_freelanceprojectmember_projectinvoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academyfreelanceproject",
            old_name="total_client_price",
            new_name="total_client_hourly_price",
        ),
        migrations.RemoveField(
            model_name="freelanceprojectmember",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="freelanceprojectmember",
            name="title",
        ),
    ]
