# Generated by Django 3.2.15 on 2022-09-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0018_auto_20220919_2338"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Attach this freelance bill to a project invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="freelance.projectinvoice",
            ),
        ),
    ]
