# Generated by Django 3.2.15 on 2022-09-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0020_auto_20220920_0038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectinvoice",
            name="freelancer",
        ),
        migrations.AlterField(
            model_name="projectinvoice",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="freelance.academyfreelanceproject"
            ),
        ),
    ]
