# Generated by Django 5.2 on 2025-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendar_event_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Google Calendar event id linked to this event (created when the event meeting url was automatically created)",
                max_length=128,
                null=True,
            ),
        ),
    ]
