# Generated by Django 5.2 on 2025-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_calendar_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("DRAFT", "Draft"),
                    ("DELETED", "Deleted"),
                    ("SUSPENDED", "Suspended"),
                    ("FINISHED", "Finished"),
                ],
                default="DRAFT",
                max_length=9,
            ),
        ),
    ]
