# Generated by Django 5.2 on 2025-12-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="is_holiday",
            field=models.BooleanField(
                default=False,
                help_text="We keep the class on recording even if it's a holiday, to avoid the timeslot and live class being re-added into the calendar)",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="is_skipped",
            field=models.BooleanField(
                default=False,
                help_text="Some classes are skipped, like the ones that are before the kickoff date, on holidays or after the ending date",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="skipped_reason",
            field=models.CharField(
                blank=True, default=None, help_text="Reason for skipping the class", max_length=255, null=True
            ),
        ),
    ]
