# Generated by Django 5.2 on 2025-12-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("events", "0004_liveclass_is_holiday_liveclass_is_skipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="cohort",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"
            ),
        ),
        migrations.AlterField(
            model_name="liveclass",
            name="cohort_time_slot",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohorttimeslot"
            ),
        ),
        migrations.AlterField(
            model_name="liveclass",
            name="remote_meeting_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
