# Generated by Django 5.2 on 2026-01-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("events", "0005_make_liveclass_fields_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyEventSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_meeting_provider",
                    models.CharField(
                        choices=[("daily", "Daily"), ("livekit", "Livekit")],
                        default="daily",
                        help_text="Default provider used when creating meeting rooms for events if meeting_provider is not provided.",
                        max_length=20,
                    ),
                ),
                (
                    "daily_api_key",
                    models.CharField(blank=True, default=None, help_text="Daily API key", max_length=255, null=True),
                ),
                (
                    "livekit_http_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="HTTP URL of the LiveKit server to make requests from the API",
                        null=True,
                    ),
                ),
                (
                    "livekit_api_key",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="API key to authenticate requests to the LiveKit server",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "livekit_api_secret",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="API secret to sign tokens for requests to the LiveKit server",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "livekit_url",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="URL of the LiveKit server for the WebSockets connection from the client",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
    ]
