# Generated by Django 5.2 on 2026-05-28 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_academyeventsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="luma_id",
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="luma_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="luma_guest_id",
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="luma_calendar_id",
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="luma_webhook_secret",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LumaWebhook",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(blank=True, default=None, max_length=40, null=True)),
                ("webhook_id", models.CharField(blank=True, default=None, max_length=80, null=True)),
                ("luma_guest_id", models.CharField(blank=True, default=None, max_length=80, null=True)),
                ("payload", models.JSONField(blank=True, default=None, null=True)),
                ("organization_id", models.CharField(blank=True, default=None, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done"), ("ERROR", "Error")],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                ("status_text", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
