# Generated by Django 5.2 on 2026-06-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_luma_webhooks"),
        ("events", "0008_eventcheckin_phone"),
    ]

    operations = []
