# Generated by Django 3.1.4 on 2021-01-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_auto_20210113_1940"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbritewebhook",
            name="organization_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
