# Generated by Django 3.2.9 on 2021-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eventcheckin_attended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventbrite_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='eventbrite_sync_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventbrite_sync_status',
            field=models.CharField(blank=True,
                                   choices=[('PENDING', 'Pending'), ('ERROR', 'Error'),
                                            ('WARNING', 'Warning'), ('SYNCHED', 'Synched')],
                                   default='PENDING',
                                   max_length=7),
        ),
    ]
