# Generated by Django 3.2.9 on 2021-11-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_auto_20211129_1758"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="sync_status",
            new_name="eventbrite_sync_status",
        ),
    ]
