# Generated by Django 3.2.9 on 2022-01-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_alter_event_host"),
        ("events", "0030_auto_20220111_0518"),
    ]

    operations = []
