# Generated by Django 3.2.16 on 2023-01-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0036_auto_20221227_2039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="visibility_settings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Visibility has to be configured every academy separately",
                to="events.EventTypeVisibilitySetting",
            ),
        ),
    ]
