# Generated by Django 3.2.16 on 2023-02-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_liveclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
