# Generated by Django 3.2.16 on 2023-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_eventtype_icon_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="icon_url",
            field=models.URLField(default=None, null=True),
        ),
    ]
