# Generated by Django 3.2.19 on 2023-05-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0043_auto_20230509_0801"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="free_for_bootcamps",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="free_for_bootcamps",
            field=models.BooleanField(default=True),
        ),
    ]
