# Generated by Django 3.2.18 on 2023-06-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_alter_event_status"),
        ("events", "0047_auto_20230606_2328"),
    ]

    operations = []
