# Generated by Django 3.2.20 on 2023-09-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_event_slug'),
        ('events', '0053_alter_event_uuid'),
    ]

    operations = []
