# Generated by Django 3.2.20 on 2023-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_merge_0051_alter_event_slug_0053_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
