# Generated by Django 3.2.22 on 2023-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20231017_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_asset',
            field=models.SlugField(
                blank=True,
                default=None,
                help_text=
                'Is the event is about a project, this field will have the asset slug of that project.',
                max_length=200,
                null=True),
        ),
    ]
