# Generated by Django 5.1.2 on 2024-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0059_event_asset_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="technologies",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Add comma-separated list of technologies",
                max_length=200,
                null=True,
            ),
        ),
    ]
