# Generated by Django 5.1.2 on 2024-11-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0060_eventtype_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If true, then it will be shown in cards and the workshop's landing page. Otherwise it will be hidden.",
            ),
        ),
    ]
