# Generated by Django 5.1.7 on 2025-03-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0062_event_recording_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recap",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="This field will be filled automatically using AI after the event finishes.",
                null=True,
            ),
        ),
    ]
