# Generated by Django 5.1.7 on 2025-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0063_event_recap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="recap",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="This field will be filled automatically using AI after the event finishes.",
                max_length=850,
                null=True,
            ),
        ),
    ]
