# Generated by Django 5.1.7 on 2025-04-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0064_alter_event_recap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="recap",
        ),
        migrations.CreateModel(
            name="EventContext",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recap",
                    models.TextField(
                        blank=True,
                        help_text="This field will be filled automatically using AI after the event finishes.",
                        max_length=850,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("ERROR", "Error")],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                (
                    "status_text",
                    models.CharField(blank=True, help_text="Fill if error happened in the task", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="context", to="events.event"
                    ),
                ),
            ],
        ),
    ]
