# Generated by Django 5.1.7 on 2025-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0065_remove_event_recap_eventcontext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcontext",
            name="recap",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This field will be filled automatically using AI after the event finishes.",
                max_length=850,
            ),
        ),
    ]
