# Generated by Django 3.0.8 on 2020-08-06 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20200806_0035"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
