# Generated by Django 3.1.2 on 2020-10-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_auto_20201012_1548"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
    ]
