# Generated by Django 3.1.2 on 2020-10-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_organizer_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="description",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
