# Generated by Django 3.2.9 on 2021-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_rename_sync_desc_event_eventbrite_sync_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("USD", "USD"), ("CRC", "CRC"), ("CLP", "CLP"), ("EUR", "EUR"), ("UYU", "UYU")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
