# Generated by Django 3.2.9 on 2022-01-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_event_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
