# Generated by Django 3.2.9 on 2022-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_event_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
