# Generated by Django 3.2.20 on 2023-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0052_event_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
