# Generated by Django 3.2.20 on 2023-08-28 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0053_alter_event_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
