# Generated by Django 3.2.21 on 2023-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0054_alter_event_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcheckin",
            name="utm_campaign",
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="utm_medium",
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="utm_source",
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="utm_url",
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
