# Generated by Django 3.2.22 on 2023-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0056_auto_20231017_0605"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="free_for_all",
            field=models.BooleanField(
                default=False, help_text="Determines if any user (From bootcamp or not) can join the event for free."
            ),
        ),
    ]
