# Generated by Django 5.1.4 on 2025-01-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0061_event_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recording_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="This will be the URL of the workshop's recording, added once it's finished",
                max_length=255,
                null=True,
            ),
        ),
    ]
