# Generated by Django 5.2 on 2025-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="plan_by_country_code",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
