# Generated by Django 5.2 on 2025-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_course_plan_by_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="client_comments",
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
