# Generated by Django 5.2 on 2025-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_alter_formentry_client_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetranslation",
            name="prerequisite",
            field=models.TextField(
                blank=True, default=None, help_text="markdown content describing course prerequisites.", null=True
            ),
        ),
    ]
