# Generated by Django 5.2 on 2025-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_alter_coursetranslation_prerequisite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetranslation",
            name="prerequisite",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Array of markdown content describing course prerequisites.",
                null=True,
            ),
        ),
    ]
