# Generated by Django 3.0.7 on 2020-06-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_auto_20200619_0108"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="priority",
        ),
        migrations.AlterField(
            model_name="tag",
            name="acp_id",
            field=models.IntegerField(help_text="The id coming from active campaign"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[("STRONG", "Strong"), ("SOFT", "Soft"), ("DISCOVERY", "Discovery"), ("OTHER", "Other")],
                default=None,
                help_text="This will be use to determine the type of lead (strong, soft, etc.), if a lead has a tag with type=strong it will be added to the automation for strong leads",
                max_length=15,
                null=True,
            ),
        ),
    ]
