# Generated by Django 5.2 on 2025-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_alter_coursetranslation_prerequisite"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDomainValidation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(db_index=True, help_text="Dominio validado", max_length=255, unique=True)),
                ("has_mx", models.BooleanField(help_text="True si el dominio tiene registros MX válidos")),
                (
                    "mx_records",
                    models.JSONField(
                        default=list,
                        help_text="Lista de registros MX encontrados (ej: ['alt1.gmail-smtp-in.l.google.com'])",
                    ),
                ),
                (
                    "spf",
                    models.TextField(
                        blank=True,
                        help_text="Registro SPF encontrado (ej: 'v=spf1 include:_spf.google.com ~all')",
                        null=True,
                    ),
                ),
                (
                    "dmarc",
                    models.TextField(
                        blank=True, help_text="Registro DMARC encontrado (ej: 'v=DMARC1; p=reject; ...')", null=True
                    ),
                ),
                (
                    "disposable",
                    models.BooleanField(
                        default=False, help_text="True si el dominio está en la lista de correos temporales"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="Fecha de la última verificación"),
                ),
                (
                    "next_check_at",
                    models.DateTimeField(db_index=True, help_text="Fecha de la próxima verificación recomendada"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "marketing_email_domain_validation",
                "indexes": [
                    models.Index(fields=["domain", "next_check_at"], name="marketing_e_domain_c06527_idx"),
                    models.Index(fields=["last_checked_at"], name="marketing_e_last_ch_113f80_idx"),
                ],
            },
        ),
    ]
