# Generated by Django 5.2 on 2025-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_alter_coursetranslation_prerequisite"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDomainValidation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "validation_type",
                    models.CharField(
                        choices=[("MX_RECORD", "MX Record"), ("SMTP_CHECK", "SMTP Check")],
                        help_text="Tipo de validación realizada",
                        max_length=20,
                    ),
                ),
                ("domain", models.CharField(db_index=True, help_text="Dominio validado", max_length=255)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Email completo (solo para SMTP checks)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_valid", models.BooleanField(help_text="Resultado de la validación")),
                (
                    "valid_until",
                    models.DateTimeField(db_index=True, help_text="Fecha hasta la cual este resultado es válido"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "marketing_email_domain_validation",
                "indexes": [
                    models.Index(
                        fields=["domain", "validation_type", "valid_until"], name="marketing_e_domain_885b01_idx"
                    ),
                    models.Index(
                        fields=["email", "validation_type", "valid_until"], name="marketing_e_email_75f41b_idx"
                    ),
                ],
            },
        ),
    ]
