# Generated by Django 5.2 on 2025-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_emaildomainvalidation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildomainvalidation",
            name="has_mx",
            field=models.BooleanField(default=False, help_text="True si el dominio tiene registros MX válidos"),
        ),
    ]
