# Generated by Django 3.0.7 on 2020-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_auto_20200619_0133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="last_name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
