# Generated by Django 5.2 on 2025-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0007_alter_emaildomainvalidation_has_mx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildomainvalidation",
            name="next_check_at",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="Fecha de la próxima verificación recomendada", null=True
            ),
        ),
    ]
