# Generated by Django 5.2 on 2025-11-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0008_alter_emaildomainvalidation_next_check_at"),
        ("payments", "0026_bag_plan_addons_bag_plan_addons_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="suggested_plan_addon",
            field=models.ManyToManyField(
                blank=True,
                help_text="Suggested plan addons for this course",
                related_name="suggested_courses",
                to="payments.plan",
            ),
        ),
    ]
