# Generated by Django 5.2 on 2025-12-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_add_academy_features"),
        ("marketing", "0009_course_suggested_plan_addon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseResaleSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plan_slug",
                    models.SlugField(
                        blank=True,
                        default=None,
                        help_text="Custom plan slug for the reseller (overrides course.plan_slug)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "plan_by_country_code",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Custom plan mapping by country code for the reseller (overrides course.plan_by_country_code)",
                        null=True,
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="Custom icon for the reseller (overrides course.icon_url)",
                        null=True,
                    ),
                ),
                (
                    "banner_image",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="Custom banner image for the reseller (overrides course.banner_image)",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Custom color in hexadecimal format for the reseller (overrides course.color)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Custom technologies list for the reseller (overrides course.technologies)",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE", "Active"), ("DELETED", "Deleted"), ("ARCHIVED", "Archived")],
                        default=None,
                        help_text="Status for the reseller (overrides course.status, defaults to ACTIVE if null)",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Custom status message for the reseller",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("UNLISTED", "Unlisted"), ("PUBLIC", "Public")],
                        default="UNLISTED",
                        help_text="Visibility status for the reseller (overrides course.visibility)",
                        max_length=15,
                    ),
                ),
                (
                    "is_listed",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Controls inclusion in reseller's listings and sitemaps (overrides course.is_listed)",
                        null=True,
                    ),
                ),
                (
                    "has_waiting_list",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Whether the reseller has a waiting list (overrides course.has_waiting_list)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether the resale is currently active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Academy that is reselling the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resale_courses",
                        to="admissions.academy",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Original course being resold",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resale_settings",
                        to="marketing.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Resale Settings",
                "verbose_name_plural": "Course Resale Settings",
                "db_table": "marketing_course_resale_settings",
                "unique_together": {("course", "academy")},
            },
        ),
    ]
