# Generated by Django 5.2 on 2025-01-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0010_courseresalesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlink",
            name="event",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Event reference in format '<id:slug>' (e.g., '<3434:event_slug>')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="course",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Course reference in format '<id:slug>' (e.g., '<123:course_slug>')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="downloadable",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Downloadable reference in format '<id:slug>' (e.g., '<567:downloadable_slug>')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="plan",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Plan reference in format '<id:slug>' (e.g., '<789:plan_slug>')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="referrer_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who referred this link (for affiliate tracking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_shortlinks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="purpose",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Internal description of what this link is used for",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="notes",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Internal notes about this short link",
                max_length=1000,
                null=True,
            ),
        ),
    ]

