# Generated by Django 5.2 on 2025-01-20 00:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_academy_from_ac_academy(apps, schema_editor):
    """Data migration: Set academy = ac_academy.academy for existing tags"""
    Tag = apps.get_model("marketing", "Tag")
    for tag in Tag.objects.filter(ac_academy__isnull=False, academy__isnull=True):
        if tag.ac_academy and tag.ac_academy.academy:
            tag.academy = tag.ac_academy.academy
            tag.save(update_fields=["academy"])


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_add_academy_features"),
        ("marketing", "0011_add_shortlink_traceability_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="acp_id",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="The id coming from active campaign (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="subscribers",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of subscribers in ActiveCampaign (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Academy this tag belongs to (required if ac_academy is not set)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.academy",
            ),
        ),
        migrations.RunPython(backfill_academy_from_ac_academy, migrations.RunPython.noop),
    ]



