# Generated by Django 5.2 on 2025-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0012_make_activecampaign_optional_for_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="ac_reservation_or_course_form_of_payment",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Reservation or course form of payment (e.g. '50€ May, 50€ June')",
                max_length=500,
                null=True,
            ),
        ),
    ]
