# Generated by Django 5.2 on 2026-05-18

from django.db import migrations

RESERVATION_FORM_OF_PAYMENT_FIELD_ID = "51"


def copy_column_to_custom_fields(apps, schema_editor):
    """Preserve values in custom_fields before dropping the dedicated column."""
    FormEntry = apps.get_model("marketing", "FormEntry")

    queryset = FormEntry.objects.exclude(ac_reservation_or_course_form_of_payment__isnull=True).exclude(
        ac_reservation_or_course_form_of_payment=""
    )

    for entry in queryset.iterator(chunk_size=500):
        value = entry.ac_reservation_or_course_form_of_payment
        custom_fields = entry.custom_fields if isinstance(entry.custom_fields, dict) else {}
        custom_fields = dict(custom_fields)

        existing = custom_fields.get(RESERVATION_FORM_OF_PAYMENT_FIELD_ID)
        if existing is None or existing == "":
            custom_fields[RESERVATION_FORM_OF_PAYMENT_FIELD_ID] = value
            entry.custom_fields = custom_fields
            entry.save(update_fields=["custom_fields"])


def restore_column_from_custom_fields(apps, schema_editor):
    """Reverse: copy custom_fields[51] back into the column when re-adding it."""
    FormEntry = apps.get_model("marketing", "FormEntry")

    for entry in FormEntry.objects.iterator(chunk_size=500):
        if not isinstance(entry.custom_fields, dict):
            continue

        value = entry.custom_fields.get(RESERVATION_FORM_OF_PAYMENT_FIELD_ID)
        if value is not None and value != "":
            entry.ac_reservation_or_course_form_of_payment = value
            entry.save(update_fields=["ac_reservation_or_course_form_of_payment"])


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0013_add_ac_reservation_or_course_form_of_payment"),
    ]

    operations = [
        migrations.RunPython(copy_column_to_custom_fields, restore_column_from_custom_fields),
        migrations.RemoveField(
            model_name="formentry",
            name="ac_reservation_or_course_form_of_payment",
        ),
    ]
