# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0014_remove_ac_reservation_or_course_form_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="activecampaignacademy",
            name="status_page_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Public status page URL where the CRM vendor reports uptime and downtime",
                null=True,
            ),
        ),
    ]
