# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0019_academy_default_plan"),
        ("marketing", "0015_activecampaignacademy_status_page_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmLeadOverride",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_field", models.CharField(choices=[("course", "course"), ("utm_campaign", "utm_campaign"), ("utm_source", "utm_source"), ("utm_medium", "utm_medium"), ("utm_content", "utm_content"), ("location", "location"), ("tags", "tags"), ("country", "country"), ("language", "language")], max_length=30)),
                ("match_value", models.CharField(help_text="Case-insensitive exact match against the FormEntry payload", max_length=255)),
                ("destination_ac_url", models.URLField(blank=True, default=None, null=True)),
                ("destination_ac_key", models.CharField(blank=True, default=None, max_length=150, null=True)),
                (
                    "destination_crm_vendor",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE_CAMPAIGN", "Active Campaign"), ("BREVO", "Brevo")],
                        default=None,
                        help_text="Leave empty with url and key to skip CRM. Fill all three to send to another AC/Brevo",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Empty = all academies. Set = only FormEntries whose location resolved to this academy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="crmleadoverride",
            constraint=models.UniqueConstraint(
                fields=("match_field", "match_value", "academy"),
                name="uniq_crm_lead_override_match",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="crmleadoverride",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        models.Q(
                            models.Q(("destination_ac_url", ""), ("destination_ac_url__isnull", True), _connector="OR"),
                            models.Q(("destination_ac_key", ""), ("destination_ac_key__isnull", True), _connector="OR"),
                            models.Q(
                                ("destination_crm_vendor", ""),
                                ("destination_crm_vendor__isnull", True),
                                _connector="OR",
                            ),
                        ),
                        models.Q(
                            ("destination_ac_url__isnull", False),
                            models.Q(("destination_ac_url", ""), _negated=True),
                            ("destination_ac_key__isnull", False),
                            models.Q(("destination_ac_key", ""), _negated=True),
                            ("destination_crm_vendor__isnull", False),
                            models.Q(("destination_crm_vendor", ""), _negated=True),
                        ),
                        _connector="OR",
                    )
                ),
                name="crm_lead_override_destination_all_or_nothing",
            ),
        ),
    ]
