# Generated by Django 3.1.4 on 2020-12-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0028_auto_20201218_0534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="acp_id",
            field=models.PositiveIntegerField(help_text="ID asigned in active campaign"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="acp_id",
            field=models.IntegerField(help_text="The id coming from active campaign"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
    ]
