# Generated by Django 3.1.6 on 2021-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0032_auto_20210128_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="deal_status",
            field=models.CharField(
                blank=True, choices=[("WON", "Won"), ("LOST", "Lost")], default=None, max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="sentiment",
            field=models.CharField(
                blank=True, choices=[("GOOD", "Good"), ("BAD", "Bad")], default=None, max_length=15, null=True
            ),
        ),
    ]
