# Generated by Django 3.2 on 2021-06-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0018_alter_cohortuser_role"),
        ("marketing", "0034_auto_20210430_0035"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formentry",
            name="ac_academy",
        ),
        migrations.CreateModel(
            name="AcademyAlias",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("active_campaign_slug", models.SlugField()),
                ("academy", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
    ]
