# Generated by Django 3.2.9 on 2022-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0048_alter_formentry_utm_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='utm_content',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
