# Generated by Django 3.2.15 on 2022-09-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0057_auto_20220919_2057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="storage_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PERSISTED", "Persisted"),
                    ("DUPLICATED", "Duplicated"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
