# Generated by Django 3.2.16 on 2023-02-15 19:28

import breathecode.utils.validators.language
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0053_alter_cohort_kickoff_date'),
        ('marketing', '0062_alter_formentry_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('status',
                 models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted'),
                                           ('ARCHIVED', 'Archived')],
                                  default='ACTIVE',
                                  max_length=15)),
                ('visibility',
                 models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'),
                                           ('PUBLIC', 'Public')],
                                  default='PRIVATE',
                                  max_length=15)),
                ('icon_url', models.URLField(help_text='Image icon to show on website')),
                ('technologies', models.SlugField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academy')),
                ('syllabus',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang',
                 models.CharField(max_length=5,
                                  validators=[breathecode.utils.validators.language.validate_language_code])),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.course')),
            ],
        ),
    ]
