# Generated by Django 3.2.18 on 2023-06-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0069_alter_activecampaignwebhook_run_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadgenerationapp",
            name="last_call_log",
            field=models.TextField(
                blank=True, default=None, help_text="Incomig payload from the last request", max_length=450, null=True
            ),
        ),
    ]
