# Generated by Django 3.2.18 on 2023-06-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0070_auto_20230622_0838"),
        ("marketing", "0070_leadgenerationapp_last_call_log"),
    ]

    operations = []
