# Generated by Django 3.2.19 on 2023-07-18 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0071_merge_20230629_0305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="phone",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+99999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{8,15}$",
                    )
                ],
            ),
        ),
    ]
