# Generated by Django 3.2.18 on 2023-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0073_formentry_attribution_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="attribution_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Keep a consistent attribution from al the previous applications from the same email (it will reset to a new one for each WON)",
                max_length=30,
                null=True,
            ),
        ),
    ]
