# Generated by Django 3.2.18 on 2023-08-31 19:58

from django.db import migrations
from django.db import connection


def convert_to_str(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE marketing_formentry SET attribution_id = CAST(attribution_id AS VARCHAR) WHERE attribution_id IS NOT NULL"
        )


def convert_to_int(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE marketing_formentry SET attribution_id = CAST(attribution_id AS BIGINT) WHERE attribution_id IS NOT NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0074_alter_formentry_attribution_id"),
    ]

    operations = [
        migrations.RunPython(convert_to_str, reverse_code=convert_to_int),
    ]
