# Generated by Django 3.2.18 on 2023-08-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0074_coursetranslation_landing_url"),
        ("marketing", "0075_auto_20230831_1958"),
    ]

    operations = []
