# Generated by Django 5.0.2 on 2024-03-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0064_academy_legal_name'),
        ('marketing', '0077_course_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.cohort'),
        ),
    ]
