# Generated by Django 5.0.2 on 2024-03-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0078_coursetranslation_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetranslation",
            name="description",
            field=models.TextField(max_length=400),
        ),
    ]
