# Generated by Django 5.0.3 on 2024-03-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0078_alter_formentry_storage_status"),
        ("marketing", "0083_alter_coursetranslation_video_url"),
    ]

    operations = []
