# Generated by Django 5.0.3 on 2024-04-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0085_merge_20240402_1513'),
        ('marketing', '0085_merge_20240403_0116'),
    ]

    operations = []
