# Generated by Django 5.1.2 on 2024-11-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0090_course_cohorts_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cohorts_order",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="An IDs comma separated list to indicate the order in which cohorts in the cohort group will be displayed",
                max_length=50,
                null=True,
            ),
        ),
    ]
