# Generated by Django 5.1.2 on 2024-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0091_course_cohorts_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetranslation",
            name="heading",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Heading that will be used in the landing page",
                max_length=160,
                null=True,
            ),
        ),
    ]
