# Generated by Django 5.1.6 on 2025-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0094_alter_formentry_course_alter_formentry_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="cohorts_group",
        ),
        migrations.RemoveField(
            model_name="course",
            name="cohorts_order",
        ),
        migrations.AddField(
            model_name="course",
            name="banner_image",
            field=models.URLField(blank=True, default=None, help_text="Banner image to show on website", null=True),
        ),
    ]
