# Generated by Django 5.2 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0097_coursetranslation_featured_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="technologies",
            field=models.CharField(max_length=240),
        ),
    ]
