# Generated by Django 5.2 on 2025-05-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0099_coursetranslation_preview_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="plan_by_country_code",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
