# Generated by Django 3.2.12 on 2022-04-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="html",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
