# Generated by Django 3.2.12 on 2022-05-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0039_syllabus_main_technologies"),
        ("registry", "0004_auto_20220415_1515"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordCluster",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("lang", models.CharField(help_text="E.g: en, es, it", max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
        migrations.CreateModel(
            name="AssetKeyword",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("lang", models.CharField(help_text="E.g: en, es, it", max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registry.keywordcluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("lang", models.CharField(help_text="E.g: en, es, it", max_length=2)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.assetcategory",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="seo_keywords",
            field=models.ManyToManyField(
                blank=True, help_text="Optimize for a max of two keywords per asset", to="registry.AssetKeyword"
            ),
        ),
    ]
