# Generated by Django 3.2.16 on 2022-12-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0019_auto_20221109_0246"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="readme_updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
