# Generated by Django 3.2.16 on 2022-12-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0021_alter_asset_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="registry.assetcategory"
            ),
        ),
    ]
