# Generated by Django 3.2.16 on 2023-01-05 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0020_asset_readme_updated_at"),
        ("registry", "0022_alter_asset_category"),
    ]

    operations = []
