# Generated by Django 3.2.16 on 2023-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0024_credentialsoriginality_originalityscan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialsoriginality",
            name="usage",
            field=models.JSONField(default=dict),
        ),
    ]
