# Generated by Django 3.2.18 on 2023-04-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0029_syllabusversionproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("UNLISTED", "Unlisted"), ("PRIVATE", "Private")],
                default="PUBLIC",
                help_text="It won't be shown on the website unleast the status is published",
                max_length=20,
            ),
        ),
    ]
