# Generated by Django 3.2.19 on 2023-06-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0030_alter_asset_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PLANNING", "Planning"),
                    ("WRITING", "Writing"),
                    ("DRAFT", "Draft"),
                    ("OPTIMIZED", "Optimized"),
                    ("PUBLISHED", "Published"),
                ],
                default="NOT_STARTED",
                help_text="Related to the publishing of the asset",
                max_length=20,
            ),
        ),
    ]
