# Generated by Django 3.2.20 on 2023-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0033_alter_contentvariable_default_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettechnology",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
