# Generated by Django 3.2.23 on 2023-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0038_auto_20231123_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assets_related",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related assets used to get prepared before going through this asset.",
                to="registry.Asset",
            ),
        ),
    ]
