# Generated by Django 5.1.1 on 2024-10-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0045_asset_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetContext",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ai_context", models.TextField()),
                ("asset", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registry.asset")),
            ],
        ),
    ]
