# Generated by Django 5.1.1 on 2024-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0046_assetcontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="preview_in_tutorial",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Used in 4geeks.com before the tutorial is about to start",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="preview",
            field=models.URLField(
                blank=True, default=None, help_text="This preview will be used when shared in social media", null=True
            ),
        ),
    ]
