# Generated by Django 5.1.1 on 2024-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0048_asset_dependencies_asset_is_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="is_template",
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("PROJECT", "Project"),
                    ("STARTER", "Starter Template"),
                    ("EXERCISE", "Exercise"),
                    ("QUIZ", "Quiz"),
                    ("LESSON", "Lesson"),
                    ("VIDEO", "Video"),
                    ("ARTICLE", "Article"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asseterrorlog",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROJECT", "Project"),
                    ("STARTER", "Starter Template"),
                    ("EXERCISE", "Exercise"),
                    ("QUIZ", "Quiz"),
                    ("LESSON", "Lesson"),
                    ("VIDEO", "Video"),
                    ("ARTICLE", "Article"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
