# Generated by Django 5.1.2 on 2024-11-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0050_assetcontext_status_assetcontext_status_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcontext",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("PROCESSING", "PROCESSING"), ("DONE", "DONE"), ("ERROR", "ERROR")],
                db_index=True,
                default="PENDING",
                help_text="If pending, it means it hasn't been generated yet, processing means that is being generated at this moment, done means it has been generated",
                max_length=20,
            ),
        ),
    ]
