# Generated by Django 5.1.2 on 2024-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0051_alter_assetcontext_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettechnology",
            name="marketing_information",
            field=models.JSONField(
                blank=True, default=None, help_text="JSON structure for marketing information", null=True
            ),
        ),
    ]
