# Generated by Django 5.1.6 on 2025-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0054_merge_20241216_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="feature",
            field=models.BooleanField(
                default=True,
                help_text="If true, it will be shown in the landing pages of the website for marketing purposes",
            ),
        ),
    ]
