# Generated by Django 3.2.9 on 2022-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0011_issue_node_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="repository_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="url",
            field=models.URLField(),
        ),
    ]
