# Generated by Django 3.2.16 on 2023-02-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance", "0023_auto_20221221_1133"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RepositoryIssueWebhook",
        ),
    ]
