# Generated by Django 3.1.4 on 2020-12-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_auto_20201209_0216"),
        ("assignments", "0004_auto_20200708_0049"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cohort",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"
            ),
        ),
    ]
