# Generated by Django 3.2.16 on 2023-02-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0011_alter_task_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalproject",
            name="screenshot",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
