# Generated by Django 3.2.20 on 2023-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0012_finalproject_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="opened_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
