# Generated by Django 5.0.1 on 2024-02-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0016_task_delivered_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentTelemetry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_slug", models.CharField(max_length=200)),
                (
                    "telemetry",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Incoming JSON from LearnPack with detailed telemetry info",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="telemetry",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Learnpack telemetry json will be stored and shared among all the assignments form the same associalted_slug",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignmenttelemetry",
            ),
        ),
        migrations.CreateModel(
            name="LearnPackWebhook",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_streaming", models.BooleanField()),
                ("event", models.CharField(max_length=15)),
                (
                    "payload",
                    models.JSONField(blank=True, default=None, help_text="Will be set by learnpack", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done"), ("ERROR", "Error")],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                ("status_text", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "telemetry",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.assignmenttelemetry",
                    ),
                ),
            ],
        ),
    ]
