# Generated by Django 5.1.1 on 2024-09-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0018_repositorydeletionorder_repositorywhitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydeletionorder",
            name="starts_transferring_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
