# Generated by Django 5.1.2 on 2024-11-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0019_repositorydeletionorder_starts_transferring_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattachment",
            name="mime",
            field=models.CharField(max_length=120),
        ),
    ]
