# Generated by Django 5.2 on 2025-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherinfluencerreferralcommission",
            name="matured_at",
        ),
        migrations.AlterField(
            model_name="teacherinfluencerreferralcommission",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid"), ("CANCELLED", "Cancelled")],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
