# Generated by Django 5.2 on 2025-08-25 02:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_cohort_shortcuts"),
        ("commission", "0004_change_created_at_to_default"),
        ("payments", "0007_plan_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserCohortEngagement",
            new_name="UserUsageCommission",
        ),
    ]
