# Generated by Django 5.2 on 2025-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0006_alter_teacherinfluencercommission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userusagecommission",
            name="details",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional details and metadata about this usage commission"
            ),
        ),
    ]
