# Generated by Django 5.2 on 2025-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0007_userusagecommission_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geekcreatorcommission",
            name="details",
        ),
        migrations.AddField(
            model_name="geekcreatorpayment",
            name="status_text",
            field=models.TextField(
                blank=True,
                help_text="Additional text explaining the status (e.g., why a payment is in preview)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geekcreatorpayment",
            name="status",
            field=models.CharField(
                choices=[("PREVIEW", "Preview"), ("PENDING", "Pending"), ("PAID", "Paid")],
                db_index=True,
                default="PENDING",
                help_text="Current status of the payment",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="geekcreatorreferralcommission",
            name="amount",
            field=models.FloatField(
                default=0.0, help_text="Commission amount earned from this referral (already applied 0.5 commission)"
            ),
        ),
    ]
