# Generated by Django 5.2 on 2025-05-16 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="main_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="payments.currency",
            ),
        ),
        migrations.AddField(
            model_name="academy",
            name="city",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.city"),
        ),
        migrations.AddField(
            model_name="cohort",
            name="academy",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"),
        ),
        migrations.AddField(
            model_name="cohort",
            name="micro_cohorts",
            field=models.ManyToManyField(
                blank=True,
                help_text="This cohorts will represent small courses inside a main course",
                related_name="main_cohorts",
                to="admissions.cohort",
            ),
        ),
        migrations.AddField(
            model_name="cohorttimeslot",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"),
        ),
        migrations.AddField(
            model_name="cohortuser",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"),
        ),
        migrations.AddField(
            model_name="cohortuser",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.country"),
        ),
        migrations.AddField(
            model_name="academy",
            name="country",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.country"),
        ),
        migrations.AddField(
            model_name="syllabus",
            name="academy_owner",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"
            ),
        ),
        migrations.AddField(
            model_name="syllabusschedule",
            name="academy",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"
            ),
        ),
        migrations.AddField(
            model_name="syllabusschedule",
            name="syllabus",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.syllabus"
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.syllabusschedule",
            ),
        ),
        migrations.AddField(
            model_name="syllabusscheduletimeslot",
            name="schedule",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.syllabusschedule"),
        ),
        migrations.AddField(
            model_name="syllabusversion",
            name="syllabus",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.syllabus"),
        ),
        migrations.AddField(
            model_name="cohort",
            name="syllabus_version",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.syllabusversion",
            ),
        ),
    ]
