# Generated by Django 5.2 on 2025-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="shortcuts",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Array of shortcut objects, adding shortcuts will create a widget on the header of the cohort dashboard",
                null=True,
            ),
        ),
    ]
