# Generated by Django 5.2 on 2025-08-28 13:14

import breathecode.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_cohort_shortcuts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabusversion",
            name="json",
            field=models.JSONField(default=breathecode.admissions.models.default_syllabus_version_json),
        ),
    ]
