# Generated by Django 5.2 on 2025-10-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_alter_syllabusversion_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Primary owner of the academy, typically the first admin with role 'admin'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_academies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
