# Generated by Django 3.0.7 on 2020-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_auto_20200703_1752"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cohort",
            name="online_room_url",
        ),
        migrations.AlterField(
            model_name="cohort",
            name="ending_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
