# Generated by Django 3.0.7 on 2020-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_auto_20200703_1951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortuser",
            name="educational_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("POSTPONED", "Postponed"),
                    ("GRADUATED", "Graduated"),
                    ("SUSPENDED", "Suspended"),
                    ("DROPPED", "Dropped"),
                ],
                default=None,
                max_length=15,
                null=True,
            ),
        ),
    ]
