# Generated by Django 5.2 on 2025-10-22 16:25

import breathecode.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_populate_academy_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="white_label_features",
            field=models.JSONField(
                blank=True,
                default=breathecode.admissions.models.default_white_label_features,
                help_text="JSON field to store white label feature configurations for navigation and dashboard widgets",
            ),
        ),
    ]
