# Generated by Django 5.2 on 2025-10-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0008_alter_academy_white_label_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="If this syllabus was forked/created based another one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="admissions.syllabus",
            ),
        ),
        migrations.AddField(
            model_name="syllabusversion",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="If this syllabus version was forked/created based another one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="admissions.syllabusversion",
            ),
        ),
    ]
