# Generated by Django 3.1 on 2020-09-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0008_auto_20200708_0049"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="logo_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
