# Generated by Django 5.2 on 2025-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0009_syllabus_forked_from_syllabusversion_forked_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabusversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Published"),
                    ("DRAFT", "Draft"),
                    ("DEPRECATED", "Deprecated"),
                    ("DELETED", "Deleted"),
                ],
                db_index=True,
                default="PUBLISHED",
                max_length=15,
            ),
        ),
    ]
