# Generated by Django 5.2 on 2025-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0010_alter_syllabusversion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="enable_assessments_telemetry",
            field=models.BooleanField(
                db_index=True, default=False, help_text="If true, the assessments will be tracked in the database"
            ),
        ),
    ]
