# Generated by Django 5.2 on 2025-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0011_cohort_enable_assessments_telemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabusversion",
            name="reasoning",
            field=models.TextField(
                blank=True, default=None, help_text="Why is this new version being created?", max_length=450, null=True
            ),
        ),
    ]
