# Generated by Django 3.1.1 on 2020-10-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_auto_20201005_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='schedule_type',
            field=models.CharField(choices=[('PART-TIME', 'Part-Time'), ('FULL-TIME', 'Full-Time')], default='PART-TIME', max_length=15),
        ),
    ]
