# Generated by Django 5.2 on 2025-12-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_add_reasoning_to_syllabus_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academy",
            name="white_label_features",
        ),
    ]
