# Generated by Django 5.2 on 2025-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_add_reasoning_to_syllabus_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="platform_description",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Description of the platform shown in notification emails",
                null=True,
            ),
        ),
    ]
