# Generated by Django 3.1.4 on 2020-12-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_auto_20201218_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.city'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.country'),
        ),
    ]
