# Generated by Django 5.2 on 2025-12-01 21:23

from django.db import connection, migrations


def remove_white_label_features_if_exists(apps, schema_editor):
    """
    Remove white_label_features column only if it exists.
    
    This makes the migration idempotent - it can be run multiple times
    without errors. This is important for production environments where
    the column might have been removed manually or in a different way.
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists in the database
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='admissions_academy' 
            AND column_name='white_label_features'
            AND table_schema = current_schema()
        """)
        
        if cursor.fetchone():
            # Column exists, remove it using SQL
            # Using IF EXISTS makes it safe even if called multiple times
            cursor.execute("ALTER TABLE admissions_academy DROP COLUMN IF EXISTS white_label_features")


def reverse_remove_white_label_features(apps, schema_editor):
    """
    Reverse operation - add the column back if needed.
    
    Note: This is a simplified reverse. In a real scenario, you might want
    to restore the field definition from migration 0007 or 0008.
    """
    # This is a no-op since we're removing a deprecated field
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_add_platform_description"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operation: idempotent removal
            database_operations=[
                migrations.RunPython(
                    remove_white_label_features_if_exists,
                    reverse_remove_white_label_features,
                ),
            ],
            # State operation: tell Django the field is removed
            state_operations=[
                migrations.RemoveField(
                    model_name="academy",
                    name="white_label_features",
                ),
            ],
        ),
    ]
