# Generated by Django 3.1.4 on 2020-12-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_auto_20201218_2000'),
        ('admissions', '0014_auto_20201218_0534'),
    ]

    operations = [
    ]
