# Generated by Django 5.2 on 2025-12-01 21:23

import breathecode.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0014_remove_academy_white_label_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="academy_features",
            field=models.JSONField(
                blank=True,
                default=breathecode.admissions.models.default_academy_features,
                help_text="JSON field to store feature flag configurations for all academies. Allows enabling/disabling features and customizing navigation. Example: hide dashboard widgets, include custom links, etc.",
                verbose_name="Academy Features",
            ),
        ),
    ]

