# Generated by Django 5.2 on 2025-12-08 06:12

import breathecode.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_add_academy_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="welcome_video",
            field=models.JSONField(
                blank=True,
                default=breathecode.admissions.models.default_welcome_video,
                help_text="Video de bienvenida con preview_image y url. Formato: {'url': 'url', 'preview_image': 'url'}. Si no se especifica en el payload de la invitación, se usará este valor por defecto.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academy",
            name="white_label_params",
            field=models.JSONField(
                blank=True,
                default=breathecode.admissions.models.default_white_label_params,
                help_text="This is a json with translations {es: '', en: ''} that will include a markdown that can be rendered on the right side of the login when an academy is whitelabel.",
                null=True,
            ),
        ),
    ]
