# Generated by Django 3.1.6 on 2021-02-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_auto_20210220_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='certificate',
        ),
    ]
