# Generated by Django 5.2 on 2025-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_academy_welcome_video_academy_white_label_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="short_url",
            field=models.CharField(
                blank=True, default=None, help_text="Use for ShortLinks and redirects", max_length=255, null=True
            ),
        ),
    ]
