# Generated by Django 3.2 on 2021-04-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_cohort_never_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("TEACHER", "Teacher"),
                    ("ASSISTANT", "Assistant"),
                    ("REVIEWER", "Reviewer"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=9,
            ),
        ),
    ]
