# Generated by Django 5.2 on 2026-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_academy_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohorts_order',
            field=models.CharField(blank=True, default=None, help_text='An IDs comma separated list to indicate the order in which the micro cohorts will be displayed', max_length=120, null=True),
        ),
    ]
