# Generated by Django 3.2 on 2021-05-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_certificatetimeslot_cohorttimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorttimeslot',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.certificatetimeslot'),
        ),
    ]
