# Generated by Django 3.2.5 on 2021-07-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0021_auto_20210727_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialtymode",
            name="syllabus",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.syllabus"
            ),
        ),
    ]
