# Generated by Django 3.2.5 on 2021-07-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_auto_20210709_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohorttimeslot',
            name='specialty_mode',
        ),
    ]
