# Generated by Django 3.2.5 on 2021-07-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_alter_specialtymode_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtymode',
            name='syllabus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.syllabus'),
        ),
    ]
