# Generated by Django 3.2.12 on 2022-03-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0032_auto_20220304_1747"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpecialtyMode",
            new_name="SyllabusSchedule",
        ),
    ]
