# Generated by Django 3.2.12 on 2022-03-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0035_rename_specialty_mode_syllabusscheduletimeslot_schedule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cohort",
            old_name="specialty_mode",
            new_name="schedule",
        ),
    ]
