# Generated by Django 3.2.12 on 2022-03-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0037_alter_cohort_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="syllabus_version",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="admissions.syllabusversion"
            ),
        ),
    ]
