# Generated by Django 3.2.13 on 2022-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0039_syllabus_main_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusversion',
            name='change_log_details',
            field=models.TextField(blank=True, default=None, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='syllabusversion',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')],
                                   default='PUBLISHED',
                                   max_length=15),
        ),
    ]
