# Generated by Django 3.2.13 on 2022-05-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0040_auto_20220510_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortuser",
            name="watching",
            field=models.BooleanField(
                default=False, help_text="You can active students to the watch list and monitor them closely"
            ),
        ),
    ]
