# Generated by Django 3.2.14 on 2022-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0041_cohortuser_watching"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="white_labeled",
            field=models.BooleanField(default=False),
        ),
    ]
