# Generated by Django 3.2.15 on 2022-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0045_alter_syllabusversion_integrity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='available_as_sass',
            field=models.BooleanField(default=False,
                                      help_text='Academies available as SASS will be sold thru 4Geeks.com'),
        ),
    ]
