# Generated by Django 3.2.16 on 2023-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0050_alter_cohort_is_hidden_on_prework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='kickoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
