# Generated by Django 3.2.18 on 2023-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0060_alter_cohortuser_educational_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="white_label_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
