# Generated by Django 3.2.21 on 2023-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0061_academy_white_label_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="is_documentation",
            field=models.BooleanField(default=False),
        ),
    ]
