# Generated by Django 3.2.22 on 2023-10-17 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0062_syllabus_is_documentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="available_as_saas",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Academies available as SAAS will be sold thru 4Geeks.com"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="is_hidden_on_prework",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Determines if the cohorts will be shown in the dashboard if it's status is 'PREWORK'",
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="latitude",
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="academy",
            name="longitude",
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="academy",
            name="status",
            field=models.CharField(
                choices=[("INACTIVE", "Inactive"), ("ACTIVE", "Active"), ("DELETED", "Deleted")],
                db_index=True,
                default="ACTIVE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="timezone",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="academy",
            name="zip_code",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="accepts_enrollment_suggestions",
            field=models.BooleanField(
                db_index=True, default=True, help_text="The system will suggest won leads to be added to this cohort"
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="available_as_saas",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                help_text="Cohorts available as SAAS will be sold through plans at 4Geeks.com",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="ending_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="is_hidden_on_prework",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                help_text="Determines if the cohort will be shown in the dashboard if it's status is 'PREWORK'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="kickoff_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="language",
            field=models.CharField(db_index=True, default="en", max_length=2),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="never_ends",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="private",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="It will not show on the public API endpoints but you will still be able to add people manually",
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="remote_available",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True (default) if the students from other cities can take it from home",
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="slug",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="stage",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inactive"),
                    ("PREWORK", "Prework"),
                    ("STARTED", "Started"),
                    ("FINAL_PROJECT", "Final Project"),
                    ("ENDED", "Ended"),
                    ("DELETED", "Deleted"),
                ],
                db_index=True,
                default="INACTIVE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="timezone",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="ending_at",
            field=models.BigIntegerField(
                db_index=True,
                default=202101010000,
                help_text="The first 4 number are year, the next 2 number are month, the next 2 number are day, the next 2 number are hour and the last 2 number are second",
                validators=[
                    django.core.validators.MaxValueValidator(300000000000),
                    django.core.validators.MinValueValidator(202101010000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="recurrency_type",
            field=models.CharField(
                choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                db_index=True,
                default="WEEKLY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="recurrent",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="removed_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, help_text="This will be available until this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="starting_at",
            field=models.BigIntegerField(
                db_index=True,
                default=202101010000,
                help_text="The first 4 number are year, the next 2 number are month, the next 2 number are day, the next 2 number are hour and the last 2 number are second",
                validators=[
                    django.core.validators.MaxValueValidator(300000000000),
                    django.core.validators.MinValueValidator(202101010000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cohorttimeslot",
            name="timezone",
            field=models.CharField(db_index=True, default="America/New_York", max_length=50),
        ),
        migrations.AlterField(
            model_name="cohortuser",
            name="educational_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("POSTPONED", "Postponed"),
                    ("GRADUATED", "Graduated"),
                    ("SUSPENDED", "Suspended"),
                    ("DROPPED", "Dropped"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cohortuser",
            name="finantial_status",
            field=models.CharField(
                blank=True,
                choices=[("FULLY_PAID", "Fully Paid"), ("UP_TO_DATE", "Up to date"), ("LATE", "Late")],
                db_index=True,
                default=None,
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cohortuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("TEACHER", "Teacher"),
                    ("ASSISTANT", "Assistant"),
                    ("REVIEWER", "Reviewer"),
                    ("STUDENT", "Student"),
                ],
                db_index=True,
                default="STUDENT",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="cohortuser",
            name="watching",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="You can active students to the watch list and monitor them closely",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(db_index=True, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="is_documentation",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="name",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="private",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="syllabusschedule",
            name="description",
            field=models.TextField(db_index=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="syllabusschedule",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="syllabusschedule",
            name="schedule_type",
            field=models.CharField(
                choices=[("PART-TIME", "Part-Time"), ("FULL-TIME", "Full-Time")],
                db_index=True,
                default="PART-TIME",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="ending_at",
            field=models.BigIntegerField(
                db_index=True,
                default=202101010000,
                help_text="The first 4 number are year, the next 2 number are month, the next 2 number are day, the next 2 number are hour and the last 2 number are second",
                validators=[
                    django.core.validators.MaxValueValidator(300000000000),
                    django.core.validators.MinValueValidator(202101010000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="recurrency_type",
            field=models.CharField(
                choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                db_index=True,
                default="WEEKLY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="recurrent",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="removed_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, help_text="This will be available until this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="starting_at",
            field=models.BigIntegerField(
                db_index=True,
                default=202101010000,
                help_text="The first 4 number are year, the next 2 number are month, the next 2 number are day, the next 2 number are hour and the last 2 number are second",
                validators=[
                    django.core.validators.MaxValueValidator(300000000000),
                    django.core.validators.MinValueValidator(202101010000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="syllabusscheduletimeslot",
            name="timezone",
            field=models.CharField(db_index=True, default="America/New_York", max_length=50),
        ),
        migrations.AlterField(
            model_name="syllabusversion",
            name="integrity_check_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="syllabusversion",
            name="integrity_status",
            field=models.CharField(
                choices=[("ERROR", "Error"), ("PENDING", "Pending"), ("WARNING", "Warning"), ("OK", "Ok")],
                db_index=True,
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="syllabusversion",
            name="status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("DRAFT", "Draft")],
                db_index=True,
                default="PUBLISHED",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="syllabusversion",
            name="version",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
