# Generated by Django 5.0.1 on 2024-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0063_auto_20231017_0605"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="legal_name",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True),
        ),
    ]
