# Generated by Django 5.1.2 on 2024-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0064_academy_legal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortuser",
            name="educational_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("POSTPONED", "Postponed"),
                    ("GRADUATED", "Graduated"),
                    ("SUSPENDED", "Suspended"),
                    ("DROPPED", "Dropped"),
                    ("NOT_COMPLETING", "Not Completing"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=15,
                null=True,
            ),
        ),
    ]
