# Generated by Django 5.1.2 on 2024-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0066_cohort_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="micro_cohorts",
            field=models.ManyToManyField(
                blank=True,
                help_text="This cohorts will represent small courses inside a main course",
                related_name="main_cohorts",
                to="admissions.cohort",
            ),
        ),
    ]
