# Generated by Django 5.1.3 on 2024-12-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0065_alter_cohortuser_educational_status"),
        ("admissions", "0067_alter_cohort_micro_cohorts"),
    ]

    operations = []
