# Generated by Django 3.2.12 on 2022-04-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZyteProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zyte_api_key", models.CharField(max_length=150)),
                ("zyte_api_deploy", models.CharField(max_length=50)),
                (
                    "zyte_api_spider_number",
                    models.IntegerField(
                        help_text="This number is the one that corresponds when the ZYTE spider was created."
                    ),
                ),
                (
                    "zyte_api_last_job_number",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="(Optional field) Start at 0 but increase with each search.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.platform")),
            ],
        ),
        migrations.CreateModel(
            name="Spider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("job_search", models.CharField(max_length=150)),
                (
                    "loc_search",
                    models.CharField(
                        blank=True, help_text="This field may be optional on some platforms.", max_length=150, null=True
                    ),
                ),
                (
                    "zyte_spider_number",
                    models.IntegerField(
                        blank=True, default=0, help_text="This number must be copy from ZYTE", null=True
                    ),
                ),
                (
                    "zyte_job_number",
                    models.IntegerField(
                        blank=True, default=0, help_text="Start at 0 but increase on each fetch", null=True
                    ),
                ),
                (
                    "zyte_fetch_count",
                    models.IntegerField(default=0, help_text="The number of spider job excecutions to fetch"),
                ),
                ("zyte_last_fetch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "spider_last_run_status",
                    models.CharField(
                        choices=[
                            ("SYNCHED", "Synched"),
                            ("PENDING", "Pending"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("spider_last_run_desc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCHED", "Synched"),
                            ("PENDING", "Pending"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("sync_desc", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.position")),
                (
                    "zyte_project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.zyteproject"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.position")),
            ],
        ),
        migrations.CreateModel(
            name="LocationAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.location")),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("published_date_raw", models.CharField(max_length=50)),
                ("published_date_processed", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPENED", "Opened"), ("FILLED", "Filled")], default="OPENED", max_length=15
                    ),
                ),
                ("apply_url", models.URLField(max_length=500)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("USD", "USD"), ("CRC", "CRC"), ("CLP", "CLP"), ("EUR", "EUR"), ("UYU", "UYU")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("min_salary", models.FloatField(blank=True, null=True)),
                ("max_salary", models.FloatField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, max_length=253, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Internship", "Internship"),
                            ("Part-time", "Part-time"),
                            ("Temporary", "Temporary"),
                            ("Contract", "Contract"),
                        ],
                        default="Full-time",
                        max_length=15,
                    ),
                ),
                ("remote", models.BooleanField(default=False, verbose_name="Remote")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("career_tags", models.ManyToManyField(blank=True, null=True, to="career.CareerTag")),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="career.employer"
                    ),
                ),
                ("locations", models.ManyToManyField(blank=True, null=True, to="career.Location")),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.position")),
                ("spider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="career.spider")),
            ],
        ),
        migrations.AddField(
            model_name="employer",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="career.location"
            ),
        ),
    ]
