# Generated by Django 3.2.13 on 2022-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_auto_20220404_1939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="career_tags",
            field=models.ManyToManyField(blank=True, to="career.CareerTag"),
        ),
        migrations.AlterField(
            model_name="job",
            name="locations",
            field=models.ManyToManyField(blank=True, to="career.Location"),
        ),
    ]
