# Generated by Django 5.2 on 2026-02-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_academy_short_url"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner academy. Must be null when is_manageable_by_academy is True.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.academy",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_manageable_by_academy",
            field=models.BooleanField(
                default=False,
                help_text="If True, category is for API internal use; academies cannot manage it but can assign media.",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("slug", "academy"), name="media_category_slug_academy_unique"),
        ),
    ]
