# Generated by Django 3.1.7 on 2021-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="categories",
            field=models.ManyToManyField(blank=True, to="media.Category"),
        ),
    ]
