# Generated by Django 3.1.7 on 2021-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_auto_20210330_0754"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="hits",
            field=models.IntegerField(default=0),
        ),
    ]
