# Generated by Django 3.1.7 on 2021-04-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_auto_20210302_0254"),
        ("media", "0003_media_hits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="owner",
        ),
        migrations.AddField(
            model_name="media",
            name="academy",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"
            ),
        ),
    ]
