# Generated by Django 5.0.7 on 2024-08-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0064_academy_legal_name"),
        ("media", "0005_auto_20210524_1426"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=60)),
                ("chunk_index", models.PositiveIntegerField()),
                ("total_chunks", models.PositiveIntegerField()),
                ("chunk_size", models.PositiveIntegerField(help_text="Size of each chunk in bytes")),
                ("bucket", models.CharField(max_length=255)),
                ("operation_type", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academy where the file was uploaded",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=60)),
                ("hash", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
                ("bucket", models.CharField(max_length=255)),
                ("operation_type", models.CharField(max_length=60)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Metadata associated with the file, used for schedule the transfer",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("TRANSFERRING", "Transferring"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="CREATED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Academy where the file was uploaded",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
