# Generated by Django 3.2.3 on 2021-06-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_mediaresolution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresolution',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
            preserve_default=False,
        ),
    ]
