# Generated by Django 3.2.3 on 2021-06-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_mediaresolution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresolution',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
    ]
