# Generated by Django 3.2.9 on 2021-11-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('zyte_spider_number', models.IntegerField()),
                ('zyte_job_number', models.IntegerField()),
                ('status',
                 models.CharField(choices=[('SYNCHED', 'Synched'), ('PENDING', 'Pending'),
                                           ('WARNING', 'Warning'), ('ERROR', 'Error')],
                                  default='PENDING',
                                  max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='jobs.platform')),
            ],
        ),
    ]
