# Generated by Django 3.2.9 on 2022-02-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211213_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='published',
            new_name='published_date_raw',
        ),
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True,
                                   choices=[('USD', 'USD'), ('CRC', 'CRC'), ('CLP', 'CLP'), ('EUR', 'EUR'),
                                            ('UYU', 'UYU')],
                                   default='USD',
                                   max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published_date_processed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='zyte_last_fetch_date',
            field=models.DateTimeField(null=True),
        ),
    ]
