# Generated by Django 3.2.9 on 2021-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_spider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='spider',
            name='status',
            field=models.CharField(choices=[('SYNCHED', 'Synched'), ('PENDING', 'Pending'),
                                            ('WARNING', 'Warning'), ('ERROR', 'Error')],
                                   default='PENDING',
                                   max_length=15),
        ),
    ]
