# Generated by Django 3.2.16 on 2022-12-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_auto_20221214_1309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceitemfeature",
            name="how_many",
        ),
        migrations.RemoveField(
            model_name="serviceitemfeature",
            name="unit_type",
        ),
    ]
