# Generated by Django 3.2.16 on 2023-01-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_auto_20221231_0202"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncConsumable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expires_at", models.DateTimeField()),
                ("path", models.CharField(max_length=200)),
                ("related_pk", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("related_slug", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payments.service")),
            ],
        ),
    ]
