# Generated by Django 3.2.16 on 2023-01-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_auto_20230115_0509"),
        ("payments", "0012_auto_20230117_2124"),
    ]

    operations = []
