# Generated by Django 3.2.16 on 2023-01-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_auto_20230115_0509"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="valid_until",
            new_name="next_payment_at",
        ),
    ]
