# Generated by Django 3.2.16 on 2023-01-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_rename_valid_until_subscription_next_payment_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="valid_until",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
