# Generated by Django 3.2.16 on 2023-01-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_auto_20230123_1621"),
        ("payments", "0015_merge_20230125_0054"),
    ]

    operations = []
