# Generated by Django 3.2.18 on 2023-05-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_auto_20230502_2225"),
        ("payments", "0026_plan_invites"),
    ]

    operations = []
