# Generated by Django 3.2.21 on 2023-09-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_alter_bag_type"),
        ("payments", "0029_service_title"),
    ]

    operations = []
