# Generated by Django 3.2.21 on 2023-09-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0033_serviceitemfeature_title"),
        ("payments", "0034_cohortset_cohorts"),
    ]

    operations = []
