# Generated by Django 3.2.21 on 2023-09-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0035_merge_20230921_2255"),
        ("payments", "0035_merge_20230923_0701"),
    ]

    operations = []
