# Generated by Django 3.2.22 on 2023-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0037_auto_20231025_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
