# Generated by Django 5.0.3 on 2024-04-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0044_coupon_bag_coupons_seller_coupon_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="service_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Service set to be sold in this service and plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.serviceset",
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="selected_service_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Service set which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.serviceset",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="selected_service_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Service set which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.serviceset",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("COHORT_SET", "Cohort set"),
                    ("MENTORSHIP_SERVICE_SET", "Mentorship service set"),
                    ("EVENT_TYPE_SET", "Event type set"),
                    ("SERVICE_SET", "Service set"),
                ],
                default="COHORT_SET",
                help_text="Service type",
                max_length=22,
            ),
        ),
    ]
