# Generated by Django 5.0.7 on 2024-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0051_service_consumer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=models.CharField(help_text="Description of the payment method", max_length=480),
        ),
    ]
