# Generated by Django 5.1.6 on 2025-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0055_alter_serviceitemfeature_one_line_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfinancing",
            name="how_many_installments",
            field=models.IntegerField(
                default=0, help_text="How many installments to collect and build the plan financing"
            ),
        ),
    ]
