# Generated by Django 5.2 on 2025-04-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("payments", "0058_alter_planfinancing_status_alter_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortset",
            name="cohorts",
            field=models.ManyToManyField(
                blank=True,
                through="payments.CohortSetCohort",
                through_fields=("cohort_set", "cohort"),
                to="admissions.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="service_items",
            field=models.ManyToManyField(
                blank=True,
                through="payments.PlanServiceItem",
                through_fields=("plan", "service_item"),
                to="payments.serviceitem",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="service_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Service items to be supplied",
                through="payments.SubscriptionServiceItem",
                through_fields=("subscription", "service_item"),
                to="payments.serviceitem",
            ),
        ),
    ]
