# Generated by Django 5.2 on 2025-04-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0060_merge_20250409_0022"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingoption",
            name="pricing_ratio_exceptions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Exceptions to the general pricing ratios per country"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.currency",
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="country_code",
            field=models.CharField(
                blank=True, default="", help_text="Country code used for pricing ratio calculations", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.currency",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="country_code",
            field=models.CharField(
                blank=True, default="", help_text="Country code used for pricing ratio calculations", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.currency",
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.currency",
            ),
        ),
    ]
