# Generated by Django 5.2 on 2025-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0061_financingoption_pricing_ratio_exceptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="included_country_codes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A list of country codes that represent countries that can use this payment method, comma separated",
                max_length=255,
            ),
        ),
    ]
