# Generated by Django 5.2 on 2025-05-23 19:11

import breathecode.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfinancing",
            name="coupons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Coupons applied during the sale",
                limit_choices_to=breathecode.payments.models.limit_coupon_choices,
                to="payments.coupon",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="coupons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Coupons applied during the sale",
                limit_choices_to=breathecode.payments.models.limit_coupon_choices,
                to="payments.coupon",
            ),
        ),
    ]
