# Generated by Django 5.2 on 2025-05-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicestockscheduler",
            name="plan_handler",
        ),
        migrations.RemoveField(
            model_name="servicestockscheduler",
            name="subscription_handler",
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="last_renew_method",
            field=models.CharField(
                choices=[("TASK", "Task"), ("MANUAL", "Manual")],
                default="TASK",
                help_text="Last renew method",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="plan_financing",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan financing",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancing",
            ),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="renewed_at",
            field=models.DateTimeField(blank=True, help_text="Last renewed at", null=True),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscription",
            ),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="valid_from",
            field=models.DateTimeField(blank=True, help_text="Valid from", null=True),
        ),
        migrations.AlterField(
            model_name="servicestockscheduler",
            name="valid_until",
            field=models.DateTimeField(blank=True, db_index=True, help_text="Valid until", null=True),
        ),
    ]
