# Generated by Django 5.2 on 2025-05-16 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontact",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The Academy associated with this Stripe contact. If null, the contact is typically managed under a default/central Stripe account. This determines which Stripe account the customer belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.academy",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcontact",
            name="stripe_id",
            field=models.CharField(
                help_text="The Stripe Customer ID (e.g., cus_xxxxxxxxxxxxxx). This links the user to their record in Stripe.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymentcontact",
            name="user",
            field=models.ForeignKey(
                help_text="The Django User associated with this Stripe contact.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
