# Generated by Django 5.2 on 2025-05-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_planfinancing_coupons_subscription_coupons"),
        ("payments", "0002_remove_servicestockscheduler_plan_handler_and_more"),
    ]

    operations = []
