# Generated by Django 5.2 on 2025-05-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_planfinancing_coupons_subscription_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="plan_financing",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan financing which the consumable belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancing",
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription which the consumable belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscription",
            ),
        ),
    ]
