# Generated by Django 5.2 on 2025-06-03 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_planfinancing_coupons_subscription_coupons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="allowed_user",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this user can use this coupon",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restricted_coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
