# Generated by Django 5.2 on 2025-07-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_coupon_allowed_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="plan_financing",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="PlanFinancing that generated this consumable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancing",
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription that generated this consumable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscription",
            ),
        ),
    ]
