# Generated by Django 3.2.16 on 2022-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20221113_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='renew_every',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='renew_every_unit',
        ),
        migrations.AddField(
            model_name='fixture',
            name='renew_every',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fixture',
            name='renew_every_unit',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'),
                                            ('YEAR', 'Year')],
                                   default='MONTH',
                                   max_length=10),
        ),
    ]
