# Generated by Django 3.2.16 on 2022-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0048_academy_main_currency'),
        ('mentorship', '0016_alter_mentorshipbill_status'),
        ('payments', '0004_auto_20221113_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='mentorship_service_pattern',
        ),
        migrations.AddField(
            model_name='fixture',
            name='cohorts',
            field=models.ManyToManyField(to='admissions.Cohort'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='mentorship_services',
            field=models.ManyToManyField(to='mentorship.MentorshipService'),
        ),
    ]
