# Generated by Django 3.2.16 on 2022-11-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20221115_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
