# Generated by Django 5.2 on 2025-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_coupon_referred_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="is_backed",
            field=models.BooleanField(
                default=False,
                help_text="if this payment method is backed by real life transaction, usually backed payments are considered real income",
            ),
        ),
    ]
