# Generated by Django 3.2.16 on 2022-11-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_invoice_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='renew_every',
            new_name='pay_every',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='renew_every_unit',
            new_name='pay_every_unit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cohorts',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_auto_renew',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_cancellable',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_renew',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='renew_credits_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='renew_every',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='renew_every_unit',
        ),
        migrations.AddField(
            model_name='service',
            name='trial_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='trial_duration_unit',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'),
                                            ('YEAR', 'Year')],
                                   default='MONTH',
                                   max_length=10),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='is_renewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='renew_at',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='renew_at_unit',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'),
                                            ('YEAR', 'Year')],
                                   default='MONTH',
                                   max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'),
                                            ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted'),
                                            ('DISCONTINUED', 'Discontinued')],
                                   default='DRAFT',
                                   max_length=12),
        ),
        migrations.CreateModel(
            name='ServiceStockScheduler',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('last_renew', models.DateTimeField(default=None, null=True)),
                ('is_belongs_to_plan', models.BooleanField(default=False)),
                ('consumables', models.ManyToManyField(to='payments.Consumable')),
                ('service_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.serviceitem')),
                ('subscription',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscription')),
            ],
        ),
    ]
