# Generated by Django 5.2 on 2025-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_paymentmethod_is_backed"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="title",
            field=models.CharField(
                blank=True, help_text="Plan title, used on checkout process", max_length=100, null=True
            ),
        ),
    ]
