# Generated by Django 3.2.16 on 2022-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20221129_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status_message',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='status',
            field=models.CharField(choices=[('RENEWAL', 'Renewal'), ('CHECKING', 'Checking'),
                                            ('PAID', 'Paid')],
                                   default='CHECKING',
                                   max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free trial'), ('ACTIVE', 'Active'),
                                            ('CANCELLED', 'Cancelled'), ('DEPRECATED', 'Deprecated'),
                                            ('PAYMENT_ISSUE', 'Payment issue'), ('ERROR', 'Error')],
                                   default='ACTIVE',
                                   max_length=13),
        ),
    ]
