# Generated by Django 5.2 on 2025-08-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_plan_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="deprecated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this payment method is deprecated and cannot be used for new purchases",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("INTERNAL", "Internal"), ("HIDDEN", "Hidden")],
                db_index=True,
                default="PUBLIC",
                help_text="Visibility level of the payment method",
                max_length=10,
            ),
        ),
    ]
