# Generated by Django 5.2 on 2025-09-08 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_cohort_shortcuts"),
        ("payments", "0008_paymentmethod_deprecated_paymentmethod_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Team name", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Academy context",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Team owner", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "name", "academy")},
            },
        ),
        migrations.CreateModel(
            name="BillingTeamMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_admin", models.BooleanField(default=False, help_text="Team admin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team", on_delete=django.db.models.deletion.CASCADE, to="payments.billingteam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Member user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "user")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionSeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "seats",
                    models.PositiveIntegerField(default=1, help_text="Number of seats assigned to the user (>= 1)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_item",
                    models.ForeignKey(
                        help_text="Seat service item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.serviceitem",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Assigned user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "service_item", "user"), name="uniq_subscription_seat_per_user"
                    )
                ],
            },
        ),
    ]
