# Generated by Django 5.2 on 2025-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_paymentmethod_deprecated_paymentmethod_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="name",
            field=models.CharField(help_text="Company name or person name", max_length=50),
        ),
    ]
