# Generated by Django 3.2.16 on 2022-12-31 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0048_academy_main_currency"),
        ("mentorship", "0017_auto_20221130_0504"),
        ("payments", "0008_auto_20221230_1044"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipServiceSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                ("mentorship_services", models.ManyToManyField(blank=True, to="mentorship.MentorshipService")),
            ],
        ),
        migrations.RemoveField(
            model_name="plan",
            name="schedulers",
        ),
        migrations.AddField(
            model_name="planserviceitem",
            name="cohort_pattern",
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="planserviceitem",
            name="cohorts",
            field=models.ManyToManyField(blank=True, to="admissions.Cohort"),
        ),
        migrations.DeleteModel(
            name="PaymentServiceScheduler",
        ),
        migrations.AddField(
            model_name="planserviceitem",
            name="mentorship_service_set",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="payments.mentorshipserviceset"
            ),
        ),
    ]
