# Generated by Django 5.2 on 2025-09-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0003_userinvite_course"),
        ("payments", "0009_billingteam_billingteammembership_subscriptionseat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionSeatInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "seats",
                    models.PositiveIntegerField(default=1, help_text="Number of seats to grant upon acceptance (>= 1)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invite",
                    models.ForeignKey(
                        help_text="User invite",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.userinvite",
                    ),
                ),
                (
                    "service_item",
                    models.ForeignKey(
                        help_text="Seat service item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.serviceitem",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.subscription",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "service_item", "invite"), name="uniq_subscription_seat_invite"
                    )
                ],
            },
        ),
    ]
