# Generated by Django 5.2 on 2025-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_seller_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="exclude_from_referral_program",
            field=models.BooleanField(default=True, help_text="If is true, referral coupons will not be allowed"),
        ),
    ]
