# Generated by Django 5.2 on 2025-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_bag_seat_service_item_plan_consumption_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_refunded",
            field=models.FloatField(
                default=0, help_text="Amount refunded, this field will only be set when the invoice is refunded"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="exclude_from_referral_program",
            field=models.BooleanField(default=True, help_text="If is true, referral coupons will not be allowed"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="name",
            field=models.CharField(help_text="Company name or person name", max_length=50),
        ),
    ]
