# Generated by Django 5.2 on 2025-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_bag_seat_service_item_plan_consumption_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_refunded",
            field=models.FloatField(
                default=0, help_text="Amount refunded, this field will only be set when the invoice is refunded"
            ),
        ),
    ]
