# Generated by Django 5.2 on 2025-09-08 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_subscriptionseatinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingteammembership",
            name="email",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="billingteammembership",
            name="seat_consumable",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Consumable issued for this team member seat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.consumable",
            ),
        ),
        migrations.AddField(
            model_name="billingteammembership",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="billingteammembership",
            index=models.Index(fields=["status"], name="payments_bi_status_b7cf3d_idx"),
        ),
        migrations.AddIndex(
            model_name="billingteammembership",
            index=models.Index(fields=["email"], name="payments_bi_email_a80f73_idx"),
        ),
        migrations.AddIndex(
            model_name="billingteammembership",
            index=models.Index(fields=["user"], name="payments_bi_user_id_07540d_idx"),
        ),
        migrations.AddConstraint(
            model_name="billingteammembership",
            constraint=models.UniqueConstraint(
                fields=("seat_consumable", "email"), name="uniq_btm_seat_consumable_email"
            ),
        ),
    ]
