# Generated by Django 5.2 on 2025-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_invoice_amount_refunded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="exclude_from_referral_program",
            field=models.BooleanField(default=True, help_text="If is true, referral coupons will not be allowed"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="name",
            field=models.CharField(help_text="Company name or person name", max_length=50),
        ),
    ]
