# Generated by Django 5.2 on 2025-10-02 16:40
#
# Duplicate of 0010 (Plan.exclude_from_referral_program + Seller.name).
# Kept as a no-op so 0012 can keep depending on this node.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_invoice_amount_refunded_and_more"),
    ]

    operations = []
