# Generated by Django 5.2 on 2025-10-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_plan_exclude_from_referral_program_and_seller_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionseat",
            name="seat_multiplier",
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription_billing_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription billing team",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscriptionbillingteam",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription seat",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscriptionseat",
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="auto_recharge_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable automatic consumable recharge when balance runs low"
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="max_period_spend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Maximum spending per monthly period (null = unlimited)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="recharge_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Amount to recharge when threshold is reached (in subscription currency)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="recharge_threshold_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Balance threshold to trigger auto-recharge (in subscription currency)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_recharge_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable automatic consumable recharge when balance runs low"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_period_spend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Maximum spending per monthly period (null = unlimited)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="recharge_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Amount to recharge when threshold is reached (in subscription currency)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="recharge_threshold_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Balance threshold to trigger auto-recharge (in subscription currency)",
                max_digits=10,
            ),
        ),
    ]
