# Generated by Django 5.2 on 2025-09-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_billingteammembership_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="is_team_allowed",
            field=models.BooleanField(db_index=True, default=False, help_text="Allow team seats for this item"),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="max_team_members",
            field=models.IntegerField(default=-1, help_text="Max team members allowed (-1 = unlimited)"),
        ),
    ]
