# Generated by Django 3.2.16 on 2023-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20230115_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
