# Generated by Django 5.2 on 2025-10-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_populate_academy_owner"),
        ("payments", "0012_remove_subscriptionseat_seat_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingoption",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Academy that owns this financing option",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.academy",
            ),
        ),
    ]
