# Generated by Django 5.2 on 2025-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_remove_subscriptionseat_seat_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academypaymentsettings",
            name="coinbase_api_key",
            field=models.CharField(blank=True, help_text="API key for Coinbase Commerce", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="academypaymentsettings",
            name="coinbase_webhook_secret",
            field=models.CharField(
                blank=True, help_text="Webhook secret for Coinbase Commerce", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="academypaymentsettings",
            name="pos_vendor",
            field=models.CharField(
                choices=[("STRIPE", "Stripe"), ("COINBASE", "Coinbase Commerce")],
                default="STRIPE",
                help_text="Point of Sale vendor like Stripe, etc.",
                max_length=20,
            ),
        ),
    ]
