# Generated by Django 5.2 on 2025-10-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_remove_subscriptionseat_seat_multiplier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionbillingteam",
            old_name="seats_limit",
            new_name="additional_seats",
        ),
    ]
