# Generated by Django 5.2 on 2025-09-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("payments", "0012_serviceitem_is_team_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="team_member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Team member associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.billingteammembership",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="team_consumables",
            field=models.JSONField(blank=True, default=dict, help_text="Team consumables policy JSON"),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="team_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Required auth group for team members of this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
            ),
        ),
    ]
