# Generated by Django 5.2 on 2025-09-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_consumable_team_member_serviceitem_team_consumables_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="seat_add_on_service",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Optional AcademyService used as seat add-on for per-seat purchases",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seat_add_on_of_plans",
                to="payments.academyservice",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="supports_teams",
            field=models.BooleanField(
                db_index=True, default=False, editable=False, help_text="Derived: plan supports team features"
            ),
        ),
    ]
