# Generated by Django 5.2 on 2025-10-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_rename_subscriptionbillingteam_seats_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionbillingteam",
            name="additional_seats",
            field=models.PositiveIntegerField(
                default=0, help_text="Additional seats for this team excluding the owner seat"
            ),
        ),
    ]
