# Generated by Django 5.2 on 2025-10-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_academypaymentsettings_coinbase_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="is_coinbase",
            field=models.BooleanField(default=False),
        ),
    ]
