# Generated by Django 5.2 on 2025-10-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_populate_academy_owner"),
        ("payments", "0013_add_academy_to_financing_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academyservice",
            name="service",
            field=models.ForeignKey(
                help_text="Service", on_delete=django.db.models.deletion.CASCADE, to="payments.service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academyservice",
            unique_together={("academy", "service")},
        ),
    ]
