# Generated by Django 3.2.16 on 2023-01-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_currency_decimals"),
        ("payments", "0013_merge_0012_auto_20230115_0509_0012_auto_20230117_2124"),
    ]

    operations = []
