# Generated by Django 5.2 on 2025-10-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_paymentmethod_is_coinbase"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="coinbase_charge_id",
            field=models.CharField(blank=True, default=None, help_text="Coinbase charge id", max_length=40, null=True),
        ),
    ]
