# Generated by Django 3.2.16 on 2023-01-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_merge_20230120_2311"),
        ("payments", "0014_subscription_valid_until"),
    ]

    operations = []
