# Generated by Django 5.2 on 2025-09-09 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_plan_seat_add_on_service_plan_supports_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscriptionseat",
            name="uniq_subscription_seat_per_user",
        ),
        migrations.RemoveField(
            model_name="subscriptionseat",
            name="service_item",
        ),
        migrations.AlterField(
            model_name="subscriptionseat",
            name="seats",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of seats assigned to the user (>= 1), it multiplies the capacity of the service item",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionseat",
            constraint=models.UniqueConstraint(fields=("subscription", "user"), name="uniq_subscription_seat_per_user"),
        ),
    ]
