# Generated by Django 5.2 on 2025-10-27 22:45

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_alter_syllabusversion_json"),
        ("payments", "0014_alter_subscriptionbillingteam_additional_seats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academypaymentsettings",
            name="coinbase_api_key",
            field=models.CharField(blank=True, help_text="API key for Coinbase Commerce", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="academypaymentsettings",
            name="coinbase_webhook_secret",
            field=models.CharField(
                blank=True, help_text="Webhook secret for Coinbase Commerce", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="academypaymentsettings",
            name="early_renewal_window_days",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Days before expiration when early renewal is allowed, 0 means it is not allowed",
                validators=[django.core.validators.MaxValueValidator(14)],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="coinbase_charge_id",
            field=models.CharField(blank=True, default=None, help_text="Coinbase charge id", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="is_coinbase",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="academypaymentsettings",
            name="pos_vendor",
            field=models.CharField(
                choices=[("STRIPE", "Stripe"), ("COINBASE", "Coinbase Commerce")],
                default="STRIPE",
                help_text="Point of Sale vendor like Stripe, etc.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the payment method is different than credit card this will be set to true"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the payment method is different than credit card this will be set to true"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coinbase_charge_id__isnull", False)),
                fields=("coinbase_charge_id",),
                name="unique_coinbase_charge_id",
            ),
        ),
    ]
