# Generated by Django 3.2.16 on 2023-01-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_merge_20230120_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_unit',
            field=models.CharField(blank=True,
                                   choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'),
                                            ('YEAR', 'Year')],
                                   default='MONTH',
                                   max_length=10,
                                   null=True),
        ),
    ]
