# Generated by Django 5.2 on 2025-10-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_subscriptionbillingteam_additional_seats"),
        ("payments", "0015_add_pricing_hash_to_financing_option"),
    ]

    operations = []
