# Generated by Django 5.2 on 2025-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_remove_subscriptionseat_uniq_subscription_seat_per_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionseat",
            name="seats",
        ),
        migrations.AddField(
            model_name="subscriptionseat",
            name="seat_multiplier",
            field=models.PositiveIntegerField(
                default=1, help_text="Multiplier applied to per-member consumables issuance (>= 1)"
            ),
        ),
    ]
