# Generated by Django 5.2 on 2025-10-23 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_invoice_coinbase_charge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="academypaymentsettings",
            name="early_renewal_window_days",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Days before expiration when manual renewal is allowed ",
                validators=[django.core.validators.MaxValueValidator(14)],
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the payment method is different than credit card this will be set to true"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the payment method is different than credit card this will be set to true"
            ),
        ),
    ]
