# Generated by Django 3.2.16 on 2023-01-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_merge_20230121_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planfinancing',
            old_name='paid_at',
            new_name='next_payment_at',
        ),
        migrations.RenameField(
            model_name='planfinancing',
            old_name='pay_until',
            new_name='valid_until',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_unit',
            field=models.CharField(blank=True,
                                   choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'),
                                            ('YEAR', 'Year')],
                                   default='MONTH',
                                   max_length=10,
                                   null=True),
        ),
    ]
