# Generated by Django 3.2.16 on 2023-01-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_subscription_valid_until'),
        ('payments', '0015_auto_20230121_0513'),
    ]

    operations = []
