# Generated by Django 5.2 on 2025-10-26 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_alter_syllabusversion_json"),
        ("payments", "0016_academypaymentsettings_early_renewal_window_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coinbase_charge_id__isnull", False)),
                fields=("coinbase_charge_id",),
                name="unique_coinbase_charge_id",
            ),
        ),
    ]
