# Generated by Django 5.2 on 2025-09-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_remove_subscriptionseat_seats_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="seats_log",
            field=models.JSONField(blank=True, default=list, help_text="Audit log of seat changes"),
        ),
        migrations.AddField(
            model_name="subscriptionseat",
            name="email",
            field=models.CharField(
                db_index=True, default="", help_text="Email of the member (normalized)", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="subscriptionseat",
            name="seat_log",
            field=models.JSONField(blank=True, default=list, help_text="Audit log of seat changes for this seat"),
        ),
        migrations.AlterField(
            model_name="subscriptionseat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Assigned user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionseat",
            constraint=models.UniqueConstraint(
                fields=("subscription", "email"), name="uniq_subscription_seat_per_email"
            ),
        ),
    ]
