# Generated by Django 3.2.16 on 2023-01-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_merge_20230123_2138"),
        ("payments", "0016_merge_20230125_2040"),
    ]

    operations = []
