# Generated by Django 3.2.16 on 2023-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_merge_20230126_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionsession",
            name="related_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
