# Generated by Django 5.2 on 2025-11-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_academypaymentsettings_coinbase_api_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="is_coinbase",
            new_name="is_crypto",
        ),
    ]
