# Generated by Django 5.2 on 2025-09-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_subscription_seats_log_subscriptionseat_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubscriptionSeatInvite",
        ),
    ]
