# Generated by Django 3.2.16 on 2023-02-14 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0040_alter_venue_zip_code"),
        ("admissions", "0053_alter_cohort_kickoff_date"),
        ("payments", "0018_alter_consumptionsession_related_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planfinancing",
            old_name="paid_at",
            new_name="next_payment_at",
        ),
        migrations.RenameField(
            model_name="planfinancing",
            old_name="pay_until",
            new_name="valid_until",
        ),
        migrations.RenameField(
            model_name="servicestockscheduler",
            old_name="last_renew",
            new_name="valid_until",
        ),
        migrations.AddField(
            model_name="invoice",
            name="refund_stripe_id",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="refunded_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="time_of_life",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="time_of_life_unit",
            field=models.CharField(
                blank=True,
                choices=[("DAY", "Day"), ("WEEK", "Week"), ("MONTH", "Month"), ("YEAR", "Year")],
                default="MONTH",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="monthly_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="plan_expires_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionserviceitem",
            name="cohorts",
            field=models.ManyToManyField(blank=True, to="admissions.Cohort"),
        ),
        migrations.AddField(
            model_name="subscriptionserviceitem",
            name="mentorship_service_set",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="payments.mentorshipserviceset"
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="chosen_period",
            field=models.CharField(
                choices=[
                    ("NO_SET", "No set"),
                    ("MONTH", "Month"),
                    ("QUARTER", "Quarter"),
                    ("HALF", "Half"),
                    ("YEAR", "Year"),
                ],
                default="NO_SET",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="type",
            field=models.CharField(
                choices=[("BAG", "Bag"), ("CHARGE", "Charge"), ("PREVIEW", "Preview")], default="BAG", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="event_type",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="events.eventtype"
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE_TRIAL", "Free trial"),
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPRECATED", "Deprecated"),
                    ("PAYMENT_ISSUE", "Payment issue"),
                    ("ERROR", "Error"),
                    ("FULLY_PAID", "Fully Paid"),
                ],
                default="ACTIVE",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="status_message",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE_TRIAL", "Free trial"),
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPRECATED", "Deprecated"),
                    ("PAYMENT_ISSUE", "Payment issue"),
                    ("ERROR", "Error"),
                    ("FULLY_PAID", "Fully Paid"),
                ],
                default="ACTIVE",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status_message",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
