# Generated by Django 5.2 on 2025-09-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0005_alter_userinvite_team_member"),
        ("payments", "0018_delete_subscriptionseatinvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingteammembership",
            name="team",
        ),
        migrations.AlterUniqueTogether(
            name="billingteammembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="billingteammembership",
            name="seat_consumable",
        ),
        migrations.RemoveField(
            model_name="billingteammembership",
            name="user",
        ),
        migrations.AlterField(
            model_name="consumable",
            name="team_member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Team member associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionseat",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionBillingTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Team name", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        help_text="Subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.subscription",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BillingTeam",
        ),
        migrations.DeleteModel(
            name="BillingTeamMembership",
        ),
    ]
