# Generated by Django 5.2 on 2025-11-07 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_rename_is_coinbase_paymentmethod_is_crypto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFinancingSeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.CharField(
                        db_index=True, default="", help_text="Email of the member (normalized)", max_length=150
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="if true, this user is able to access the plan financing"
                    ),
                ),
                (
                    "seat_log",
                    models.JSONField(blank=True, default=list, help_text="Audit log of seat changes for this seat"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Assigned user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consumable",
            name="plan_financing_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Plan financing seat associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.planfinancingseat",
            ),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="plan_financing_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Plan financing seat",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancingseat",
            ),
        ),
        migrations.CreateModel(
            name="PlanFinancingTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Team name", max_length=80)),
                (
                    "seats_log",
                    models.JSONField(
                        blank=True, default=list, help_text="Audit log of seat changes for this financing team"
                    ),
                ),
                (
                    "additional_seats",
                    models.PositiveIntegerField(
                        default=0, help_text="Additional seats for this team excluding the owner seat"
                    ),
                ),
                (
                    "consumption_strategy",
                    models.CharField(
                        choices=[("PER_TEAM", "Per team"), ("PER_SEAT", "Per seat")],
                        default="PER_SEAT",
                        help_text="Consumption strategy",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financing",
                    models.OneToOneField(
                        help_text="Plan financing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="payments.planfinancing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planfinancingseat",
            name="team",
            field=models.ForeignKey(
                help_text="Plan financing team",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="payments.planfinancingteam",
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="plan_financing_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Plan financing team associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancingteam",
            ),
        ),
        migrations.AddField(
            model_name="servicestockscheduler",
            name="plan_financing_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Plan financing team",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.planfinancingteam",
            ),
        ),
        migrations.AddConstraint(
            model_name="planfinancingseat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("team", "user"),
                name="uniq_plan_financing_seat_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="planfinancingseat",
            constraint=models.UniqueConstraint(fields=("team", "email"), name="uniq_plan_financing_seat_per_email"),
        ),
    ]
