# Generated by Django 5.2 on 2025-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_planfinancingseat_consumable_plan_financing_seat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academypaymentsettings",
            old_name="pos_api_key",
            new_name="stripe_api_key",
        ),
        migrations.RemoveField(
            model_name="academypaymentsettings",
            name="pos_vendor",
        ),
        migrations.AddField(
            model_name="academypaymentsettings",
            name="stripe_publishable_key",
            field=models.CharField(blank=True, help_text="Publishable key for Stripe", max_length=255),
        ),
        migrations.AddField(
            model_name="academypaymentsettings",
            name="stripe_webhook_secret",
            field=models.CharField(blank=True, help_text="Webhook secret for Stripe", max_length=255),
        ),
    ]
