# Generated by Django 5.2 on 2025-09-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_remove_billingteammembership_team_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="seats_log",
        ),
        migrations.AddField(
            model_name="subscription",
            name="supports_billing_team",
            field=models.BooleanField(
                db_index=True, default=False, help_text="If true, this subscription has a billing team"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionbillingteam",
            name="seats_log",
            field=models.JSONField(
                blank=True, default=list, help_text="Audit log of seat changes for this billing team"
            ),
        ),
    ]
