# Generated by Django 5.2 on 2025-11-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_rename_pos_api_key_academypaymentsettings_stripe_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academypaymentsettings",
            name="pos_webhook_secret",
        ),
        migrations.RemoveField(
            model_name="academypaymentsettings",
            name="pos_publishable_key",
        ),
    ]
