# Generated by Django 5.2 on 2025-11-12 17:54

from django.db import migrations


def drop_pos_webhook_secret(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("ALTER TABLE payments_academypaymentsettings DROP COLUMN IF EXISTS pos_webhook_secret;")


def drop_pos_publishable_key(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("ALTER TABLE payments_academypaymentsettings DROP COLUMN IF EXISTS pos_publishable_key;")


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_rename_pos_api_key_academypaymentsettings_stripe_api_key_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_pos_webhook_secret, migrations.RunPython.noop),
        migrations.RunPython(drop_pos_publishable_key, migrations.RunPython.noop),
    ]
