# Generated by Django 5.2 on 2025-09-11 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_remove_subscription_seats_log_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscriptionseat",
            name="uniq_subscription_seat_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="subscriptionseat",
            name="uniq_subscription_seat_per_email",
        ),
        migrations.RemoveField(
            model_name="consumable",
            name="team_member",
        ),
        migrations.RemoveField(
            model_name="subscriptionseat",
            name="subscription",
        ),
        migrations.AddField(
            model_name="consumable",
            name="subscription_billing_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription billing team associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionbillingteam",
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="subscription_seat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription seat associated to this consumable (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionseat",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="consumption_strategy",
            field=models.CharField(
                choices=[("PER_TEAM", "Per team"), ("PER_SEAT", "Per seat"), ("BOTH", "Both")],
                default="PER_SEAT",
                help_text="Consumption strategy",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionbillingteam",
            name="consumption_strategy",
            field=models.CharField(
                choices=[("PER_TEAM", "Per team"), ("PER_SEAT", "Per seat")],
                default="PER_SEAT",
                help_text="Consumption strategy",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionbillingteam",
            name="seats_limit",
            field=models.PositiveIntegerField(default=1, help_text="Limit of seats for this team"),
        ),
        migrations.AddField(
            model_name="subscriptionseat",
            name="billing_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Subscription billing team",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscriptionbillingteam",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionseat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("billing_team", "user"),
                name="uniq_subscription_seat_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionseat",
            constraint=models.UniqueConstraint(
                fields=("billing_team", "email"), name="uniq_subscription_seat_per_email"
            ),
        ),
    ]
