# Generated by Django 5.2 on 2025-11-12 17:54

from django.db import migrations


def drop_old_pos_fields_if_supported(apps, schema_editor):
    """
    Drop legacy POS fields if supported by the database engine.

    Tests run with SQLite in-memory; SQLite doesn't support `DROP COLUMN IF EXISTS`,
    so we skip on non-PostgreSQL engines.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE payments_academypaymentsettings DROP COLUMN IF EXISTS pos_webhook_secret;")
        cursor.execute("ALTER TABLE payments_academypaymentsettings DROP COLUMN IF EXISTS pos_publishable_key;")


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_rename_pos_api_key_academypaymentsettings_stripe_api_key_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_old_pos_fields_if_supported, migrations.RunPython.noop),
    ]
