# Generated by Django 5.2 on 2025-11-13 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0010_alter_syllabusversion_status"),
        ("payments", "0021_remove_old_pos_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="planoffer",
            name="live_cohorts_syllabus",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, highlight the syllabus that includes live classes relevant to this offer. ",
                to="admissions.syllabus",
            ),
        ),
        migrations.AlterField(
            model_name="planoffer",
            name="suggested_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Suggested plans",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_offer_to",
                to="payments.plan",
            ),
        ),
    ]
