# Generated by Django 5.2 on 2025-11-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_planoffer_live_cohorts_syllabus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="plan_financing",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, purchasing an add-on with this service item will build the linked plan financing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_items_creating_financing",
                to="payments.plan",
            ),
        ),
    ]
