# Generated by Django 3.2.16 on 2023-03-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_auto_20230308_0703"),
        ("payments", "0023_plan_has_waiting_list"),
    ]

    operations = []
