# Generated by Django 5.2 on 2025-11-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_serviceitem_plan_financing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceitem",
            name="plan_financing",
        ),
    ]
