# Generated by Django 5.2 on 2025-11-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_remove_serviceitem_plan_financing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planoffer",
            name="live_cohorts_syllabus",
        ),
    ]
