# Generated by Django 5.2 on 2025-11-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_remove_planoffer_live_cohorts_syllabus"),
    ]

    operations = [
        migrations.AddField(
            model_name="bag",
            name="plan_addons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Addon plans associated to this bag",
                related_name="bags_as_addon",
                to="payments.plan",
            ),
        ),
        migrations.AddField(
            model_name="bag",
            name="plan_addons_amount",
            field=models.FloatField(
                default=0, help_text="One-shot amount to be charged for all plan addons in this bag"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_addons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Addon plans that can be attached to this main plan",
                related_name="parent_plans",
                to="payments.plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_onboarding",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If the plan is tagged for onboarding, the front end will include it in the plans that are meant to be used as first payment plans for users; other plans focus on upsell or cross-sell so they can be ignored by first-time users",
            ),
        ),
    ]
