# Generated by Django 5.2 on 2025-11-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_bag_plan_addons_bag_plan_addons_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_breakdown",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Breakdown of how the invoice amount is divided across plans, plan addons, and service items",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("FULFILLED", "Fulfilled"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                    ("PARTIALLY_REFUNDED", "Partially refunded"),
                    ("REFUNDED", "Refunded"),
                    ("DISPUTED_AS_FRAUD", "Disputed as fraud"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Invoice status",
                max_length=18,
            ),
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField(help_text="Credit note amount")),
                ("reason", models.TextField(help_text="Reason for credit note")),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date when the credit note was issued"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("CANCELLED", "Cancelled")],
                        db_index=True,
                        default="DRAFT",
                        help_text="Credit note status",
                        max_length=10,
                    ),
                ),
                (
                    "legal_text",
                    models.TextField(blank=True, help_text="Country-specific legal text for refunds", null=True),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, help_text="Country code for legal compliance", max_length=2, null=True
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="Breakdown of what is being refunded (main_plan, service_items, plan_addons)",
                        null=True,
                    ),
                ),
                (
                    "refund_stripe_id",
                    models.CharField(
                        blank=True, default=None, help_text="Stripe refund id if applicable", max_length=32, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency of the credit note",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.currency",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Original invoice being refunded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="payments.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "payments_credit_note",
                "ordering": ["-created_at"],
            },
        ),
    ]
