# Generated by Django 5.2 on 2025-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_bag_plan_addons_bag_plan_addons_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_breakdown",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Breakdown of how the invoice amount is divided across plans, plan addons, and service items",
                null=True,
            ),
        ),
    ]
