# Generated by Django 5.2 on 2025-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_invoice_amount_breakdown_alter_invoice_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount_breakdown",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Breakdown of how the invoice amount is divided across plans, plan addons, and service items",
                null=True,
            ),
        ),
    ]
