# Generated by Django 3.2.16 on 2023-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_merge_0026_auto_20230502_2225_0026_plan_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_per_half',
            field=models.FloatField(
                blank=True,
                default=None,
                help_text='If it is not a subscription, then the value fo these fields should be 0',
                null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_per_month',
            field=models.FloatField(
                blank=True,
                default=None,
                help_text='If it is not a subscription, then the value fo these fields should be 0',
                null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_per_quarter',
            field=models.FloatField(
                blank=True,
                default=None,
                help_text='If it is not a subscription, then the value fo these fields should be 0',
                null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_per_year',
            field=models.FloatField(
                blank=True,
                default=None,
                help_text='If it is not a subscription, then the value fo these fields should be 0',
                null=True),
        ),
    ]
