# Generated by Django 5.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_alter_invoice_status_creditnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_model_service",
            field=models.BooleanField(
                default=False,
                help_text="If true, this service will be considered a model service and will be suggested to all academies at setup time"
            ),
        ),
    ]
