# Generated by Django 3.2.20 on 2023-09-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_auto_20230607_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
