# Generated by Django 3.2.21 on 2023-09-12 05:55

import breathecode.utils.validators.language
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0060_alter_cohortuser_educational_status"),
        ("payments", "0029_alter_bag_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        help_text="A human-readable identifier, it must be unique and it can only contain letters, numbers and hyphens",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                ("cohorts", models.ManyToManyField(blank=True, to="admissions.Cohort")),
            ],
        ),
        migrations.RemoveField(
            model_name="bag",
            name="selected_cohorts",
        ),
        migrations.RemoveField(
            model_name="bag",
            name="selected_event_type_sets",
        ),
        migrations.RemoveField(
            model_name="bag",
            name="selected_mentorship_service_sets",
        ),
        migrations.RemoveField(
            model_name="consumable",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="available_cohorts",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="cohort_pattern",
        ),
        migrations.RemoveField(
            model_name="planfinancing",
            name="selected_cohort",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="selected_cohort",
        ),
        migrations.AlterField(
            model_name="plan",
            name="event_type_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Event type set to be sold in this service and plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.eventtypeset",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="mentorship_service_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Mentorship service set to be sold in this service and plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.mentorshipserviceset",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("COHORT_SET", "Cohort set"),
                    ("MENTORSHIP_SERVICE_SET", "Mentorship service set"),
                    ("EVENT_TYPE_SET", "Event type set"),
                ],
                default="COHORT_SET",
                help_text="Service type",
                max_length=22,
            ),
        ),
        migrations.CreateModel(
            name="CohortSetTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "lang",
                    models.CharField(
                        help_text="ISO 639-1 language code + ISO 3166-1 alpha-2 country code, e.g. en-US",
                        max_length=5,
                        validators=[breathecode.utils.validators.language.validate_language_code],
                    ),
                ),
                ("title", models.CharField(help_text="Title of the cohort set", max_length=60)),
                ("description", models.CharField(help_text="Description of the cohort set", max_length=255)),
                (
                    "short_description",
                    models.CharField(help_text="Short description of the cohort set", max_length=255),
                ),
                (
                    "cohort_set",
                    models.ForeignKey(
                        help_text="Cohort set", on_delete=django.db.models.deletion.CASCADE, to="payments.cohortset"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consumable",
            name="cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort which the consumable belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.cohortset",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort sets to be sold in this service and plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.cohortset",
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="selected_cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.cohortset",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="selected_cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.cohortset",
            ),
        ),
    ]
