# Generated by Django 5.2 on 2026-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0030_add_feature_flags_and_coupon_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(
                blank=True, default=None, help_text="Description of the service", max_length=255, null=True
            ),
        ),
    ]
