# Generated by Django 3.2.21 on 2023-09-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0061_academy_white_label_url"),
        ("payments", "0031_merge_20230912_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfinancing",
            name="joined_cohorts",
            field=models.ManyToManyField(
                blank=True, help_text="Cohorts those that he/she joined", to="admissions.Cohort"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="joined_cohorts",
            field=models.ManyToManyField(
                blank=True, help_text="Cohorts those that he/she joined", to="admissions.Cohort"
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="status",
            field=models.CharField(
                choices=[("RENEWAL", "Renewal"), ("CHECKING", "Checking"), ("PAID", "Paid")],
                db_index=True,
                default="CHECKING",
                help_text="Bag status",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="unit_type",
            field=models.CharField(
                choices=[("UNIT", "Unit")],
                db_index=True,
                default="UNIT",
                help_text="Unit type (e.g. UNIT))",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                db_index=True, help_text="ISO 4217 currency code (e.g. USD, EUR, MXN)", max_length=3, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("FULFILLED", "Fulfilled"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                    ("REFUNDED", "Refunded"),
                    ("DISPUTED_AS_FRAUD", "Disputed as fraud"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Invoice status",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_onboarding",
            field=models.BooleanField(db_index=True, default=False, help_text="Is onboarding plan?"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="A human-readable identifier, it must be unique and it can only contain letters, numbers and hyphens",
                max_length=60,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="selected_cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort set which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.cohortset",
            ),
        ),
        migrations.AlterField(
            model_name="planfinancing",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE_TRIAL", "Free trial"),
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPRECATED", "Deprecated"),
                    ("PAYMENT_ISSUE", "Payment issue"),
                    ("ERROR", "Error"),
                    ("FULLY_PAID", "Fully Paid"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Status",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="private",
            field=models.BooleanField(db_index=True, default=True, help_text="If the asset is private or not"),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="A human-readable identifier, it must be unique and it can only contain letters, numbers and hyphens",
                max_length=60,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="unit_type",
            field=models.CharField(
                choices=[("UNIT", "Unit")],
                db_index=True,
                default="UNIT",
                help_text="Unit type (e.g. UNIT))",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="selected_cohort_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Cohort set which the plans and services is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.cohortset",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE_TRIAL", "Free trial"),
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPRECATED", "Deprecated"),
                    ("PAYMENT_ISSUE", "Payment issue"),
                    ("ERROR", "Error"),
                    ("FULLY_PAID", "Fully Paid"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Status",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="valid_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Valid until, after this date the subscription will be destroyed",
                null=True,
            ),
        ),
    ]
