# Generated by Django 5.2 on 2026-02-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0031_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="standalone_invoice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Invoice that generated this consumable when it was bought or granted standalone (e.g. user consumable checkout or staff grant). Null for consumables created from subscription or plan renewal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="standalone_consumables",
                to="payments.invoice",
            ),
        ),
    ]
