# Generated by Django 5.2 on 2026-03-25 18:24

from django.db import migrations, models

VPS_SERVER = "VPS_SERVER"
NO_SET = "NO_SET"


def set_vps_server_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="vps_server").update(consumer=VPS_SERVER)


def unset_vps_server_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="vps_server", consumer=VPS_SERVER).update(consumer=NO_SET)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0032_consumable_standalone_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="consumer",
            field=models.CharField(
                choices=[
                    ("ADD_CODE_REVIEW", "Add code review"),
                    ("LIVE_CLASS_JOIN", "Live class join"),
                    ("EVENT_JOIN", "Event join"),
                    ("JOIN_MENTORSHIP", "Join mentorship"),
                    ("READ_LESSON", "Read lesson"),
                    ("AI_INTERACTION", "AI Interaction"),
                    ("VPS_SERVER", "VPS server"),
                    ("NO_SET", "No set"),
                ],
                default="NO_SET",
                help_text="Several services can consume the same way; choosing a consumer is considered a good practice to avoid service mismatch behaviors.",
                max_length=15,
            ),
        ),
        migrations.RunPython(set_vps_server_consumer, unset_vps_server_consumer),
    ]
