# Generated by Django 5.2 on 2026-03-25 18:26

from django.db import migrations, models

MONTHLY_LLM_BUDGET = "MONTHLY_LLM_BUDGET"
NO_SET = "NO_SET"


def set_monthly_llm_budget_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="monthly_llm_budget").update(consumer=MONTHLY_LLM_BUDGET)


def unset_monthly_llm_budget_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="monthly_llm_budget", consumer=MONTHLY_LLM_BUDGET).update(consumer=NO_SET)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0033_service_consumer_vps_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="consumer",
            field=models.CharField(
                choices=[
                    ("ADD_CODE_REVIEW", "Add code review"),
                    ("LIVE_CLASS_JOIN", "Live class join"),
                    ("EVENT_JOIN", "Event join"),
                    ("JOIN_MENTORSHIP", "Join mentorship"),
                    ("READ_LESSON", "Read lesson"),
                    ("AI_INTERACTION", "AI Interaction"),
                    ("VPS_SERVER", "VPS server"),
                    ("MONTHLY_LLM_BUDGET", "Monthly LLM budget"),
                    ("NO_SET", "No set"),
                ],
                default="NO_SET",
                help_text="Several services can consume the same way; choosing a consumer is considered a good practice to avoid service mismatch behaviors.",
                max_length=22,
            ),
        ),
        migrations.RunPython(set_monthly_llm_budget_consumer, unset_monthly_llm_budget_consumer),
    ]
