# Generated by Django 5.2 on 2026-04-15

from django.db import migrations, models

GITHUB_COPILOT = "GITHUB_COPILOT"
NO_SET = "NO_SET"


def set_github_copilot_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="github-copilot").update(consumer=GITHUB_COPILOT)


def unset_github_copilot_consumer(apps, schema_editor):
    Service = apps.get_model("payments", "Service")
    Service.objects.filter(slug="github-copilot", consumer=GITHUB_COPILOT).update(consumer=NO_SET)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0034_service_consumer_monthly_llm_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="consumer",
            field=models.CharField(
                choices=[
                    ("ADD_CODE_REVIEW", "Add code review"),
                    ("LIVE_CLASS_JOIN", "Live class join"),
                    ("EVENT_JOIN", "Event join"),
                    ("JOIN_MENTORSHIP", "Join mentorship"),
                    ("READ_LESSON", "Read lesson"),
                    ("AI_INTERACTION", "AI Interaction"),
                    ("VPS_SERVER", "VPS server"),
                    ("MONTHLY_LLM_BUDGET", "Monthly LLM budget"),
                    ("GITHUB_COPILOT", "GitHub Copilot"),
                    ("NO_SET", "No set"),
                ],
                default="NO_SET",
                help_text="Several services can consume the same way; choosing a consumer is considered a good practice to avoid service mismatch behaviors.",
                max_length=22,
            ),
        ),
        migrations.RunPython(set_github_copilot_consumer, unset_github_copilot_consumer),
    ]

