# Generated by Django 5.2 on 2026-04-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_service_consumer_github_copilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfinancing',
            name='next_charge_pull_applied',
            field=models.BooleanField(db_index=True, default=False, help_text='True once next_payment_at was pulled earlier due to a consumable that depends on a third-party billing (e.g. VPS); atomic update limits this to once per plan financing even with parallel activations.'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='third_party_billing_cycle',
            field=models.BooleanField(db_index=True, default=False, help_text="If true, consumables for this item depend on a third-party billing period (e.g. VPS vendor). When the consumable is used (e.g. VPS provisioned) within 12h of that consumable's creation, internal next_payment_at may be pulled forward so we charge before that vendor cycle."),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_charge_pull_applied',
            field=models.BooleanField(db_index=True, default=False, help_text='True once next_payment_at was pulled earlier due to a consumable that depends on a third-party billing (e.g. VPS); atomic update limits this to once per subscription even with parallel activations.'),
        ),
    ]
