# Generated by Django 5.2 on 2026-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_plan_discontinued_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfinancing',
            name='initial_payment_amount',
            field=models.FloatField(blank=True, default=None, help_text="Optional upfront collected at financing creation that is NOT part of the regular installment schedule (i.e. a negotiated split: upfront + future installments). Set this only when the first payment amount differs from the recurring installment amount. Keep it null for standard installment plans (even if the first installment is paid immediately) and for negotiated single-pay purchases.", null=True),
        ),
    ]
