# Generated by Django 5.2 on 2026-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_clarify_planfinancing_initial_payment_amount_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfinancing',
            name='initial_payment_notes',
            field=models.CharField(blank=True, default=None, help_text='Staff justification/notes for negotiated payment terms. Used when staff agrees on a discounted single-pay amount, or when staff negotiates an upfront amount plus future installments.', max_length=250, null=True),
        ),
    ]
