# Generated by Django 3.2.23 on 2023-12-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0048_auto_20231128_1224'),
        ('payments', '0040_alter_serviceitem_is_renewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='cohort_set',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='Cohort set which the consumable belongs to',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='payments.cohortset'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='event_type_set',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='Event type set which the consumable belongs to',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='payments.eventtypeset'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='mentorship_service_set',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='Mentorship service set which the consumable belongs to',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='payments.mentorshipserviceset'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('COHORT_SET', 'Cohort set'),
                                            ('MENTORSHIP_SERVICE_SET', 'Mentorship service set'),
                                            ('EVENT_TYPE_SET', 'Event type set'),
                                            ('CHAT_SUPPORT', 'Chat support'), ('CODE_REVIEW', 'Code review'),
                                            ('AI_INTERACTION', 'AI interaction'),
                                            ('LEARNPACK_BUILD', 'Learnpack build'),
                                            ('LEARNPACK_TEST', 'Learnpack test')],
                                   default='COHORT_SET',
                                   help_text='Service type',
                                   max_length=22),
        ),
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('service', models.SlugField(help_text='Microservice slug')),
                ('app',
                 models.ForeignKey(blank=True,
                                   default=None,
                                   help_text='Subscription',
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='authenticate.app')),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='app_service',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    help_text='App service which the consumable belongs to',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='payments.appservice'),
        ),
    ]
