# Generated by Django 5.2 on 2026-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_clarify_planfinancing_initial_payment_notes_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfinancing',
            name='monthly_price',
            field=models.FloatField(default=0, help_text='Per-installment amount the user is expected to pay for this financing, frozen at creation time (not live catalog pricing). For negotiated single-pay purchases, this stores the agreed single payment amount (legacy name: it is not always monthly).'),
        ),
    ]
