# Generated by Django 5.2 on 2026-05-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_clarify_planfinancing_monthly_price_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PLAN_FINANCING', 'Plan Financing'), ('SUBSCRIPTION', 'Subscription'), ('GLOBAL', 'Global')], db_index=True, help_text='Scope that determines where this credit can be consumed', max_length=16)),
                ('amount', models.FloatField(help_text='Signed amount: positive when credit is added, negative when consumed')),
                ('entry_type', models.CharField(choices=[('CREDIT_ADDED', 'Credit Added'), ('CREDIT_CONSUMED', 'Credit Consumed')], db_index=True, help_text='Type of credit movement', max_length=16)),
                ('notes', models.CharField(blank=True, default=None, help_text='Optional notes about this credit movement', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_financing', models.ForeignKey(blank=True, default=None, help_text='Plan financing this credit movement belongs to (when scope is PLAN_FINANCING)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='payments.planfinancing')),
                ('source_deposit', models.ForeignKey(blank=True, default=None, help_text='StudentDeposit that originated this credit movement (when applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='payments.studentdeposit')),
                ('subscription', models.ForeignKey(blank=True, default=None, help_text='Subscription this credit movement belongs to (when scope is SUBSCRIPTION)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='payments.subscription')),
                ('user', models.ForeignKey(help_text='User this credit movement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
