# Generated by Django 5.0.6 on 2024-06-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_consumptionsession_operation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfinancing',
            name='conversion_info',
            field=models.JSONField(blank=True,
                                   default=None,
                                   help_text='UTMs and other conversion information.',
                                   null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='conversion_info',
            field=models.JSONField(blank=True,
                                   default=None,
                                   help_text='UTMs and other conversion information.',
                                   null=True),
        ),
    ]
