# Generated by Django 5.0.6 on 2024-06-25 16:38

import breathecode.utils.validators.language
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0064_academy_legal_name'),
        ('payments', '0046_consumptionsession_operation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(help_text='Description of the payment method', max_length=255)),
                ('third_party_link',
                 models.URLField(blank=True, default=None, help_text='Link of a third party payment method',
                                 null=True)),
                ('lang',
                 models.CharField(help_text='ISO 639-1 language code + ISO 3166-1 alpha-2 country code, e.g. en-US',
                                  max_length=5,
                                  validators=[breathecode.utils.validators.language.validate_language_code])),
                ('academy',
                 models.ForeignKey(blank=True,
                                   help_text='Academy owner',
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='admissions.academy')),
            ],
        ),
    ]
