# Generated by Django 5.0.6 on 2024-06-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_paymentmethod'),
        ('payments', '0047_planfinancing_conversion_info_and_more'),
    ]

    operations = []
