# Generated by Django 5.2 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0049_plan_time_of_life_optional_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="is_financing_managed_by_provider",
            field=models.BooleanField(
                default=False,
                help_text="When paying with plan financing (how_many_installments), charge the full financed total instead of the first installment. Only applies when provider_settings is non-empty.",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="logo_urls",
            field=models.JSONField(
                blank=True, default=list, help_text="Public logo URLs to display in checkout for this payment method"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plans where this payment method is available. Empty means it works for all plans on this academy.",
                related_name="payment_methods",
                to="payments.plan",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="provider_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific settings for this payment method. For Stripe Checkout hosted payments, set {'stripe_payment_method_types': ['klarna', 'affirm']}. Use is_financing_managed_by_provider for BNPL that finances installments externally.",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="stripe_id",
            field=models.CharField(
                blank=True, default=None, help_text="Stripe charge or checkout session id", max_length=255, null=True
            ),
        ),
    ]
