# Generated by Django 5.2 on 2026-06-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0049_paymentmethod_is_financing_managed_by_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Stripe charge or checkout session id",
                max_length=255,
                null=True,
            ),
        ),
    ]
