# Generated by Django 5.2 on 2026-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0050_paymentmethod_is_financing_managed_by_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="consumer",
            field=models.CharField(
                choices=[
                    ("ADD_CODE_REVIEW", "Add code review"),
                    ("LIVE_CLASS_JOIN", "Live class join"),
                    ("EVENT_JOIN", "Event join"),
                    ("JOIN_MENTORSHIP", "Join mentorship"),
                    ("READ_LESSON", "Read lesson"),
                    ("AI_INTERACTION", "AI Interaction"),
                    ("VPS_SERVER", "VPS server"),
                    ("LLM_BUDGET", "LLM budget"),
                    ("GITHUB_COPILOT", "GitHub Copilot"),
                    ("NO_SET", "No set"),
                ],
                default="NO_SET",
                help_text="Several services can consume the same way; choosing a consumer is considered a good practice to avoid service mismatch behaviors.",
                max_length=22,
            ),
        ),
    ]
