# Generated by Django 5.0.7 on 2024-08-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0051_service_consumer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the billing is managed externally outside of the system"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment method, null if it uses stripe",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="planfinancing",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the billing is managed externally outside of the system"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="externally_managed",
            field=models.BooleanField(
                default=False, help_text="If the billing is managed externally outside of the system"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="bag",
            field=models.ForeignKey(
                help_text="Bag", on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="payments.bag"
            ),
        ),
        migrations.CreateModel(
            name="ProofOfPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provided_payment_details",
                    models.TextField(
                        blank=True, default="", help_text="These details are provided by the user as proof of payment"
                    ),
                ),
                (
                    "confirmation_image_url",
                    models.URLField(
                        blank=True, default=None, help_text="URL of the confirmation image for the payment", null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, default=None, help_text="Reference for the payment", max_length=32, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done")],
                        db_index=True,
                        default="PENDING",
                        help_text="Bag status",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who provided these details",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="proof",
            field=models.OneToOneField(
                blank=True,
                help_text="Proof of payment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.proofofpayment",
            ),
        ),
    ]
