# Generated by Django 5.0.7 on 2024-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0053_invoice_externally_managed_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="consumer",
            field=models.CharField(
                choices=[
                    ("ADD_CODE_REVIEW", "Add code review"),
                    ("LIVE_CLASS_JOIN", "Live class join"),
                    ("EVENT_JOIN", "Event join"),
                    ("JOIN_MENTORSHIP", "Join mentorship"),
                    ("READ_LESSON", "Read lesson"),
                    ("AI_INTERACTION", "AI Interaction"),
                    ("NO_SET", "No set"),
                ],
                default="NO_SET",
                help_text="Service type",
                max_length=15,
            ),
        ),
    ]
