# Generated by Django 5.2 on 2026-08-08 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0019_academy_default_plan"),
        ("payments", "0054_planfeatures_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="academypaymentsettings",
            name="internal_billing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Internal billing settings between 4Geeks and this academy (not student checkout). Shape: {"active_users_billing": {"enabled": true, "price_per_user": 10.0, "currency": "USD", "exclude_cohort_slug_patterns": [".*land-a-job-in-tech.*", ".*pt-general.*"]}}. `enabled` toggles daily billing; `price_per_user` is the unit price; month charge = peak daily unique users × that price (from the peak day\'s snapshot); `exclude_cohort_slug_patterns` are regexes against cohort.slug.',
            ),
        ),
        migrations.CreateModel(
            name="ActiveUsersBill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_date", models.DateField(db_index=True, help_text="Calendar day this snapshot represents")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="That day's unique_user_count × price_per_user (daily audit, not the month invoice alone)",
                        max_digits=14,
                    ),
                ),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                (
                    "price_per_user",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Snapshot of active_users_billing.price_per_user at generation time",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Due"),
                            ("DISPUTED", "Disputed"),
                            ("IGNORED", "Ignored"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="DUE",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", help_text="e.g. 2026-08-07 active users", max_length=64),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bill-level clarifications (duplicates disregarded, cohorts skipped by exclusion patterns)",
                    ),
                ),
                (
                    "unique_user_count",
                    models.PositiveIntegerField(default=0, help_text="Distinct billable users that day"),
                ),
                (
                    "duplicate_user_count",
                    models.PositiveIntegerField(default=0, help_text="Enrollment rows skipped as duplicates that day"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Academy", on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_date", "-id"],
                "unique_together": {("academy", "billing_date")},
            },
        ),
        migrations.CreateModel(
            name="ActiveUsersBillItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Students attributed to this cohort after same-day dedupe"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="user_count × bill.price_per_user", max_digits=14
                    ),
                ),
                (
                    "user_ids",
                    models.JSONField(blank=True, default=list, help_text="Billed user ids for this cohort that day"),
                ),
                ("notes", models.TextField(blank=True, default="", help_text="Item-level clarifications")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Daily active users bill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.activeusersbill",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        help_text="Cohort this line represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.cohort",
                    ),
                ),
            ],
            options={
                "ordering": ["cohort_id"],
            },
        ),
    ]
