# Generated by Django 5.1.2 on 2025-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0054_alter_service_consumer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceitemfeature",
            name="one_line_desc",
            field=models.CharField(help_text="One line description of the service item", max_length=64),
        ),
        migrations.AlterField(
            model_name="serviceitemfeature",
            name="title",
            field=models.CharField(default=None, help_text="Title of the service item", max_length=64, null=True),
        ),
    ]
