# Generated by Django 5.1.6 on 2025-02-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0055_alter_serviceitemfeature_one_line_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academyservice",
            name="available_cohort_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available cohort sets to be sold in this service and plan",
                to="payments.cohortset",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Service item bundles that can be purchased with this plan",
                to="payments.academyservice",
            ),
        ),
    ]
