# Generated by Django 5.1.6 on 2025-03-10 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0056_planfinancing_how_many_installments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Date the subscription was created"
            ),
        ),
    ]
