# Generated by Django 5.1.7 on 2025-03-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0056_planfinancing_how_many_installments"),
    ]

    operations = [
        migrations.AddField(
            model_name="academyservice",
            name="available_cohort_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available cohort sets to be sold in this service and plan",
                to="payments.cohortset",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Service item bundles that can be purchased with this plan",
                to="payments.academyservice",
            ),
        ),
    ]
