# Generated by Django 5.2 on 2025-04-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0059_academyservice_pricing_ratio_exceptions_and_more"),
        ("payments", "0059_alter_cohortset_cohorts_alter_plan_service_items_and_more"),
    ]

    operations = []
