# Generated by Django 3.2.7 on 2021-11-06 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0025_merge_20211018_2259"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("price_per_hour", models.FloatField()),
                ("token", models.CharField(help_text="Used for the invitation", max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("INVITED", "Invited"), ("ACTIVE", "Active"), ("INNACTIVE", "Innactive")],
                        default="INVITED",
                        help_text="Options are: INVITEDACTIVEINNACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default=None,
                        help_text="Only use this if the user does not exist on breathecode already",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_online", models.BooleanField()),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("online_meeting_url", models.CharField(blank=True, default=None, max_length=255, null=True)),
                (
                    "online_recording_url",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="We encourace the mentors to record the session and share them with the students",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("INVITED", "Invited"), ("ACTIVE", "Active"), ("INNACTIVE", "Innactive")],
                        default="INVITED",
                        help_text="Options are: INVITEDACTIVEINNACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "agenda",
                    models.TextField(
                        blank=True, default=None, help_text="What will this mentorship be about", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Describe briefly what happened at the mentorship session",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("ended_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mentee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "mentor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mentorship.mentorprofile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipService",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("INNACTIVE", "Innactive")],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="service",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mentorship.mentorshipservice"),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="user",
            field=models.ForeignKey(
                help_text="If the user does not exist, you can use the email field instead",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
