# Generated by Django 3.2.9 on 2022-02-25 20:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mentorship", "0005_auto_20211111_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipservice",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                help_text="Default duration for mentorship sessions of this service",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipservice",
            name="logo_url",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="mentee_left_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Exact moment the mentee left the meeting for the last time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="mentor_joined_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Exact moment the mentor joined the meeting for the first time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="mentor_left_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Exact moment the mentor left the meeting for the last time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="name",
            field=models.CharField(
                blank=True, default=None, help_text="Room name, used on daily.co", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="ends_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Scheduled end date, will be used as meeting expiration as well",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="mentee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
