# Generated by Django 3.2.23 on 2024-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0026_calendlyorganization_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="availability_report",
            field=models.JSONField(blank=True, default=[], help_text="Mentor availability report"),
        ),
    ]
