# Generated by Django 5.0.2 on 2024-03-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0027_mentorprofile_availability_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="questions_and_answers",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
