# Generated by Django 5.1.1 on 2024-09-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0031_alter_mentorprofile_availability_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="meta",
            field=models.JSONField(
                blank=True, default=None, help_text="Meta information related to meeting vendor", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, default=None, help_text="Real end date (only if it started)", null=True
            ),
        ),
    ]
