# Generated by Django 5.2 on 2025-05-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0002_initial"),
        ("authenticate", "0002_initial"),
        ("events", "0001_initial"),
        ("feedback", "0001_initial"),
        ("mentorship", "0002_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="asset",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="registry.asset"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.cohort",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="event",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="live_class",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="events.liveclass"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="mentorship_session",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentorship.mentorshipsession",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="token",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authenticate.token",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="review",
            name="cohort",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="platform",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feedback.reviewplatform"),
        ),
        migrations.AddField(
            model_name="survey",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.cohort"),
        ),
        migrations.AddField(
            model_name="answer",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="You can group one or more answers in one survey, the survey does not belong to any student in particular but answers belong to the student that answered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.survey",
            ),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="academy",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy"),
        ),
        migrations.AddField(
            model_name="surveytemplate",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="feedback.surveytemplate",
            ),
        ),
        migrations.AddField(
            model_name="academyfeedbacksettings",
            name="cohort_survey_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for monthly cohort quality surveys, leave empty to disable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohort_survey_academies",
                to="feedback.surveytemplate",
            ),
        ),
        migrations.AddField(
            model_name="academyfeedbacksettings",
            name="event_survey_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for event quality surveys, leave empty to disable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_survey_academies",
                to="feedback.surveytemplate",
            ),
        ),
        migrations.AddField(
            model_name="academyfeedbacksettings",
            name="liveclass_survey_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for live class quality surveys, leave empty to disable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liveclass_survey_academies",
                to="feedback.surveytemplate",
            ),
        ),
        migrations.AddField(
            model_name="academyfeedbacksettings",
            name="mentorship_session_survey_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for mentorship session quality surveys, leave empty to disable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentorship_survey_academies",
                to="feedback.surveytemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveytemplate",
            unique_together={("original", "lang")},
        ),
    ]
