# Generated by Django 5.2 on 2025-09-26 16:23

import breathecode.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_academy",
            field=models.JSONField(
                blank=True,
                default={
                    "highest": "very likely",
                    "lowest": "not likely",
                    "survey_subject": "One question about the academy",
                    "title": "Based on your experience so far, how likely are you to recommend {} to others?",
                },
                help_text="Questions to ask about the academy",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
    ]
