# Generated by Django 5.2 on 2025-12-15 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_academy_welcome_video_academy_white_label_params"),
        ("feedback", "0004_add_feedback_tags_and_optional_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("learnpack_completed", "Learnpack Completion"),
                            ("course_completed", "Course Completion"),
                        ],
                        help_text="Tipo de evento que dispara la encuesta: learnpack_completed o course_completed",
                        max_length=50,
                    ),
                ),
                ("questions", models.JSONField(help_text="Estructura de preguntas (formato flexible para escalar)")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "asset_slugs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Para learnpacks: si está vacío, aplica a todos. Si tiene valores, solo a esos learnpacks específicos. Ejemplo: ['learnpack-1', 'learnpack-2']",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Para filtrar por academia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "cohorts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Si está vacío, aplica a todas las cohorts. Si tiene valores, solo a esas cohorts específicas",
                        to="admissions.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Survey Configuration",
                "verbose_name_plural": "Survey Configurations",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger_context",
                    models.JSONField(
                        help_text="Info del evento que disparó la encuesta: learnpack_slug, course_slug, etc."
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Respuestas del usuario guardadas en BD, null hasta que responda. Formato: {'q1': 5, 'q2': 4, 'q3': 'texto respuesta'}",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ANSWERED", "Answered"), ("EXPIRED", "Expired")],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, default=None, help_text="Timestamp de cuando respondió", null=True
                    ),
                ),
                (
                    "survey_config",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feedback.surveyconfiguration"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
            },
        ),
    ]
