# Generated by Django 5.2 on 2025-12-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_academy_welcome_video_academy_white_label_params"),
        ("feedback", "0005_surveyconfiguration_surveyresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestionTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "questions",
                    models.JSONField(
                        help_text="Questions JSON structure (same shape as SurveyConfiguration.questions)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Survey Question Template",
                "verbose_name_plural": "Survey Question Templates",
            },
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="email_opened_at",
            field=models.DateTimeField(
                blank=True, default=None, help_text="First time the survey email was opened", null=True
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="opened_at",
            field=models.DateTimeField(
                blank=True, default=None, help_text="First time the survey was opened", null=True
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="questions_snapshot",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Snapshot of questions used to render/validate this response.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="academy",
            field=models.ForeignKey(
                help_text="Used to scope configurations by academy",
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.academy",
            ),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="asset_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For learnpacks: if empty, applies to all. If set, applies only to those learnpacks. Example: ['learnpack-1', 'learnpack-2']",
            ),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="cohorts",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, applies to all cohorts. If set, applies only to those cohorts.",
                to="admissions.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="questions",
            field=models.JSONField(help_text="Questions JSON structure (flexible format)"),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="trigger_type",
            field=models.CharField(
                blank=True,
                choices=[("learnpack_completed", "Learnpack Completion"), ("course_completed", "Course Completion")],
                default=None,
                help_text="Realtime trigger type for this configuration (learnpack_completed or course_completed). For email/list-based studies, this can be null.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="answered_at",
            field=models.DateTimeField(blank=True, default=None, help_text="When the survey was answered", null=True),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OPENED", "Opened"),
                    ("PARTIAL", "Partial"),
                    ("ANSWERED", "Answered"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="trigger_context",
            field=models.JSONField(
                help_text="Context that originated the survey (e.g. learnpack_slug, course_slug, cohort_id, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="surveyconfiguration",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional questions template. If set, questions are sourced from the template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_configurations",
                to="feedback.surveyquestiontemplate",
            ),
        ),
        migrations.CreateModel(
            name="SurveyStudy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("starts_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("ends_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "max_responses",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Max ANSWERED responses allowed (null = unlimited)",
                        null=True,
                    ),
                ),
                ("stats", models.JSONField(blank=True, default=dict, help_text="Aggregated stats for this study")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
                (
                    "survey_configurations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Survey configurations that belong to this study",
                        related_name="survey_studies",
                        to="feedback.surveyconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Study",
                "verbose_name_plural": "Survey Studies",
            },
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="survey_study",
            field=models.ForeignKey(
                blank=True,
                help_text="Study/campaign that originated this survey response (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_responses",
                to="feedback.surveystudy",
            ),
        ),
    ]
