# Generated by Django 5.2 on 2025-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_surveyquestiontemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="trigger_type",
            field=models.CharField(
                blank=True,
                choices=[("learnpack_completed", "Learnpack Completion"), ("course_completed", "Course Completion")],
                default=None,
                help_text="Realtime trigger type for this configuration (learnpack_completed or course_completed). only for realtime studies where a modal appears after a user completes an activityFor email/list-based studies, this can be null.",
                max_length=50,
                null=True,
            ),
        ),
    ]
