# Generated by Django 5.2 on 2025-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_surveyconfiguration_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyconfiguration",
            name="syllabus",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional filter to scope surveys by syllabus/module. Shape: {'syllabus': '<syllabus_slug>', 'version': <int>, 'module': <int>, 'asset_slug': '<slug>'}. All keys are optional; if 'module' is omitted, it applies to the whole syllabus/version.",
            ),
        ),
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="trigger_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("module_completed", "Module Completion"),
                    ("syllabus_completed", "Syllabus Completion"),
                    ("learnpack_completed", "Learnpack Completion"),
                    ("course_completed", "Course Completion"),
                ],
                default=None,
                help_text="Realtime trigger type for this configuration (learnpack_completed, course_completed, module_completed or syllabus_completed). Only for realtime studies where a modal appears after a user completes an activity. For email/list-based studies, this can be null.",
                max_length=50,
                null=True,
            ),
        ),
    ]
