# Generated by Django 5.2 on 2025-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_surveyconfiguration_syllabus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyconfiguration",
            name="priority",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Probability of receiving this survey when the trigger condition is met (0-100). P(Survey | Module) = priority%. Example: 20.0 means 20% of users who complete this module will receive the survey. 100.0 means all users will receive it. If null, defaults to 100% (all users receive the survey).",
                null=True,
            ),
        ),
    ]
