# Generated by Django 5.2 on 2026-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_alter_surveyconfiguration_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyconfiguration",
            name="priority",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Cumulative target: Proportion of users who should have answered the survey by this module (0-100). Interpreted as cumulative distribution target, not direct probability. Example: Module 1 priority=30, Module 3 priority=75, Module 5 priority=100 means: 30% should answer by module 1, 75% by module 3, 100% by module 5. The system uses conditional hazard-based sampling to achieve this distribution. If null, defaults to 100% (all users should answer by this module).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveystudy",
            name="survey_configurations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Survey configurations that belong to this study. All configurations must have the same trigger_type. If you need different trigger types, create separate studies.",
                related_name="survey_studies",
                to="feedback.surveyconfiguration",
            ),
        ),
    ]
