# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_alter_surveyconfiguration_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveystudy",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("FINISHED", "Finished"),
                    ("DELETED", "Deleted"),
                ],
                default="DRAFT",
                help_text=(
                    "Status of the study. "
                    "DRAFT: not started, "
                    "ACTIVE: currently running, "
                    "FINISHED: completed (ended), "
                    "DELETED: archived/hidden from frontend."
                ),
                max_length=15,
            ),
        ),
    ]

