# Generated by Django 5.2

import breathecode.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0012_add_status_to_surveystudy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_academy",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_academy,
                help_text="Questions to ask about the academy",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_cohort",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_cohort,
                help_text="Questions to ask about a cohort",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_event",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_event,
                help_text="Questions to ask about an event",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_liveclass_mentor",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_liveclass_mentor,
                help_text="Questions to ask about a live class mentor",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_mentor",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_mentor,
                help_text="Questions to ask about a mentor",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_mentor_communication",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_mentor_communication,
                help_text="Questions to ask about mentor communication during class",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_mentor_participation",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_mentor_participation,
                help_text="Questions to ask about class how the mentor answers and encoursges participation",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_mentorshipsession",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_mentorshipsession,
                help_text="Questions to ask about a mentorship session",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
        migrations.AlterField(
            model_name="surveytemplate",
            name="when_asking_platform",
            field=models.JSONField(
                blank=True,
                default=breathecode.feedback.models.default_when_asking_platform,
                help_text="Questions to ask about the 4Geeks.com platform",
                null=True,
                validators=[breathecode.feedback.models.validate_question_structure],
            ),
        ),
    ]
