# Generated by Django 3.1.4 on 2020-12-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_answer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='token',
        ),
    ]
