# Generated by Django 3.1.4 on 2020-12-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_auto_20201110_0727'),
        ('feedback', '0013_remove_answer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='token',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.token'),
        ),
    ]
