# Generated by Django 3.1.4 on 2021-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0015_auto_20210129_2143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="comment",
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[("SENT", "Sent"), ("PENDING", "Pending"), ("PARTIAL", "Partial"), ("FATAL", "Fatal")],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
