# Generated by Django 3.2.5 on 2021-07-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0017_survey_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
