# Generated by Django 3.2.13 on 2022-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_survey_response_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nps_previous_rating',
            field=models.FloatField(blank=True,
                                    default=None,
                                    help_text='Automatically calculated based on NPS survey responses',
                                    null=True),
        ),
    ]
