# Generated by Django 5.0.7 on 2024-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0028_review_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="platform_and_content",
            field=models.BooleanField(default=False),
        ),
    ]
