# Generated by Django 5.1.6 on 2025-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0030_answer_asset_answer_live_class_survey_is_customized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_by_slug",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Ideal to create new standarized questions",
                max_length=100,
                null=True,
            ),
        ),
    ]
