# Generated by Django 5.1.6 on 2025-03-07 17:14

import breathecode.feedback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
        ("feedback", "0031_alter_answer_question_by_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("lang", models.CharField(help_text="Two-letter language code", max_length=2)),
                (
                    "is_shared",
                    models.BooleanField(default=False, help_text="If true, other academies can use this template"),
                ),
                (
                    "when_asking_event",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very likely",
                            "lowest": "not likely",
                            "survey_subject": "One question about the event you attended today",
                            "title": "How likely are you to recommend events like this to your friends and family?",
                        },
                        help_text="Questions to ask about an event",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_mentor",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very good",
                            "lowest": "not good",
                            "survey_subject": "We need your feedback",
                            "title": "How has your experience been with your mentor {} so far?",
                        },
                        help_text="Questions to ask about a mentor",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_cohort",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very good",
                            "lowest": "not good",
                            "survey_subject": "We need your feedback",
                            "title": "How has your experience been studying {} so far?",
                        },
                        help_text="Questions to ask about a cohort",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_academy",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very likely",
                            "lowest": "not likely",
                            "survey_subject": "We need your feedback",
                            "title": "How likely are you to recommend {} to your friends and family?",
                        },
                        help_text="Questions to ask about the academy",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_mentorshipsession",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very useful",
                            "lowest": "not useful",
                            "survey_subject": "We need your feedback",
                            "title": "How was your experience in your mentoring session with {}?",
                        },
                        help_text="Questions to ask about a mentorship session",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_platform",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very good",
                            "lowest": "not good",
                            "survey_subject": "We need your feedback",
                            "title": "How has your experience been with the platform and content so far?",
                        },
                        help_text="Questions to ask about the 4Geeks.com platform",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_liveclass_mentor",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very good",
                            "lowest": "not good",
                            "survey_subject": "We need your feedback",
                            "title": "How would you rate your teacher's performance today?",
                        },
                        help_text="Questions to ask about a live class mentor",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_mentor_communication",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very clear",
                            "lowest": "not clear",
                            "survey_subject": "We need your feedback",
                            "title": "How clear was the teacher in explaining the concepts?",
                        },
                        help_text="Questions to ask about mentor communication during class",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "when_asking_mentor_participation",
                    models.JSONField(
                        blank=True,
                        default={
                            "highest": "very good",
                            "lowest": "not good",
                            "survey_subject": "We need your feedback",
                            "title": "Did the teacher encourage participation and effectively resolve your doubts?",
                        },
                        help_text="Questions to ask about class how the mentor answers and encoursges participation",
                        null=True,
                        validators=[breathecode.feedback.models.validate_question_structure],
                    ),
                ),
                (
                    "additional_questions",
                    models.JSONField(
                        blank=True, help_text="Additional custom questions in the same structure", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admissions.academy")),
            ],
            options={
                "unique_together": {("slug", "lang")},
            },
        ),
    ]
