# Generated by Django 5.2 on 2025-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0034_alter_surveytemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="title",
            field=models.CharField(
                blank=True, help_text="Automatically set from the questions inside", max_length=200, null=True
            ),
        ),
    ]
