# Generated by Django 5.2 on 2025-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0034_alter_surveytemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="template_slug",
            field=models.CharField(
                blank=True,
                help_text="Slug of the template that was used to create this survey",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="title",
            field=models.CharField(
                blank=True, help_text="Automatically set from the questions inside", max_length=200, null=True
            ),
        ),
    ]
