# Generated by Django 5.2 on 2025-12-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_add_reasoning_to_syllabus_version"),
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyNotifySettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variable overrides for notification templates.\nFormat:\n  - Template-specific: 'template.SLUG.VARIABLE': 'value'\n  - Global (all templates): 'global.VARIABLE': 'value'\nSupports interpolation: {{global.VARIABLE}} or {{template.slug.VARIABLE}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_settings",
                        to="admissions.academy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academy Notification Settings",
                "verbose_name_plural": "Academy Notification Settings",
            },
        ),
    ]
