# Generated by Django 3.1.2 on 2020-11-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_auto_20201105_0612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackchannel",
            name="purpose",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="slackchannel",
            name="topic",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
