# Generated by Django 5.2 on 2025-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_add_academy_notify_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="academynotifysettings",
            name="disabled_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of template slugs to disable for this academy. Example: ['welcome_academy', 'nps_survey']",
            ),
        ),
    ]
