# Generated by Django 5.2 on 2026-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_add_disabled_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academynotifysettings',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text="Variable overrides for notification templates.\nFormat:\n  - Template-specific: 'template.SLUG.VARIABLE': 'value'\n  - Per-language: 'template.SLUG.VARIABLE.en' / 'template.SLUG.VARIABLE.es': 'value'\n  - Global (all templates): 'global.VARIABLE': 'value'\nSupports interpolation: {{global.VARIABLE}} or {{template.slug.VARIABLE}}"),
        ),
    ]
