# Generated by Django 5.2 on 2026-10-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0021_alter_cohort_cohorts_order"),
        ("notify", "0004_alter_academynotifysettings_template_variables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="Kind of notification, like plan-expired", max_length=60)),
                ("title", models.CharField(max_length=150)),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", help_text="Plain text, already in the language of the user"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Where the frontend sends the user on click, a path of the app or a full URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=None, null=True)),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="When set, the user gets at most one notification per slug and key",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.academy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "read_at"], name="inbox_notification_user_read")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key__isnull", False)),
                        fields=("user", "slug", "dedupe_key"),
                        name="unique_inbox_notification_per_dedupe_key",
                    )
                ],
            },
        ),
    ]
