# Generated by Django 3.1.4 on 2020-12-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0007_auto_20201111_2218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackteam",
            name="credentials",
        ),
    ]
