# Generated by Django 5.0.6 on 2024-06-17 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0011_alter_hook_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HookError",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=255)),
                ("event", models.CharField(db_index=True, max_length=64, verbose_name="Event")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hooks", models.ManyToManyField(blank=True, related_name="errors", to=settings.HOOK_CUSTOM_MODEL)),
            ],
        ),
    ]
